import { GraphData } from "@/types";

export const INITIAL_GRAPH_DATA: GraphData = {
  nodes: [
    // ── Companies ──────────────────────────────────────────────
    { id: "openai",    label: "OpenAI",         type: "company", description: "Creator of GPT-4, o1, and ChatGPT", size: 42, color: "#10a37f", url: "https://openai.com" },
    { id: "anthropic", label: "Anthropic",       type: "company", description: "Creator of Claude — safety-focused AI lab", size: 38, color: "#d97706", url: "https://anthropic.com" },
    { id: "google",    label: "Google DeepMind", type: "company", description: "Creator of Gemini, AlphaFold, and Gemma", size: 40, color: "#4285f4", url: "https://deepmind.google" },
    { id: "meta",      label: "Meta AI",         type: "company", description: "Creator of Llama open-source models", size: 36, color: "#0866ff", url: "https://ai.meta.com" },
    { id: "mistral",   label: "Mistral AI",      type: "company", description: "European AI research lab, creator of Mixtral", size: 30, color: "#ff7000", url: "https://mistral.ai" },
    { id: "deepseek",  label: "DeepSeek",        type: "company", description: "Chinese AI research lab, open-source focus", size: 32, color: "#1e3a8a", url: "https://deepseek.com" },
    { id: "xai",       label: "xAI",             type: "company", description: "Elon Musk's AI company, creator of Grok", size: 28, color: "#c0c0c0", url: "https://x.ai" },
    { id: "microsoft", label: "Microsoft",       type: "company", description: "OpenAI partner; Azure AI and Phi models", size: 34, color: "#00a4ef", url: "https://microsoft.com/ai" },
    { id: "huggingface", label: "Hugging Face",  type: "company", description: "ML community platform and model hub for open-source AI", size: 32, color: "#ff9900", url: "https://huggingface.co" },
    { id: "cohere",    label: "Cohere",          type: "company", description: "Enterprise NLP platform — Command R+ and Embed models", size: 24, color: "#d946ef", url: "https://cohere.com" },
    { id: "perplexity", label: "Perplexity AI",  type: "company", description: "AI-powered answer engine and search", size: 24, color: "#06b6d4", url: "https://perplexity.ai" },
    { id: "groq",      label: "Groq",            type: "company", description: "Ultra-fast LLM inference with custom LPU hardware", size: 22, color: "#00d4ff", url: "https://groq.com" },
    { id: "stability", label: "Stability AI",    type: "company", description: "Open-source generative image and audio AI", size: 22, color: "#7c3aed", url: "https://stability.ai" },
    { id: "elevenlabs", label: "ElevenLabs",     type: "company", description: "AI voice generation, cloning, and dubbing", size: 22, color: "#f59e0b", url: "https://elevenlabs.io" },
    { id: "runway",    label: "Runway",          type: "company", description: "AI-powered video generation and creative tools", size: 22, color: "#ec4899", url: "https://runwayml.com" },
    { id: "together",  label: "Together AI",     type: "company", description: "Cloud platform for open-source model hosting and inference", size: 22, color: "#10b981", url: "https://together.ai" },

    // ── Models ─────────────────────────────────────────────────
    { id: "gpt4o",      label: "GPT-4o",           type: "model", description: "OpenAI's flagship multimodal model", size: 34, color: "#10a37f", url: "https://platform.openai.com/docs/models/gpt-4o" },
    { id: "o1",         label: "o1 / o3",           type: "model", description: "OpenAI's reasoning-focused chain-of-thought models", size: 32, color: "#10a37f", url: "https://platform.openai.com/docs/models/o1" },
    { id: "gpt5",       label: "GPT-5",             type: "model", description: "OpenAI's next-generation frontier model", size: 28, color: "#10a37f", url: "https://openai.com/index/gpt-5" },
    { id: "claude35",   label: "Claude 3.5 Sonnet", type: "model", description: "Anthropic's top coding and reasoning model", size: 32, color: "#d97706", url: "https://www.anthropic.com/claude/sonnet" },
    { id: "claude3opus", label: "Claude 3 Opus",    type: "model", description: "Anthropic's most intelligent released model", size: 28, color: "#d97706", url: "https://www.anthropic.com/claude/opus" },
    { id: "claude4sonnet", label: "Claude Sonnet 4", type: "model", description: "Anthropic's latest flagship balanced model", size: 34, color: "#d97706", url: "https://www.anthropic.com/claude" },
    { id: "gemini15",   label: "Gemini 1.5 Pro",    type: "model", description: "Google's 1M-token long-context model", size: 32, color: "#4285f4", url: "https://deepmind.google/technologies/gemini/pro/" },
    { id: "gemma2",     label: "Gemma 2",           type: "model", description: "Google's open-source SLM family (2B–27B)", size: 22, color: "#4285f4", url: "https://ai.google.dev/gemma" },
    { id: "llama3",     label: "Llama 3",           type: "model", description: "Meta's open-source flagship (8B, 70B, 405B)", size: 30, color: "#0866ff", url: "https://llama.meta.com/" },
    { id: "mistral7b",  label: "Mistral 7B",        type: "model", description: "Efficient open-source model with sliding window attention", size: 24, color: "#ff7000", url: "https://mistral.ai/news/announcing-mistral-7b/" },
    { id: "mixtral8x22", label: "Mixtral 8x22B",    type: "model", description: "Mistral's Mixture-of-Experts flagship", size: 26, color: "#ff7000", url: "https://mistral.ai/news/mixtral-8x22b/" },
    { id: "deepseekv3", label: "DeepSeek V3",       type: "model", description: "State-of-art open-source MoE model", size: 30, color: "#1e3a8a", url: "https://github.com/deepseek-ai/DeepSeek-V3" },
    { id: "grok2",      label: "Grok-2",            type: "model", description: "xAI's reasoning and coding model", size: 24, color: "#c0c0c0", url: "https://x.ai/grok" },
    { id: "phi4",       label: "Phi-4",             type: "model", description: "Microsoft's small but capable SLM", size: 22, color: "#00a4ef", url: "https://azure.microsoft.com/en-us/blog/phi-4-microsofts-newest-small-language-model/" },
    { id: "phi3",       label: "Phi-3 Mini",        type: "model", description: "Microsoft's compact on-device model", size: 20, color: "#00a4ef", url: "https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/" },
    { id: "qwen25",     label: "Qwen 2.5",          type: "model", description: "Alibaba's multilingual open-source model", size: 24, color: "#ef4444", url: "https://qwenlm.github.io/blog/qwen2.5/" },
    { id: "commandr",   label: "Command R+",        type: "model", description: "Cohere's RAG-optimized enterprise model", size: 22, color: "#d946ef", url: "https://cohere.com/command" },
    { id: "flux1",      label: "FLUX.1",            type: "model", description: "Black Forest Labs' state-of-art image generation model", size: 22, color: "#7c3aed", url: "https://blackforestlabs.ai/" },

    // ── Concepts ───────────────────────────────────────────────
    { id: "rag",           label: "RAG",              type: "concept", description: "Retrieval Augmented Generation — ground LLMs in external knowledge", size: 32, color: "#6366f1" },
    { id: "agents",        label: "AI Agents",        type: "concept", description: "Autonomous AI systems that plan, use tools, and complete tasks", size: 34, color: "#8b5cf6" },
    { id: "mcp",           label: "MCP",              type: "concept", description: "Model Context Protocol — standard interface for tool use by Anthropic", size: 28, color: "#d97706" },
    { id: "reasoning",     label: "Reasoning",        type: "concept", description: "Advanced multi-step problem solving and logical inference", size: 30, color: "#6366f1" },
    { id: "multimodal",    label: "Multimodal AI",    type: "concept", description: "AI that understands and generates text, images, audio, and video", size: 28, color: "#06b6d4" },
    { id: "rlhf",          label: "RLHF",             type: "concept", description: "Reinforcement Learning from Human Feedback — alignment technique", size: 26, color: "#6366f1" },
    { id: "finetuning",    label: "Fine-tuning",      type: "concept", description: "Adapting pre-trained models to specific tasks and domains", size: 26, color: "#6366f1" },
    { id: "alignment",     label: "AI Alignment",     type: "concept", description: "Making AI systems safe, helpful, and aligned with human values", size: 28, color: "#ef4444" },
    { id: "embeddings",    label: "Embeddings",       type: "concept", description: "Dense vector representations capturing semantic meaning", size: 24, color: "#06b6d4" },
    { id: "automation",    label: "AI Automation",    type: "concept", description: "Automated AI workflows, pipelines, and business processes", size: 26, color: "#f59e0b" },
    { id: "tooluse",       label: "Tool Use",         type: "concept", description: "AI models calling external APIs, code interpreters, and databases", size: 28, color: "#06b6d4" },
    { id: "functioncalling", label: "Function Calling", type: "concept", description: "Structured JSON output for deterministic API interactions", size: 22, color: "#06b6d4" },
    { id: "longtermemory", label: "Long-term Memory", type: "concept", description: "Persistent memory systems for agents across sessions", size: 22, color: "#8b5cf6" },
    { id: "synthdata",     label: "Synthetic Data",   type: "concept", description: "AI-generated training data for model improvement", size: 20, color: "#f59e0b" },
    { id: "prompteng",     label: "Prompt Engineering", type: "concept", description: "Crafting effective prompts for optimal LLM behavior", size: 28, color: "#06b6d4" },

    // ── Frameworks ─────────────────────────────────────────────
    { id: "langchain",  label: "LangChain",   type: "framework", description: "Most popular framework for building LLM-powered applications", size: 30, color: "#22c55e" },
    { id: "langgraph",  label: "LangGraph",   type: "framework", description: "Graph-based multi-agent orchestration built on LangChain", size: 26, color: "#22c55e" },
    { id: "crewai",     label: "CrewAI",      type: "framework", description: "Role-based multi-agent collaboration framework", size: 24, color: "#f59e0b" },
    { id: "autogen",    label: "AutoGen",     type: "framework", description: "Microsoft's conversational multi-agent framework", size: 24, color: "#00a4ef" },
    { id: "llamaindex", label: "LlamaIndex",  type: "framework", description: "Data framework for connecting LLMs to private data", size: 26, color: "#f59e0b" },
    { id: "dspy",       label: "DSPy",        type: "framework", description: "Declarative self-improving LLM pipeline programming", size: 22, color: "#06b6d4" },
    { id: "haystack",   label: "Haystack",    type: "framework", description: "End-to-end NLP search and RAG framework", size: 22, color: "#ef4444" },
    { id: "openrouter", label: "OpenRouter",  type: "framework", description: "Unified API gateway for 200+ AI models", size: 28, color: "#6366f1" },
    { id: "ollama",     label: "Ollama",      type: "framework", description: "Run LLMs locally with a simple CLI and API", size: 26, color: "#22c55e" },

    // ── Tools ──────────────────────────────────────────────────
    { id: "vectordb",     label: "Vector Databases", type: "tool", description: "Semantic similarity search infrastructure for AI applications", size: 26, color: "#06b6d4" },
    { id: "pinecone",     label: "Pinecone",         type: "tool", description: "Managed vector database — serverless, fast, and scalable", size: 22, color: "#0ea5e9" },
    { id: "chroma",       label: "ChromaDB",         type: "tool", description: "Open-source in-memory + persistent embedding database", size: 20, color: "#7c3aed" },
    { id: "wandb",        label: "Weights & Biases", type: "tool", description: "ML experiment tracking, model evaluation, and deployment", size: 22, color: "#ffbe00" },
    { id: "langsmith",    label: "LangSmith",        type: "tool", description: "LLM app observability, tracing, evaluation, and testing", size: 22, color: "#22c55e" },
    { id: "huggingfacehub", label: "HF Hub",         type: "tool", description: "Repository hosting 500k+ models, datasets, and Spaces", size: 28, color: "#ff9900" },

    // ── Research Papers ────────────────────────────────────────
    { id: "attention",     label: "Attention Mechanism", type: "research", description: "Scaled dot-product attention — the core innovation of transformers", size: 26, color: "#8b5cf6" },
    { id: "transformers",  label: "Transformers",        type: "research", description: "'Attention Is All You Need' — the foundation of modern LLMs", size: 30, color: "#8b5cf6" },
    { id: "scaling",       label: "Scaling Laws",        type: "research", description: "How model capability scales predictably with compute and data", size: 24, color: "#8b5cf6" },
    { id: "constitutional", label: "Constitutional AI",  type: "research", description: "Anthropic's principle-based approach to AI safety training", size: 22, color: "#d97706" },
    { id: "cot",           label: "Chain of Thought",    type: "research", description: "Reasoning via intermediate step-by-step thinking (Wei et al.)", size: 26, color: "#8b5cf6" },
    { id: "tot",           label: "Tree of Thoughts",    type: "research", description: "Deliberate problem solving by exploring reasoning branches", size: 22, color: "#8b5cf6" },
    { id: "moe",           label: "Mixture of Experts",  type: "research", description: "Sparse gating routes tokens to specialist sub-networks", size: 26, color: "#8b5cf6" },
    { id: "lora",          label: "LoRA / PEFT",         type: "research", description: "Low-rank adaptation for parameter-efficient fine-tuning", size: 24, color: "#8b5cf6" },
    { id: "dpo",           label: "DPO",                 type: "research", description: "Direct Preference Optimization — simpler alternative to RLHF", size: 22, color: "#d97706" },
    { id: "flashattn",     label: "Flash Attention",     type: "research", description: "IO-aware exact attention algorithm enabling long contexts", size: 24, color: "#8b5cf6" },

    // ── YouTube Channels ───────────────────────────────────────
    { id: "yt-two-minute", label: "Two Minute Papers 🎬", type: "tool", description: "AI research explained clearly — Károly Zsolnai-Fehér", size: 22, color: "#ff0000", url: "https://youtube.com/@TwoMinutePapers" },
    { id: "yt-ai-explained", label: "AI Explained 🎬",   type: "tool", description: "Clear AI news and concept breakdowns", size: 20, color: "#ff0000", url: "https://youtube.com/@aiexplained-official" },
    { id: "yt-karpathy",   label: "Andrej Karpathy 🎬",  type: "tool", description: "Deep learning from first principles by ex-OpenAI director", size: 26, color: "#ff0000", url: "https://youtube.com/@AndrejKarpathy" },
    { id: "yt-fireship",   label: "Fireship 🎬",         type: "tool", description: "Fast-paced AI and dev tutorials", size: 20, color: "#ff0000", url: "https://youtube.com/@Fireship" },
    { id: "yt-mattwolfe",  label: "Matt Wolfe AI 🎬",    type: "tool", description: "AI tool reviews, news, and weekly roundups", size: 20, color: "#ff0000", url: "https://youtube.com/@mreflow" },
    { id: "yt-yannic",     label: "Yannic Kilcher 🎬",   type: "tool", description: "Deep ML paper reviews and research commentary", size: 22, color: "#ff0000", url: "https://youtube.com/@YannicKilcher" },
  ],

  links: [
    // ── Company → Model ────────────────────────────────────────
    { source: "openai",    target: "gpt4o",       label: "created" },
    { source: "openai",    target: "o1",          label: "created" },
    { source: "openai",    target: "gpt5",        label: "created" },
    { source: "anthropic", target: "claude35",    label: "created" },
    { source: "anthropic", target: "claude3opus", label: "created" },
    { source: "anthropic", target: "claude4sonnet", label: "created" },
    { source: "google",    target: "gemini15",    label: "created" },
    { source: "google",    target: "gemma2",      label: "created" },
    { source: "meta",      target: "llama3",      label: "created" },
    { source: "mistral",   target: "mistral7b",   label: "created" },
    { source: "mistral",   target: "mixtral8x22", label: "created" },
    { source: "deepseek",  target: "deepseekv3",  label: "created" },
    { source: "xai",       target: "grok2",       label: "created" },
    { source: "microsoft", target: "phi4",        label: "created" },
    { source: "microsoft", target: "phi3",        label: "created" },
    { source: "cohere",    target: "commandr",    label: "created" },
    { source: "stability", target: "flux1",       label: "created" },

    // ── Company → Tool/Framework ───────────────────────────────
    { source: "microsoft",  target: "autogen",      label: "created" },
    { source: "huggingface", target: "huggingfacehub", label: "operates" },
    { source: "groq",       target: "llama3",       label: "accelerates" },
    { source: "groq",       target: "mixtral8x22",  label: "accelerates" },
    { source: "together",   target: "llama3",       label: "hosts" },
    { source: "together",   target: "mixtral8x22",  label: "hosts" },
    { source: "perplexity", target: "rag",          label: "uses" },
    { source: "perplexity", target: "agents",       label: "uses" },
    { source: "runway",     target: "multimodal",   label: "advances" },
    { source: "elevenlabs", target: "multimodal",   label: "advances" },

    // ── Concept relationships ──────────────────────────────────
    { source: "agents",    target: "rag",          label: "uses" },
    { source: "agents",    target: "mcp",          label: "uses" },
    { source: "agents",    target: "tooluse",      label: "requires" },
    { source: "agents",    target: "longtermemory", label: "benefits from" },
    { source: "agents",    target: "automation",   label: "enables" },
    { source: "rag",       target: "vectordb",     label: "requires" },
    { source: "rag",       target: "embeddings",   label: "uses" },
    { source: "vectordb",  target: "embeddings",   label: "stores" },
    { source: "rlhf",      target: "alignment",    label: "enables" },
    { source: "dpo",       target: "alignment",    label: "advances" },
    { source: "dpo",       target: "rlhf",         label: "alternative to" },
    { source: "mcp",       target: "tooluse",      label: "standardizes" },
    { source: "mcp",       target: "automation",   label: "enables" },
    { source: "tooluse",   target: "functioncalling", label: "implemented via" },
    { source: "prompteng", target: "agents",       label: "optimizes" },
    { source: "cot",       target: "prompteng",    label: "technique of" },
    { source: "synthdata", target: "finetuning",   label: "used in" },

    // ── Research → concepts ────────────────────────────────────
    { source: "anthropic", target: "constitutional", label: "developed" },
    { source: "constitutional", target: "alignment", label: "advances" },
    { source: "anthropic", target: "mcp",          label: "created" },
    { source: "attention", target: "transformers", label: "foundation of" },
    { source: "transformers", target: "gpt4o",     label: "powers" },
    { source: "transformers", target: "claude35",  label: "powers" },
    { source: "transformers", target: "gemini15",  label: "powers" },
    { source: "transformers", target: "llama3",    label: "powers" },
    { source: "scaling",   target: "gpt5",         label: "guides" },
    { source: "rlhf",      target: "gpt4o",        label: "trains" },
    { source: "rlhf",      target: "claude35",     label: "trains" },
    { source: "cot",       target: "reasoning",    label: "improves" },
    { source: "tot",       target: "reasoning",    label: "improves" },
    { source: "tot",       target: "cot",          label: "extends" },
    { source: "moe",       target: "mixtral8x22",  label: "powers" },
    { source: "moe",       target: "deepseekv3",   label: "powers" },
    { source: "lora",      target: "finetuning",   label: "method for" },
    { source: "flashattn", target: "transformers", label: "optimizes" },
    { source: "flashattn", target: "gemini15",     label: "enables" },

    // ── Framework relationships ────────────────────────────────
    { source: "langchain", target: "langgraph",   label: "evolved into" },
    { source: "langchain", target: "langsmith",   label: "monitored by" },
    { source: "langchain", target: "chroma",      label: "integrates" },
    { source: "langchain", target: "pinecone",    label: "integrates" },
    { source: "llamaindex", target: "rag",        label: "enables" },
    { source: "llamaindex", target: "vectordb",   label: "integrates" },
    { source: "dspy",      target: "prompteng",   label: "automates" },
    { source: "haystack",  target: "rag",         label: "enables" },
    { source: "crewai",    target: "agents",      label: "built with" },
    { source: "autogen",   target: "agents",      label: "built with" },
    { source: "langgraph", target: "agents",      label: "built with" },
    { source: "agents",    target: "langchain",   label: "built with" },

    // ── OpenRouter / Ollama access ─────────────────────────────
    { source: "openrouter", target: "gpt4o",      label: "provides access" },
    { source: "openrouter", target: "claude35",   label: "provides access" },
    { source: "openrouter", target: "deepseekv3", label: "provides access" },
    { source: "openrouter", target: "o1",         label: "provides access" },
    { source: "openrouter", target: "mixtral8x22", label: "provides access" },
    { source: "openrouter", target: "commandr",   label: "provides access" },
    { source: "ollama",    target: "llama3",      label: "runs" },
    { source: "ollama",    target: "mistral7b",   label: "runs" },
    { source: "ollama",    target: "deepseekv3",  label: "runs" },
    { source: "ollama",    target: "phi3",        label: "runs" },
    { source: "ollama",    target: "gemma2",      label: "runs" },
    { source: "ollama",    target: "qwen25",      label: "runs" },

    // ── Capability links ───────────────────────────────────────
    { source: "gpt4o",     target: "multimodal",  label: "is" },
    { source: "gemini15",  target: "multimodal",  label: "is" },
    { source: "o1",        target: "reasoning",   label: "specializes in" },
    { source: "gpt4o",     target: "reasoning",   label: "has" },
    { source: "claude35",  target: "reasoning",   label: "has" },
    { source: "claude4sonnet", target: "reasoning", label: "has" },
    { source: "claude4sonnet", target: "agents",  label: "powers" },
    { source: "deepseekv3", target: "reasoning",  label: "has" },
    { source: "finetuning", target: "llama3",     label: "applied to" },
    { source: "phi3",      target: "finetuning",  label: "designed for" },
    { source: "commandr",  target: "rag",         label: "optimized for" },
    { source: "qwen25",    target: "multimodal",  label: "supports" },

    // ── HuggingFace Hub hosts ──────────────────────────────────
    { source: "huggingfacehub", target: "llama3",    label: "hosts" },
    { source: "huggingfacehub", target: "mistral7b", label: "hosts" },
    { source: "huggingfacehub", target: "gemma2",    label: "hosts" },
    { source: "huggingfacehub", target: "flux1",     label: "hosts" },
    { source: "wandb",     target: "finetuning",    label: "tracks" },
    { source: "langsmith", target: "agents",        label: "monitors" },
    { source: "pinecone",  target: "vectordb",      label: "is type of" },
    { source: "chroma",    target: "vectordb",      label: "is type of" },

    // ── YouTube channels cover ─────────────────────────────────
    { source: "yt-two-minute", target: "transformers", label: "explains" },
    { source: "yt-two-minute", target: "research",     label: "covers" },
    { source: "yt-karpathy",   target: "transformers", label: "teaches" },
    { source: "yt-karpathy",   target: "finetuning",   label: "teaches" },
    { source: "yt-karpathy",   target: "openai",       label: "worked at" },
    { source: "yt-ai-explained", target: "reasoning",  label: "covers" },
    { source: "yt-ai-explained", target: "agents",     label: "covers" },
    { source: "yt-yannic",     target: "attention",    label: "reviews" },
    { source: "yt-yannic",     target: "scaling",      label: "reviews" },
    { source: "yt-fireship",   target: "ollama",       label: "demos" },
    { source: "yt-fireship",   target: "openrouter",   label: "demos" },
    { source: "yt-mattwolfe",  target: "agents",       label: "covers" },
    { source: "yt-mattwolfe",  target: "automation",   label: "covers" },
  ],
};
