import { GraphData } from "@/types";

export const INITIAL_GRAPH_DATA: GraphData = {
  nodes: [
    // Companies
    { id: "openai", label: "OpenAI", type: "company", description: "Creator of GPT and ChatGPT", size: 40, color: "#10a37f" },
    { id: "anthropic", label: "Anthropic", type: "company", description: "Creator of Claude", size: 36, color: "#d97706" },
    { id: "google", label: "Google DeepMind", type: "company", description: "Creator of Gemini and AlphaFold", size: 38, color: "#4285f4" },
    { id: "meta", label: "Meta AI", type: "company", description: "Creator of Llama open source models", size: 34, color: "#0866ff" },
    { id: "mistral", label: "Mistral AI", type: "company", description: "European AI research lab", size: 28, color: "#ff7000" },
    { id: "deepseek", label: "DeepSeek", type: "company", description: "Chinese AI research lab", size: 30, color: "#1e3a8a" },
    { id: "xai", label: "xAI", type: "company", description: "Elon Musk's AI company, creator of Grok", size: 26, color: "#000000" },
    { id: "microsoft", label: "Microsoft", type: "company", description: "OpenAI partner and Azure AI services", size: 32, color: "#00a4ef" },
    // Models
    { id: "gpt4o", label: "GPT-4o", type: "model", description: "OpenAI's flagship multimodal model", size: 32, color: "#10a37f" },
    { id: "gpt5", label: "GPT-5", type: "model", description: "OpenAI's next generation model", size: 28, color: "#10a37f" },
    { id: "claude35", label: "Claude 3.5 Sonnet", type: "model", description: "Anthropic's top model", size: 30, color: "#d97706" },
    { id: "claude4", label: "Claude 4", type: "model", description: "Anthropic's next generation", size: 26, color: "#d97706" },
    { id: "gemini15", label: "Gemini 1.5 Pro", type: "model", description: "Google's long-context model", size: 30, color: "#4285f4" },
    { id: "llama3", label: "Llama 3", type: "model", description: "Meta's open source flagship", size: 28, color: "#0866ff" },
    { id: "mistral7b", label: "Mistral 7B", type: "model", description: "Efficient open source model", size: 24, color: "#ff7000" },
    { id: "deepseekv3", label: "DeepSeek V3", type: "model", description: "State-of-art open source model", size: 28, color: "#1e3a8a" },
    { id: "grok2", label: "Grok-2", type: "model", description: "xAI's reasoning model", size: 24, color: "#000000" },
    { id: "phi4", label: "Phi-4", type: "model", description: "Microsoft's small but capable model", size: 22, color: "#00a4ef" },
    // Concepts
    { id: "rag", label: "RAG", type: "concept", description: "Retrieval Augmented Generation", size: 30, color: "#6366f1" },
    { id: "agents", label: "AI Agents", type: "concept", description: "Autonomous AI systems with tools", size: 32, color: "#8b5cf6" },
    { id: "mcp", label: "MCP", type: "concept", description: "Model Context Protocol by Anthropic", size: 26, color: "#d97706" },
    { id: "reasoning", label: "Reasoning", type: "concept", description: "Advanced multi-step problem solving", size: 28, color: "#6366f1" },
    { id: "multimodal", label: "Multimodal AI", type: "concept", description: "AI that understands text, images, audio, video", size: 26, color: "#06b6d4" },
    { id: "rlhf", label: "RLHF", type: "concept", description: "Reinforcement Learning from Human Feedback", size: 24, color: "#6366f1" },
    { id: "finetuning", label: "Fine-tuning", type: "concept", description: "Adapting models to specific tasks", size: 24, color: "#6366f1" },
    { id: "alignment", label: "AI Alignment", type: "concept", description: "Making AI systems safe and beneficial", size: 26, color: "#ef4444" },
    // Frameworks
    { id: "langchain", label: "LangChain", type: "framework", description: "Popular LLM application framework", size: 28, color: "#22c55e" },
    { id: "langgraph", label: "LangGraph", type: "framework", description: "Graph-based agent orchestration", size: 24, color: "#22c55e" },
    { id: "crewai", label: "CrewAI", type: "framework", description: "Multi-agent collaboration framework", size: 22, color: "#f59e0b" },
    { id: "autogen", label: "AutoGen", type: "framework", description: "Microsoft's multi-agent framework", size: 22, color: "#00a4ef" },
    { id: "openrouter", label: "OpenRouter", type: "tool", description: "Unified API for 100+ models", size: 26, color: "#6366f1" },
    { id: "ollama", label: "Ollama", type: "tool", description: "Run LLMs locally", size: 24, color: "#22c55e" },
    // YouTube Channels
    { id: "yt-two-minute", label: "Two Minute Papers 🎬", type: "tool", description: "AI research explained in 2 minutes — Károly Zsolnai-Fehér", size: 22, color: "#ff0000", url: "https://youtube.com/@TwoMinutePapers" },
    { id: "yt-ai-explained", label: "AI Explained 🎬", type: "tool", description: "Clear AI breakdowns for non-experts", size: 20, color: "#ff0000", url: "https://youtube.com/@aiexplained-official" },
    { id: "yt-karpathy", label: "Andrej Karpathy 🎬", type: "tool", description: "Deep learning from first principles by ex-OpenAI director", size: 24, color: "#ff0000", url: "https://youtube.com/@AndrejKarpathy" },
    { id: "yt-fireship", label: "Fireship 🎬", type: "tool", description: "Fast-paced AI & dev tutorials", size: 20, color: "#ff0000", url: "https://youtube.com/@Fireship" },
    { id: "yt-mattwolfe", label: "Matt Wolfe AI 🎬", type: "tool", description: "AI tool reviews, news, and tutorials", size: 20, color: "#ff0000", url: "https://youtube.com/@mreflow" },
    { id: "yt-yannic", label: "Yannic Kilcher 🎬", type: "tool", description: "AI paper deep dives and research reviews", size: 22, color: "#ff0000", url: "https://youtube.com/@YannicKilcher" },
    // Research
    { id: "attention", label: "Attention Mechanism", type: "research", description: "Foundation of transformer models", size: 24, color: "#8b5cf6" },
    { id: "transformers", label: "Transformers", type: "research", description: "'Attention is All You Need' architecture", size: 28, color: "#8b5cf6" },
    { id: "scaling", label: "Scaling Laws", type: "research", description: "How model performance scales with compute", size: 22, color: "#8b5cf6" },
    { id: "constitutional", label: "Constitutional AI", type: "research", description: "Anthropic's approach to AI safety", size: 22, color: "#d97706" },
    // Tools
    { id: "vectordb", label: "Vector Databases", type: "tool", description: "Semantic search infrastructure", size: 24, color: "#06b6d4" },
    { id: "embeddings", label: "Embeddings", type: "concept", description: "Semantic representations of text", size: 22, color: "#06b6d4" },
    { id: "automation", label: "AI Automation", type: "concept", description: "Automated AI workflows and pipelines", size: 24, color: "#f59e0b" },
  ],
  links: [
    // Company → Model relationships
    { source: "openai", target: "gpt4o", label: "created" },
    { source: "openai", target: "gpt5", label: "created" },
    { source: "anthropic", target: "claude35", label: "created" },
    { source: "anthropic", target: "claude4", label: "created" },
    { source: "google", target: "gemini15", label: "created" },
    { source: "meta", target: "llama3", label: "created" },
    { source: "mistral", target: "mistral7b", label: "created" },
    { source: "deepseek", target: "deepseekv3", label: "created" },
    { source: "xai", target: "grok2", label: "created" },
    { source: "microsoft", target: "phi4", label: "created" },
    { source: "microsoft", target: "autogen", label: "created" },
    // Concept relationships
    { source: "agents", target: "rag", label: "uses" },
    { source: "agents", target: "mcp", label: "uses" },
    { source: "agents", target: "langchain", label: "built with" },
    { source: "agents", target: "langgraph", label: "built with" },
    { source: "agents", target: "crewai", label: "built with" },
    { source: "agents", target: "autogen", label: "built with" },
    { source: "rag", target: "vectordb", label: "requires" },
    { source: "rag", target: "embeddings", label: "uses" },
    { source: "vectordb", target: "embeddings", label: "stores" },
    { source: "rlhf", target: "alignment", label: "enables" },
    { source: "anthropic", target: "constitutional", label: "developed" },
    { source: "constitutional", target: "alignment", label: "advances" },
    { source: "anthropic", target: "mcp", label: "created" },
    // Research → Model relationships
    { source: "transformers", target: "gpt4o", label: "powers" },
    { source: "transformers", target: "claude35", label: "powers" },
    { source: "transformers", target: "gemini15", label: "powers" },
    { source: "transformers", target: "llama3", label: "powers" },
    { source: "attention", target: "transformers", label: "foundation of" },
    { source: "scaling", target: "gpt5", label: "guides" },
    { source: "rlhf", target: "gpt4o", label: "trains" },
    { source: "rlhf", target: "claude35", label: "trains" },
    // Framework relationships
    { source: "langchain", target: "langgraph", label: "evolved into" },
    { source: "openrouter", target: "gpt4o", label: "provides access" },
    { source: "openrouter", target: "claude35", label: "provides access" },
    { source: "openrouter", target: "deepseekv3", label: "provides access" },
    { source: "ollama", target: "llama3", label: "runs" },
    { source: "ollama", target: "mistral7b", label: "runs" },
    { source: "ollama", target: "deepseekv3", label: "runs" },
    // Capability links
    { source: "gpt4o", target: "multimodal", label: "is" },
    { source: "gemini15", target: "multimodal", label: "is" },
    { source: "gpt4o", target: "reasoning", label: "has" },
    { source: "claude35", target: "reasoning", label: "has" },
    { source: "deepseekv3", target: "reasoning", label: "has" },
    { source: "finetuning", target: "llama3", label: "applied to" },
    { source: "agents", target: "automation", label: "enables" },
    { source: "mcp", target: "automation", label: "enables" },
    // YouTube → concepts
    { source: "yt-two-minute", target: "research", label: "covers" },
    { source: "yt-two-minute", target: "transformers", label: "explains" },
    { source: "yt-karpathy", target: "transformers", label: "teaches" },
    { source: "yt-karpathy", target: "finetuning", label: "teaches" },
    { source: "yt-karpathy", target: "openai", label: "worked at" },
    { source: "yt-ai-explained", target: "reasoning", label: "covers" },
    { source: "yt-ai-explained", target: "agents", label: "covers" },
    { source: "yt-yannic", target: "attention", label: "reviews" },
    { source: "yt-yannic", target: "scaling", label: "reviews" },
    { source: "yt-fireship", target: "ollama", label: "demos" },
    { source: "yt-fireship", target: "openrouter", label: "demos" },
    { source: "yt-mattwolfe", target: "agents", label: "covers" },
    { source: "yt-mattwolfe", target: "automation", label: "covers" },
  ],
};
