import { GraphData } from "@/types";

export const INITIAL_GRAPH_DATA: GraphData = {
  nodes: [
    // ════════════════════════════════════════════════════════════
    // COMPANIES
    // ════════════════════════════════════════════════════════════
    { id: "openai",      label: "OpenAI",          type: "company", description: "Creator of GPT-4, o1, ChatGPT and DALL-E", size: 44, color: "#10a37f", url: "https://openai.com" },
    { id: "anthropic",   label: "Anthropic",        type: "company", description: "Safety-focused AI lab, creator of Claude", size: 40, color: "#d97706", url: "https://anthropic.com" },
    { id: "google",      label: "Google DeepMind",  type: "company", description: "Creator of Gemini, AlphaFold, Gemma and Veo", size: 42, color: "#4285f4", url: "https://deepmind.google" },
    { id: "meta",        label: "Meta AI",          type: "company", description: "Creator of Llama open-source model family", size: 38, color: "#0866ff", url: "https://ai.meta.com" },
    { id: "mistral",     label: "Mistral AI",       type: "company", description: "European AI research lab — Mixtral and Codestral", size: 32, color: "#ff7000", url: "https://mistral.ai" },
    { id: "deepseek",    label: "DeepSeek",         type: "company", description: "Chinese AI lab — open-source frontier models", size: 34, color: "#1e3a8a", url: "https://deepseek.com" },
    { id: "xai",         label: "xAI",              type: "company", description: "Elon Musk's AI company — creator of Grok", size: 28, color: "#c0c0c0", url: "https://x.ai" },
    { id: "microsoft",   label: "Microsoft",        type: "company", description: "OpenAI partner — Azure AI, Phi, GitHub Copilot", size: 36, color: "#00a4ef", url: "https://microsoft.com/ai" },
    { id: "huggingface", label: "Hugging Face",     type: "company", description: "ML community hub — 800k+ models & datasets", size: 34, color: "#ff9900", url: "https://huggingface.co" },
    { id: "cohere",      label: "Cohere",           type: "company", description: "Enterprise NLP — Command R+ and Embed models", size: 24, color: "#d946ef", url: "https://cohere.com" },
    { id: "perplexity",  label: "Perplexity AI",    type: "company", description: "AI-powered answer engine and search", size: 24, color: "#06b6d4", url: "https://perplexity.ai" },
    { id: "groq",        label: "Groq",             type: "company", description: "Ultra-fast LLM inference with custom LPU hardware", size: 22, color: "#00d4ff", url: "https://groq.com" },
    { id: "stability",   label: "Stability AI",     type: "company", description: "Open-source image and audio generation AI", size: 22, color: "#7c3aed", url: "https://stability.ai" },
    { id: "elevenlabs",  label: "ElevenLabs",       type: "company", description: "AI voice generation, cloning and dubbing", size: 22, color: "#f59e0b", url: "https://elevenlabs.io" },
    { id: "runway",      label: "Runway",           type: "company", description: "AI-powered video generation and creative tools", size: 22, color: "#ec4899", url: "https://runwayml.com" },
    { id: "together",    label: "Together AI",      type: "company", description: "Cloud platform for open-source model inference", size: 22, color: "#10b981", url: "https://together.ai" },
    // New companies
    { id: "ai21",        label: "AI21 Labs",        type: "company", description: "Creator of Jamba MoE model and Wordtune", size: 20, color: "#8b5cf6", url: "https://ai21.com" },
    { id: "nvidia_ai",   label: "NVIDIA AI",        type: "company", description: "GPU leader — CUDA, TensorRT, Nemotron models", size: 32, color: "#76b900", url: "https://developer.nvidia.com/ai" },
    { id: "aws_ai",      label: "Amazon Web Services", type: "company", description: "AWS AI — Bedrock, SageMaker, Titan models", size: 30, color: "#ff9900", url: "https://aws.amazon.com/ai" },
    { id: "apple_ai",    label: "Apple AI",         type: "company", description: "Apple Intelligence — on-device LLMs and private cloud", size: 26, color: "#555555", url: "https://apple.com/apple-intelligence" },
    { id: "databricks",  label: "Databricks",       type: "company", description: "Data + AI platform — creator of DBRX and MLflow", size: 24, color: "#e8702a", url: "https://databricks.com" },
    { id: "scalai",      label: "Scale AI",         type: "company", description: "AI data labeling and evaluation platform", size: 20, color: "#6366f1", url: "https://scale.com" },
    { id: "cerebras",    label: "Cerebras Systems", type: "company", description: "Wafer-scale AI chip — fastest LLM inference hardware", size: 20, color: "#ef4444", url: "https://cerebras.ai" },
    { id: "aleph_alpha", label: "Aleph Alpha",      type: "company", description: "German AI company — Luminous models, GDPR-compliant", size: 18, color: "#6366f1", url: "https://aleph-alpha.com" },
    { id: "character_ai",label: "Character.AI",     type: "company", description: "AI character platform with 200M+ users", size: 20, color: "#ec4899", url: "https://character.ai" },
    { id: "pika_labs",   label: "Pika Labs",        type: "company", description: "AI video generation startup — Pika 2.0", size: 18, color: "#f59e0b", url: "https://pika.art" },
    { id: "suno_ai",     label: "Suno AI",          type: "company", description: "AI music generation — create full songs from text", size: 18, color: "#10b981", url: "https://suno.ai" },
    { id: "fireworks",   label: "Fireworks AI",     type: "company", description: "Fast open-source model serving platform", size: 18, color: "#f97316", url: "https://fireworks.ai" },
    { id: "replicate",   label: "Replicate",        type: "company", description: "Run ML models in the cloud via simple API", size: 20, color: "#6366f1", url: "https://replicate.com" },
    { id: "inflection",  label: "Inflection AI",    type: "company", description: "Creator of Pi — personal AI assistant", size: 18, color: "#8b5cf6", url: "https://inflection.ai" },
    { id: "twelve_labs", label: "Twelve Labs",      type: "company", description: "Video understanding and search AI platform", size: 16, color: "#06b6d4", url: "https://twelvelabs.io" },
    { id: "lightning_ai",label: "Lightning AI",     type: "company", description: "PyTorch Lightning and AI Studio platform", size: 18, color: "#7f3fbf", url: "https://lightning.ai" },

    // ════════════════════════════════════════════════════════════
    // MODELS
    // ════════════════════════════════════════════════════════════
    // Existing
    { id: "gpt4o",          label: "GPT-4o",           type: "model", description: "OpenAI's flagship multimodal model", size: 34, color: "#10a37f", url: "https://platform.openai.com/docs/models/gpt-4o" },
    { id: "o1",             label: "o1 / o3",           type: "model", description: "OpenAI's reasoning-focused chain-of-thought models", size: 32, color: "#10a37f", url: "https://platform.openai.com/docs/models/o1" },
    { id: "gpt5",           label: "GPT-5",             type: "model", description: "OpenAI's next-generation frontier model", size: 28, color: "#10a37f", url: "https://openai.com/index/gpt-5" },
    { id: "claude35",       label: "Claude 3.5 Sonnet", type: "model", description: "Anthropic's top coding and reasoning model", size: 32, color: "#d97706", url: "https://www.anthropic.com/claude/sonnet" },
    { id: "claude3opus",    label: "Claude 3 Opus",     type: "model", description: "Anthropic's most intelligent released model", size: 28, color: "#d97706", url: "https://www.anthropic.com/claude/opus" },
    { id: "claude4sonnet",  label: "Claude Sonnet 4",   type: "model", description: "Anthropic's latest flagship balanced model", size: 34, color: "#d97706", url: "https://www.anthropic.com/claude" },
    { id: "gemini15",       label: "Gemini 1.5 Pro",    type: "model", description: "Google's 1M-token long-context model", size: 32, color: "#4285f4", url: "https://deepmind.google/technologies/gemini/pro/" },
    { id: "gemma2",         label: "Gemma 2",           type: "model", description: "Google's open-source SLM family (2B–27B)", size: 22, color: "#4285f4", url: "https://ai.google.dev/gemma" },
    { id: "llama3",         label: "Llama 3",           type: "model", description: "Meta's open-source flagship (8B, 70B, 405B)", size: 30, color: "#0866ff", url: "https://llama.meta.com/" },
    { id: "mistral7b",      label: "Mistral 7B",        type: "model", description: "Efficient open-source model — sliding window attention", size: 24, color: "#ff7000", url: "https://mistral.ai/news/announcing-mistral-7b/" },
    { id: "mixtral8x22",    label: "Mixtral 8x22B",     type: "model", description: "Mistral's Mixture-of-Experts flagship", size: 26, color: "#ff7000", url: "https://mistral.ai/news/mixtral-8x22b/" },
    { id: "deepseekv3",     label: "DeepSeek V3",       type: "model", description: "State-of-art open-source MoE model", size: 30, color: "#1e3a8a", url: "https://github.com/deepseek-ai/DeepSeek-V3" },
    { id: "grok2",          label: "Grok-2",            type: "model", description: "xAI's reasoning and coding model", size: 24, color: "#c0c0c0", url: "https://x.ai/grok" },
    { id: "phi4",           label: "Phi-4",             type: "model", description: "Microsoft's small but capable SLM", size: 22, color: "#00a4ef", url: "https://azure.microsoft.com/en-us/blog/phi-4-microsofts-newest-small-language-model/" },
    { id: "phi3",           label: "Phi-3 Mini",        type: "model", description: "Microsoft's compact on-device model", size: 20, color: "#00a4ef", url: "https://azure.microsoft.com/en-us/blog/introducing-phi-3-redefining-whats-possible-with-slms/" },
    { id: "qwen25",         label: "Qwen 2.5",          type: "model", description: "Alibaba's multilingual open-source model", size: 24, color: "#ef4444", url: "https://qwenlm.github.io/blog/qwen2.5/" },
    { id: "commandr",       label: "Command R+",        type: "model", description: "Cohere's RAG-optimized enterprise model", size: 22, color: "#d946ef", url: "https://cohere.com/command" },
    { id: "flux1",          label: "FLUX.1",            type: "model", description: "Black Forest Labs' state-of-art image generation", size: 22, color: "#7c3aed", url: "https://blackforestlabs.ai/" },
    { id: "claude3haiku",   label: "Claude 3 Haiku",    type: "model", description: "Anthropic's fastest and most compact model", size: 20, color: "#d97706", url: "https://www.anthropic.com/claude/haiku" },
    { id: "gemma3",         label: "Gemma 3",           type: "model", description: "Google's latest open-source SLM with multimodal support", size: 22, color: "#4285f4", url: "https://ai.google.dev/gemma" },
    // New models
    { id: "gpt4turbo",      label: "GPT-4 Turbo",       type: "model", description: "OpenAI's fast GPT-4 with 128K context", size: 26, color: "#10a37f", url: "https://platform.openai.com/docs/models" },
    { id: "gpt35",          label: "GPT-3.5 Turbo",     type: "model", description: "OpenAI's fast, cost-effective chat model", size: 22, color: "#10a37f", url: "https://platform.openai.com/docs/models" },
    { id: "dalle3",         label: "DALL-E 3",          type: "model", description: "OpenAI's advanced text-to-image model", size: 24, color: "#10a37f", url: "https://openai.com/dall-e-3" },
    { id: "sora",           label: "Sora",              type: "model", description: "OpenAI's text-to-video generation model", size: 26, color: "#10a37f", url: "https://openai.com/sora" },
    { id: "whisper",        label: "Whisper",           type: "model", description: "OpenAI's open-source speech recognition model", size: 22, color: "#10a37f", url: "https://openai.com/research/whisper" },
    { id: "gemini20flash",  label: "Gemini 2.0 Flash",  type: "model", description: "Google's fastest multimodal model with real-time capabilities", size: 28, color: "#4285f4", url: "https://deepmind.google/technologies/gemini/flash/" },
    { id: "geminiultra",    label: "Gemini Ultra",      type: "model", description: "Google's most capable Gemini model", size: 24, color: "#4285f4", url: "https://deepmind.google/technologies/gemini/ultra/" },
    { id: "veo2",           label: "Veo 2",             type: "model", description: "Google DeepMind's state-of-art video generation model", size: 22, color: "#4285f4", url: "https://deepmind.google/technologies/veo/" },
    { id: "imagen3",        label: "Imagen 3",          type: "model", description: "Google's highest quality text-to-image model", size: 22, color: "#4285f4", url: "https://deepmind.google/technologies/imagen-3/" },
    { id: "llama2",         label: "Llama 2",           type: "model", description: "Meta's previous generation open-source model", size: 22, color: "#0866ff", url: "https://llama.meta.com/llama2/" },
    { id: "llama31",        label: "Llama 3.1",         type: "model", description: "Meta's long-context Llama with 128K context window", size: 26, color: "#0866ff", url: "https://ai.meta.com/blog/meta-llama-3-1/" },
    { id: "codellama",      label: "Code Llama",        type: "model", description: "Meta's code-specialized Llama variant", size: 22, color: "#0866ff", url: "https://ai.meta.com/blog/code-llama-large-language-model-coding/" },
    { id: "mistralnemo",    label: "Mistral Nemo",      type: "model", description: "Mistral's 12B multilingual model (Apache 2.0)", size: 20, color: "#ff7000", url: "https://mistral.ai/news/mistral-nemo/" },
    { id: "mistralsmall",   label: "Mistral Small 3",   type: "model", description: "Mistral's latest efficient small model", size: 20, color: "#ff7000", url: "https://mistral.ai" },
    { id: "codestral",      label: "Codestral",         type: "model", description: "Mistral's code generation specialist model", size: 22, color: "#ff7000", url: "https://mistral.ai/news/codestral/" },
    { id: "deepseekr1",     label: "DeepSeek R1",       type: "model", description: "DeepSeek's reasoning model — rivals o1 at open-source", size: 30, color: "#1e3a8a", url: "https://github.com/deepseek-ai/DeepSeek-R1" },
    { id: "deepseekcoder",  label: "DeepSeek Coder V2", type: "model", description: "DeepSeek's MoE code model — 236B parameters", size: 24, color: "#1e3a8a", url: "https://github.com/deepseek-ai/DeepSeek-Coder-V2" },
    { id: "falcon40b",      label: "Falcon 40B",        type: "model", description: "TII's open-source model, was #1 on leaderboard", size: 20, color: "#06b6d4", url: "https://huggingface.co/tiiuae/falcon-40b" },
    { id: "zephyr7b",       label: "Zephyr 7B",         type: "model", description: "HuggingFace's DPO-trained Mistral fine-tune", size: 18, color: "#ff9900", url: "https://huggingface.co/HuggingFaceH4/zephyr-7b-beta" },
    { id: "sdxl",           label: "Stable Diffusion XL", type: "model", description: "Stability AI's high-res image generation model", size: 22, color: "#7c3aed", url: "https://stability.ai/stable-image" },
    { id: "sd3",            label: "Stable Diffusion 3", type: "model", description: "Stability AI's latest diffusion architecture", size: 20, color: "#7c3aed", url: "https://stability.ai/stable-image" },
    { id: "midjourney",     label: "Midjourney v6",     type: "model", description: "Leading AI art generation model", size: 24, color: "#f472b6", url: "https://midjourney.com" },
    { id: "suno_model",     label: "Suno v4",           type: "model", description: "AI music generation — full songs with vocals", size: 20, color: "#10b981", url: "https://suno.ai" },
    { id: "pika_model",     label: "Pika 2.0",          type: "model", description: "AI video generation with cinematic quality", size: 18, color: "#f59e0b", url: "https://pika.art" },
    { id: "sonar",          label: "Sonar (Perplexity)", type: "model", description: "Perplexity's online RAG model with real-time search", size: 20, color: "#06b6d4", url: "https://docs.perplexity.ai" },
    { id: "phi2",           label: "Phi-2",             type: "model", description: "Microsoft's 2.7B model with textbook-quality training", size: 18, color: "#00a4ef", url: "https://huggingface.co/microsoft/phi-2" },
    { id: "qwen_coder",     label: "Qwen 2.5 Coder",    type: "model", description: "Alibaba's code-specialized Qwen model", size: 20, color: "#ef4444", url: "https://qwenlm.github.io/blog/qwen2.5-coder/" },
    { id: "jamba",          label: "Jamba 1.5",         type: "model", description: "AI21's hybrid SSM-Transformer model", size: 20, color: "#8b5cf6", url: "https://www.ai21.com/jamba" },
    { id: "nemotron",       label: "Nemotron-4",        type: "model", description: "NVIDIA's 340B parameter frontier model", size: 22, color: "#76b900", url: "https://research.nvidia.com/publication/2024-06_nemotron-4-340b" },
    { id: "dbrx",           label: "DBRX",              type: "model", description: "Databricks' open MoE model — 132B total parameters", size: 20, color: "#e8702a", url: "https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm" },
    { id: "nous_hermes",    label: "Nous Hermes 2",     type: "model", description: "Fine-tuned model from Nous Research — strong instruction following", size: 18, color: "#8b5cf6", url: "https://huggingface.co/NousResearch/Nous-Hermes-2-Mixtral-8x7B" },
    { id: "openchat",       label: "OpenChat 3.5",      type: "model", description: "Open-source model using C-RLFT training method", size: 16, color: "#22c55e", url: "https://huggingface.co/openchat/openchat-3.5" },
    { id: "tinyllama",      label: "TinyLlama 1.1B",    type: "model", description: "Tiny but capable 1.1B model for edge deployment", size: 14, color: "#0866ff", url: "https://github.com/jzhang38/TinyLlama" },
    { id: "smollm",         label: "SmolLM 2",          type: "model", description: "HuggingFace's on-device SLM family (135M–1.7B)", size: 14, color: "#ff9900", url: "https://huggingface.co/blog/smollm2" },
    { id: "internlm",       label: "InternLM 2.5",      type: "model", description: "Shanghai AI Lab's multilingual reasoning model", size: 18, color: "#06b6d4", url: "https://github.com/InternLM/InternLM" },
    { id: "minicpm",        label: "MiniCPM 3",         type: "model", description: "ModelBest's efficient on-device model family", size: 14, color: "#8b5cf6", url: "https://github.com/OpenBMB/MiniCPM" },
    { id: "aya",            label: "Aya Expanse",       type: "model", description: "Cohere's multilingual model across 23 languages", size: 18, color: "#d946ef", url: "https://cohere.com/research/aya" },
    { id: "llama32",        label: "Llama 3.2",         type: "model", description: "Meta's multimodal Llama — vision + 1B/3B edge models", size: 24, color: "#0866ff", url: "https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/" },

    // ════════════════════════════════════════════════════════════
    // RESEARCH PAPERS & TECHNIQUES
    // ════════════════════════════════════════════════════════════
    { id: "attention",       label: "Attention Mechanism", type: "research", description: "Scaled dot-product attention — the core of transformers", size: 26, color: "#8b5cf6" },
    { id: "transformers",    label: "Transformers",         type: "research", description: "'Attention Is All You Need' — foundation of modern LLMs", size: 30, color: "#8b5cf6" },
    { id: "scaling",         label: "Scaling Laws",         type: "research", description: "How capability scales predictably with compute and data", size: 24, color: "#8b5cf6" },
    { id: "constitutional",  label: "Constitutional AI",    type: "research", description: "Anthropic's principle-based AI safety training approach", size: 22, color: "#d97706" },
    { id: "cot",             label: "Chain of Thought",     type: "research", description: "Step-by-step reasoning prompting (Wei et al. 2022)", size: 26, color: "#8b5cf6" },
    { id: "tot",             label: "Tree of Thoughts",     type: "research", description: "Deliberate problem solving via reasoning branch exploration", size: 22, color: "#8b5cf6" },
    { id: "moe",             label: "Mixture of Experts",   type: "research", description: "Sparse gating routes tokens to specialist sub-networks", size: 26, color: "#8b5cf6" },
    { id: "lora",            label: "LoRA / PEFT",          type: "research", description: "Low-rank adaptation for parameter-efficient fine-tuning", size: 24, color: "#8b5cf6" },
    { id: "dpo",             label: "DPO",                  type: "research", description: "Direct Preference Optimization — simpler alternative to RLHF", size: 22, color: "#d97706" },
    { id: "flashattn",       label: "Flash Attention",      type: "research", description: "IO-aware exact attention enabling very long contexts", size: 24, color: "#8b5cf6" },
    // New research
    { id: "rope",            label: "RoPE",                 type: "research", description: "Rotary Position Embedding — enables context window extension", size: 20, color: "#8b5cf6" },
    { id: "gqa",             label: "Grouped Query Attention", type: "research", description: "GQA — reduces KV cache memory for fast inference", size: 20, color: "#8b5cf6" },
    { id: "knowledge_dist",  label: "Knowledge Distillation", type: "research", description: "Training small student models to mimic large teacher models", size: 22, color: "#8b5cf6" },
    { id: "quantization",    label: "Model Quantization",   type: "research", description: "Reducing model precision (INT8/INT4/GGUF) for efficiency", size: 24, color: "#8b5cf6" },
    { id: "spec_decode",     label: "Speculative Decoding", type: "research", description: "Use small draft model to predict tokens and verify in parallel", size: 20, color: "#8b5cf6" },
    { id: "kv_cache",        label: "KV Cache",             type: "research", description: "Caching key-value pairs to speed up autoregressive generation", size: 22, color: "#8b5cf6" },
    { id: "few_shot",        label: "Few-shot Learning",    type: "research", description: "Learning from only a few labeled examples in context", size: 22, color: "#8b5cf6" },
    { id: "zero_shot",       label: "Zero-shot Learning",   type: "research", description: "Performing tasks with no task-specific training examples", size: 20, color: "#8b5cf6" },
    { id: "instruction_tuning", label: "Instruction Tuning", type: "research", description: "Fine-tuning on instruction-following pairs for general capability", size: 24, color: "#8b5cf6" },
    { id: "reward_modeling", label: "Reward Modeling",      type: "research", description: "Training a model to score outputs for RLHF alignment", size: 20, color: "#d97706" },
    { id: "rlaif",           label: "RLAIF",                type: "research", description: "Reinforcement Learning from AI Feedback — scalable alignment", size: 20, color: "#d97706" },
    { id: "diffusion_models",label: "Diffusion Models",     type: "research", description: "Iterative denoising process for image/video generation", size: 26, color: "#8b5cf6" },
    { id: "gans",            label: "GANs",                 type: "research", description: "Generative Adversarial Networks — original image synthesis", size: 20, color: "#8b5cf6" },
    { id: "vae",             label: "Variational Autoencoders", type: "research", description: "VAEs — latent space learning for generative models", size: 18, color: "#8b5cf6" },
    { id: "benchmark",       label: "AI Benchmarks",        type: "research", description: "Standardized evaluation suites for model capability", size: 22, color: "#8b5cf6" },
    { id: "mmlu",            label: "MMLU",                 type: "research", description: "Massive Multitask Language Understanding — 57 subject benchmark", size: 20, color: "#8b5cf6" },
    { id: "humaneval",       label: "HumanEval",            type: "research", description: "OpenAI's code generation benchmark — 164 Python problems", size: 18, color: "#8b5cf6" },
    { id: "gsm8k",           label: "GSM8K",                type: "research", description: "Grade school math word problems — tests multi-step reasoning", size: 18, color: "#8b5cf6" },
    { id: "interpretability",label: "Mechanistic Interp.",  type: "research", description: "Understanding what computations LLMs perform internally", size: 20, color: "#ef4444" },
    { id: "emergent",        label: "Emergent Abilities",   type: "research", description: "Capabilities that appear suddenly at certain model scales", size: 22, color: "#8b5cf6" },
    { id: "red_teaming",     label: "Red Teaming",          type: "research", description: "Adversarial testing to find safety flaws in AI systems", size: 20, color: "#ef4444" },
    { id: "watermarking",    label: "AI Watermarking",      type: "research", description: "Embedding detectable signals in AI-generated content", size: 16, color: "#8b5cf6" },
    { id: "deepspeed",       label: "DeepSpeed",            type: "research", description: "Microsoft's deep learning optimization library for training", size: 22, color: "#00a4ef" },
    { id: "ssm",             label: "State Space Models",   type: "research", description: "Mamba/S4 — linear-time sequence modeling alternative to Transformers", size: 22, color: "#8b5cf6" },

    // ════════════════════════════════════════════════════════════
    // FRAMEWORKS & LIBRARIES
    // ════════════════════════════════════════════════════════════
    { id: "langchain",    label: "LangChain",     type: "framework", description: "Most popular LLM application framework", size: 30, color: "#22c55e" },
    { id: "langgraph",    label: "LangGraph",     type: "framework", description: "Graph-based multi-agent orchestration on LangChain", size: 26, color: "#22c55e" },
    { id: "crewai",       label: "CrewAI",        type: "framework", description: "Role-based multi-agent collaboration framework", size: 24, color: "#f59e0b" },
    { id: "autogen",      label: "AutoGen",       type: "framework", description: "Microsoft's conversational multi-agent framework", size: 24, color: "#00a4ef" },
    { id: "llamaindex",   label: "LlamaIndex",    type: "framework", description: "Data framework for connecting LLMs to private data", size: 26, color: "#f59e0b" },
    { id: "dspy",         label: "DSPy",          type: "framework", description: "Declarative self-improving LLM pipeline programming", size: 22, color: "#06b6d4" },
    { id: "haystack",     label: "Haystack",      type: "framework", description: "End-to-end NLP search and RAG framework", size: 22, color: "#ef4444" },
    { id: "openrouter",   label: "OpenRouter",    type: "framework", description: "Unified API gateway for 200+ AI models", size: 28, color: "#6366f1" },
    { id: "ollama",       label: "Ollama",        type: "framework", description: "Run LLMs locally with simple CLI and API", size: 26, color: "#22c55e" },
    // New frameworks
    { id: "pytorch",      label: "PyTorch",       type: "framework", description: "Meta's deep learning framework — standard for LLM research", size: 30, color: "#ee4c2c", url: "https://pytorch.org" },
    { id: "tensorflow",   label: "TensorFlow",    type: "framework", description: "Google's ML framework — widely used in production", size: 26, color: "#ff6f00", url: "https://tensorflow.org" },
    { id: "jax",          label: "JAX",           type: "framework", description: "Google's high-performance ML research framework", size: 22, color: "#4285f4", url: "https://jax.readthedocs.io" },
    { id: "transformers_lib", label: "HF Transformers", type: "framework", description: "HuggingFace's library for 500k+ pretrained models", size: 28, color: "#ff9900", url: "https://huggingface.co/docs/transformers" },
    { id: "vllm",         label: "vLLM",          type: "framework", description: "Fast LLM serving with PagedAttention — top inference engine", size: 26, color: "#7c3aed", url: "https://vllm.ai" },
    { id: "tgi",          label: "Text Gen. Inference", type: "framework", description: "HuggingFace's production LLM serving toolkit", size: 22, color: "#ff9900", url: "https://huggingface.co/docs/text-generation-inference" },
    { id: "litellm",      label: "LiteLLM",       type: "framework", description: "Universal proxy for 100+ LLM APIs — one interface", size: 22, color: "#06b6d4", url: "https://litellm.ai" },
    { id: "semantic_kernel", label: "Semantic Kernel", type: "framework", description: "Microsoft's SDK for AI plugins and agent orchestration", size: 22, color: "#00a4ef", url: "https://learn.microsoft.com/semantic-kernel" },
    { id: "memgpt",       label: "MemGPT / Letta", type: "framework", description: "OS-inspired agent memory management system", size: 20, color: "#8b5cf6", url: "https://letta.com" },
    { id: "agentops",     label: "AgentOps",      type: "framework", description: "AI agent observability and evaluation platform", size: 18, color: "#f59e0b", url: "https://agentops.ai" },
    { id: "langflow",     label: "LangFlow",      type: "framework", description: "Visual drag-and-drop LangChain pipeline builder", size: 20, color: "#22c55e", url: "https://langflow.org" },
    { id: "flowise",      label: "Flowise",       type: "framework", description: "Low-code LLM app builder with visual interface", size: 20, color: "#f59e0b", url: "https://flowiseai.com" },
    { id: "metagpt",      label: "MetaGPT",       type: "framework", description: "Multi-agent software development framework", size: 20, color: "#06b6d4", url: "https://github.com/geekan/MetaGPT" },
    { id: "autogpt",      label: "Auto-GPT",      type: "framework", description: "One of the first autonomous GPT-4 agent systems", size: 22, color: "#10a37f", url: "https://github.com/Significant-Gravitas/AutoGPT" },
    { id: "instructor",   label: "Instructor",    type: "framework", description: "Structured JSON output from LLMs using Pydantic", size: 20, color: "#06b6d4", url: "https://python.useinstructor.com" },
    { id: "guidance_fw",  label: "Guidance",      type: "framework", description: "Microsoft's constrained generation for LLMs", size: 18, color: "#00a4ef", url: "https://github.com/guidance-ai/guidance" },
    { id: "pydantic_ai",  label: "PydanticAI",    type: "framework", description: "Type-safe agent framework by Pydantic team", size: 20, color: "#e92063", url: "https://ai.pydantic.dev" },
    { id: "smolagents",   label: "Smolagents",    type: "framework", description: "HuggingFace's minimal code-first agent framework", size: 20, color: "#ff9900", url: "https://huggingface.co/docs/smolagents" },
    { id: "mlflow",       label: "MLflow",        type: "framework", description: "Open-source ML lifecycle — tracking, models, deployments", size: 22, color: "#0194e2", url: "https://mlflow.org" },
    { id: "ray_fw",       label: "Ray",           type: "framework", description: "Distributed computing framework for AI workloads", size: 22, color: "#028cf0", url: "https://ray.io" },
    { id: "bentoml",      label: "BentoML",       type: "framework", description: "ML model serving and deployment framework", size: 18, color: "#f472b6", url: "https://bentoml.com" },
    { id: "streamlit",    label: "Streamlit",     type: "framework", description: "Fast Python web apps for ML demos and prototypes", size: 22, color: "#ff4b4b", url: "https://streamlit.io" },
    { id: "gradio",       label: "Gradio",        type: "framework", description: "HuggingFace's ML demo and interface framework", size: 22, color: "#ff9900", url: "https://gradio.app" },

    // ════════════════════════════════════════════════════════════
    // TOOLS
    // ════════════════════════════════════════════════════════════
    { id: "vectordb",        label: "Vector Databases",   type: "tool", description: "Semantic similarity search infrastructure for AI", size: 26, color: "#06b6d4" },
    { id: "pinecone",        label: "Pinecone",            type: "tool", description: "Managed vector database — serverless and scalable", size: 22, color: "#0ea5e9", url: "https://pinecone.io" },
    { id: "chroma",          label: "ChromaDB",            type: "tool", description: "Open-source in-memory + persistent embedding database", size: 20, color: "#7c3aed", url: "https://trychroma.com" },
    { id: "wandb",           label: "Weights & Biases",    type: "tool", description: "ML experiment tracking, evaluation and deployment", size: 22, color: "#ffbe00", url: "https://wandb.ai" },
    { id: "langsmith",       label: "LangSmith",           type: "tool", description: "LLM app observability, tracing and evaluation", size: 22, color: "#22c55e", url: "https://smith.langchain.com" },
    { id: "huggingfacehub",  label: "HF Hub",              type: "tool", description: "Repository hosting 800k+ models, datasets and Spaces", size: 28, color: "#ff9900", url: "https://huggingface.co" },
    // New tools
    { id: "qdrant",          label: "Qdrant",              type: "tool", description: "Rust-based high-performance vector similarity search", size: 20, color: "#ef4444", url: "https://qdrant.tech" },
    { id: "milvus",          label: "Milvus",              type: "tool", description: "Open-source vector database for billion-scale similarity", size: 20, color: "#06b6d4", url: "https://milvus.io" },
    { id: "weaviate",        label: "Weaviate",            type: "tool", description: "AI-native vector database with hybrid search", size: 20, color: "#8b5cf6", url: "https://weaviate.io" },
    { id: "pgvector",        label: "pgvector",            type: "tool", description: "PostgreSQL extension for vector similarity search", size: 18, color: "#336791", url: "https://github.com/pgvector/pgvector" },
    { id: "github_copilot",  label: "GitHub Copilot",      type: "tool", description: "AI pair programmer — autocomplete for any codebase", size: 26, color: "#6e5494", url: "https://github.com/features/copilot" },
    { id: "cursor",          label: "Cursor IDE",          type: "tool", description: "AI-first code editor built on VS Code", size: 24, color: "#6366f1", url: "https://cursor.com" },
    { id: "codeium",         label: "Codeium",             type: "tool", description: "Free AI code completion for 70+ languages", size: 18, color: "#09b6a2", url: "https://codeium.com" },
    { id: "replit_ai",       label: "Replit AI",           type: "tool", description: "AI in-browser coding environment and agent", size: 18, color: "#f26207", url: "https://replit.com/ai" },
    { id: "v0",              label: "v0.dev",              type: "tool", description: "Vercel's AI UI code generator from natural language", size: 20, color: "#000000", url: "https://v0.dev" },
    { id: "bolt",            label: "Bolt.new",            type: "tool", description: "AI full-stack app builder from StackBlitz", size: 20, color: "#3b82f6", url: "https://bolt.new" },
    { id: "aider",           label: "Aider",               type: "tool", description: "AI pair programming in terminal — edits entire codebases", size: 20, color: "#22c55e", url: "https://aider.chat" },
    { id: "opendevin",       label: "OpenHands",           type: "tool", description: "Open-source AI software engineering agent (was OpenDevin)", size: 22, color: "#6366f1", url: "https://github.com/All-Hands-AI/OpenHands" },
    { id: "tensorrt",        label: "TensorRT-LLM",        type: "tool", description: "NVIDIA's library for optimized LLM inference on GPUs", size: 22, color: "#76b900", url: "https://github.com/NVIDIA/TensorRT-LLM" },
    { id: "bedrock",         label: "Amazon Bedrock",      type: "tool", description: "AWS managed service for foundation models via API", size: 24, color: "#ff9900", url: "https://aws.amazon.com/bedrock" },
    { id: "vertex_ai",       label: "Vertex AI",           type: "tool", description: "Google Cloud's ML platform and model garden", size: 24, color: "#4285f4", url: "https://cloud.google.com/vertex-ai" },
    { id: "azure_openai",    label: "Azure OpenAI",        type: "tool", description: "Microsoft's enterprise-grade OpenAI model hosting", size: 22, color: "#00a4ef", url: "https://azure.microsoft.com/products/ai-services/openai-service" },
    { id: "sagemaker",       label: "Amazon SageMaker",    type: "tool", description: "AWS ML platform for training and deployment", size: 20, color: "#ff9900", url: "https://aws.amazon.com/sagemaker" },
    { id: "modal",           label: "Modal",               type: "tool", description: "Serverless GPU cloud for AI workloads", size: 18, color: "#6366f1", url: "https://modal.com" },
    { id: "e2b",             label: "E2B",                 type: "tool", description: "Secure sandboxed code execution for AI agents", size: 18, color: "#10b981", url: "https://e2b.dev" },
    { id: "sentence_transformers", label: "Sentence Transformers", type: "tool", description: "Python library for state-of-art text/image embeddings", size: 20, color: "#ff9900", url: "https://sbert.net" },
    { id: "helicone",        label: "Helicone",            type: "tool", description: "Open-source LLM observability and cost tracking", size: 16, color: "#f59e0b", url: "https://helicone.ai" },
    { id: "promptlayer",     label: "PromptLayer",         type: "tool", description: "Prompt management, versioning and analytics platform", size: 16, color: "#8b5cf6", url: "https://promptlayer.com" },
    // YouTube channels
    { id: "yt-two-minute",   label: "Two Minute Papers 🎬", type: "tool", description: "AI research explained clearly — Károly Zsolnai-Fehér", size: 22, color: "#ff0000", url: "https://youtube.com/@TwoMinutePapers" },
    { id: "yt-ai-explained", label: "AI Explained 🎬",      type: "tool", description: "Clear AI news and concept breakdowns", size: 20, color: "#ff0000", url: "https://youtube.com/@aiexplained-official" },
    { id: "yt-karpathy",     label: "Andrej Karpathy 🎬",   type: "tool", description: "Deep learning from first principles — ex-OpenAI director", size: 26, color: "#ff0000", url: "https://youtube.com/@AndrejKarpathy" },
    { id: "yt-fireship",     label: "Fireship 🎬",          type: "tool", description: "Fast-paced AI and dev tutorials", size: 20, color: "#ff0000", url: "https://youtube.com/@Fireship" },
    { id: "yt-mattwolfe",    label: "Matt Wolfe AI 🎬",     type: "tool", description: "AI tool reviews, news, and weekly roundups", size: 20, color: "#ff0000", url: "https://youtube.com/@mreflow" },
    { id: "yt-yannic",       label: "Yannic Kilcher 🎬",    type: "tool", description: "Deep ML paper reviews and research commentary", size: 22, color: "#ff0000", url: "https://youtube.com/@YannicKilcher" },

    // ════════════════════════════════════════════════════════════
    // CONCEPTS
    // ════════════════════════════════════════════════════════════
    { id: "rag",             label: "RAG",                type: "concept", description: "Retrieval Augmented Generation — ground LLMs in external knowledge", size: 32, color: "#6366f1" },
    { id: "agents",          label: "AI Agents",          type: "concept", description: "Autonomous AI systems that plan, use tools and complete tasks", size: 34, color: "#8b5cf6" },
    { id: "mcp",             label: "MCP",                type: "concept", description: "Model Context Protocol — standard tool use interface by Anthropic", size: 28, color: "#d97706" },
    { id: "reasoning",       label: "Reasoning",          type: "concept", description: "Advanced multi-step problem solving and logical inference", size: 30, color: "#6366f1" },
    { id: "multimodal",      label: "Multimodal AI",      type: "concept", description: "AI that understands and generates text, images, audio and video", size: 28, color: "#06b6d4" },
    { id: "rlhf",            label: "RLHF",               type: "concept", description: "Reinforcement Learning from Human Feedback — alignment technique", size: 26, color: "#6366f1" },
    { id: "finetuning",      label: "Fine-tuning",        type: "concept", description: "Adapting pre-trained models to specific tasks and domains", size: 26, color: "#6366f1" },
    { id: "alignment",       label: "AI Alignment",       type: "concept", description: "Making AI systems safe, helpful and aligned with human values", size: 28, color: "#ef4444" },
    { id: "embeddings",      label: "Embeddings",         type: "concept", description: "Dense vector representations capturing semantic meaning", size: 24, color: "#06b6d4" },
    { id: "automation",      label: "AI Automation",      type: "concept", description: "Automated AI workflows, pipelines and business processes", size: 26, color: "#f59e0b" },
    { id: "tooluse",         label: "Tool Use",           type: "concept", description: "AI models calling external APIs, code interpreters and databases", size: 28, color: "#06b6d4" },
    { id: "functioncalling", label: "Function Calling",   type: "concept", description: "Structured JSON output for deterministic API interactions", size: 22, color: "#06b6d4" },
    { id: "longtermemory",   label: "Long-term Memory",   type: "concept", description: "Persistent memory systems for agents across sessions", size: 22, color: "#8b5cf6" },
    { id: "synthdata",       label: "Synthetic Data",     type: "concept", description: "AI-generated training data for model improvement", size: 20, color: "#f59e0b" },
    { id: "prompteng",       label: "Prompt Engineering", type: "concept", description: "Crafting effective prompts for optimal LLM behavior", size: 28, color: "#06b6d4" },
    // New concepts
    { id: "hallucination",   label: "Hallucination",      type: "concept", description: "LLMs generating confident but factually wrong information", size: 26, color: "#ef4444" },
    { id: "grounding",       label: "Grounding & Factuality", type: "concept", description: "Anchoring AI responses in verifiable facts and sources", size: 24, color: "#10b981" },
    { id: "xai_concept",     label: "Explainability (XAI)", type: "concept", description: "Making AI decisions interpretable and transparent to humans", size: 22, color: "#f59e0b" },
    { id: "ai_ethics",       label: "AI Ethics",          type: "concept", description: "Ethical principles governing responsible AI development and use", size: 24, color: "#ef4444" },
    { id: "bias_fairness",   label: "Bias & Fairness",    type: "concept", description: "Identifying and mitigating unfair biases in AI models", size: 22, color: "#ef4444" },
    { id: "context_window",  label: "Context Window",     type: "concept", description: "Maximum tokens an LLM can process in a single request", size: 24, color: "#06b6d4" },
    { id: "tokenization",    label: "Tokenization",       type: "concept", description: "Converting text to token IDs using BPE or SentencePiece", size: 20, color: "#6366f1" },
    { id: "temperature",     label: "Sampling & Temperature", type: "concept", description: "Controlling LLM creativity via temperature, top-p and top-k", size: 20, color: "#6366f1" },
    { id: "image_gen",       label: "Image Generation",   type: "concept", description: "Creating photorealistic images from text prompts with AI", size: 26, color: "#ec4899" },
    { id: "video_gen",       label: "Video Generation",   type: "concept", description: "Creating video content from text or image inputs with AI", size: 24, color: "#ec4899" },
    { id: "music_gen",       label: "Music Generation",   type: "concept", description: "AI creating original music, songs and audio from prompts", size: 22, color: "#10b981" },
    { id: "voice_cloning",   label: "Voice Cloning",      type: "concept", description: "Replicating specific voices with AI from audio samples", size: 22, color: "#f59e0b" },
    { id: "stt",             label: "Speech-to-Text",     type: "concept", description: "Transcribing spoken audio to text with AI", size: 22, color: "#06b6d4" },
    { id: "tts",             label: "Text-to-Speech",     type: "concept", description: "Converting text to natural sounding speech with AI", size: 22, color: "#06b6d4" },
    { id: "code_gen",        label: "Code Generation",    type: "concept", description: "AI writing, completing and refactoring source code", size: 26, color: "#22c55e" },
    { id: "computer_use",    label: "Computer Use",       type: "concept", description: "AI controlling computers — browser, desktop and terminal", size: 26, color: "#8b5cf6" },
    { id: "math_reasoning",  label: "Mathematical Reasoning", type: "concept", description: "AI solving complex math problems with step-by-step derivations", size: 22, color: "#6366f1" },
    { id: "medical_ai",      label: "Medical AI",         type: "concept", description: "AI applied to diagnostics, drug discovery and clinical data", size: 22, color: "#ef4444" },
    { id: "multiagent",      label: "Multi-Agent Systems", type: "concept", description: "Networks of AI agents collaborating to solve complex tasks", size: 28, color: "#8b5cf6" },
    { id: "structured_output", label: "Structured Output", type: "concept", description: "Enforcing JSON schema or typed outputs from LLMs", size: 20, color: "#06b6d4" },
    { id: "semantic_search", label: "Semantic Search",    type: "concept", description: "Retrieving documents by meaning rather than keyword matching", size: 24, color: "#06b6d4" },
    { id: "hybrid_search",   label: "Hybrid Search",      type: "concept", description: "Combining dense vector and sparse BM25 retrieval", size: 20, color: "#06b6d4" },
    { id: "reranking",       label: "Re-ranking",         type: "concept", description: "Cross-encoder rescoring of retrieved documents for accuracy", size: 18, color: "#6366f1" },
    { id: "graph_rag",       label: "Graph RAG",          type: "concept", description: "RAG using knowledge graphs for richer relationship retrieval", size: 22, color: "#6366f1" },
    { id: "agentic_rag",     label: "Agentic RAG",        type: "concept", description: "Agents that autonomously query and synthesize from multiple sources", size: 22, color: "#8b5cf6" },
    { id: "self_rag",        label: "Self-RAG",           type: "concept", description: "Model learns when and what to retrieve during generation", size: 18, color: "#6366f1" },
    { id: "federated_learning", label: "Federated Learning", type: "concept", description: "Training AI on distributed data without centralizing it", size: 20, color: "#10b981" },
    { id: "ai_safety_concept", label: "AI Safety",        type: "concept", description: "Research ensuring AI systems behave safely as they become more capable", size: 24, color: "#ef4444" },
    { id: "eval",            label: "LLM Evaluation",     type: "concept", description: "Measuring LLM quality — accuracy, safety, usefulness and cost", size: 22, color: "#f59e0b" },
    { id: "ocr",             label: "Document AI / OCR",  type: "concept", description: "Extracting structured data from documents, PDFs and images", size: 20, color: "#06b6d4" },
    { id: "knowledge_base",  label: "Knowledge Base",     type: "concept", description: "Structured collection of facts for AI retrieval and Q&A", size: 22, color: "#6366f1" },
  ],

  links: [
    // ════════════════════════════════════════════════════════════
    // COMPANY → MODEL (created)
    // ════════════════════════════════════════════════════════════
    { source: "openai",    target: "gpt4o",          label: "created" },
    { source: "openai",    target: "o1",             label: "created" },
    { source: "openai",    target: "gpt5",           label: "created" },
    { source: "openai",    target: "gpt4turbo",      label: "created" },
    { source: "openai",    target: "gpt35",          label: "created" },
    { source: "openai",    target: "dalle3",         label: "created" },
    { source: "openai",    target: "sora",           label: "created" },
    { source: "openai",    target: "whisper",        label: "created" },
    { source: "anthropic", target: "claude35",       label: "created" },
    { source: "anthropic", target: "claude3opus",    label: "created" },
    { source: "anthropic", target: "claude4sonnet",  label: "created" },
    { source: "anthropic", target: "claude3haiku",   label: "created" },
    { source: "google",    target: "gemini15",       label: "created" },
    { source: "google",    target: "gemini20flash",  label: "created" },
    { source: "google",    target: "geminiultra",    label: "created" },
    { source: "google",    target: "veo2",           label: "created" },
    { source: "google",    target: "imagen3",        label: "created" },
    { source: "google",    target: "gemma2",         label: "created" },
    { source: "google",    target: "gemma3",         label: "created" },
    { source: "meta",      target: "llama3",         label: "created" },
    { source: "meta",      target: "llama2",         label: "created" },
    { source: "meta",      target: "llama31",        label: "created" },
    { source: "meta",      target: "llama32",        label: "created" },
    { source: "meta",      target: "codellama",      label: "created" },
    { source: "mistral",   target: "mistral7b",      label: "created" },
    { source: "mistral",   target: "mixtral8x22",    label: "created" },
    { source: "mistral",   target: "mistralnemo",    label: "created" },
    { source: "mistral",   target: "mistralsmall",   label: "created" },
    { source: "mistral",   target: "codestral",      label: "created" },
    { source: "deepseek",  target: "deepseekv3",     label: "created" },
    { source: "deepseek",  target: "deepseekr1",     label: "created" },
    { source: "deepseek",  target: "deepseekcoder",  label: "created" },
    { source: "xai",       target: "grok2",          label: "created" },
    { source: "microsoft", target: "phi4",           label: "created" },
    { source: "microsoft", target: "phi3",           label: "created" },
    { source: "microsoft", target: "phi2",           label: "created" },
    { source: "microsoft", target: "autogen",        label: "created" },
    { source: "cohere",    target: "commandr",       label: "created" },
    { source: "cohere",    target: "aya",            label: "created" },
    { source: "ai21",      target: "jamba",          label: "created" },
    { source: "nvidia_ai", target: "nemotron",       label: "created" },
    { source: "nvidia_ai", target: "tensorrt",       label: "created" },
    { source: "databricks",target: "dbrx",           label: "created" },
    { source: "databricks",target: "mlflow",         label: "created" },
    { source: "stability", target: "sdxl",           label: "created" },
    { source: "stability", target: "sd3",            label: "created" },
    { source: "stability", target: "flux1",          label: "created" },
    { source: "suno_ai",   target: "suno_model",     label: "created" },
    { source: "pika_labs", target: "pika_model",     label: "created" },
    { source: "perplexity",target: "sonar",          label: "created" },

    // ════════════════════════════════════════════════════════════
    // COMPANY → TOOL / FRAMEWORK
    // ════════════════════════════════════════════════════════════
    { source: "huggingface",    target: "huggingfacehub",     label: "operates" },
    { source: "huggingface",    target: "transformers_lib",   label: "created" },
    { source: "huggingface",    target: "tgi",                label: "created" },
    { source: "huggingface",    target: "gradio",             label: "created" },
    { source: "huggingface",    target: "smolagents",         label: "created" },
    { source: "microsoft",      target: "github_copilot",     label: "created" },
    { source: "microsoft",      target: "semantic_kernel",    label: "created" },
    { source: "microsoft",      target: "azure_openai",       label: "operates" },
    { source: "microsoft",      target: "deepspeed",          label: "created" },
    { source: "google",         target: "vertex_ai",          label: "operates" },
    { source: "google",         target: "tensorflow",         label: "created" },
    { source: "google",         target: "jax",                label: "created" },
    { source: "meta",           target: "pytorch",            label: "created" },
    { source: "aws_ai",         target: "bedrock",            label: "operates" },
    { source: "aws_ai",         target: "sagemaker",          label: "operates" },
    { source: "groq",           target: "llama3",             label: "accelerates" },
    { source: "groq",           target: "mixtral8x22",        label: "accelerates" },
    { source: "together",       target: "llama3",             label: "hosts" },
    { source: "together",       target: "mixtral8x22",        label: "hosts" },
    { source: "fireworks",      target: "llama3",             label: "hosts" },
    { source: "replicate",      target: "sdxl",               label: "hosts" },
    { source: "replicate",      target: "flux1",              label: "hosts" },
    { source: "perplexity",     target: "rag",                label: "uses" },
    { source: "perplexity",     target: "agents",             label: "uses" },
    { source: "lightning_ai",   target: "pytorch",            label: "extends" },
    { source: "character_ai",   target: "agents",             label: "uses" },
    { source: "cerebras",       target: "llama3",             label: "accelerates" },
    { source: "cerebras",       target: "deepseekr1",         label: "accelerates" },
    { source: "scalai",         target: "synthdata",          label: "produces" },
    { source: "scalai",         target: "finetuning",         label: "enables" },
    { source: "twelve_labs",    target: "multimodal",         label: "advances" },
    { source: "inflection",     target: "agents",             label: "uses" },

    // ════════════════════════════════════════════════════════════
    // RESEARCH → MODELS (powers / enables)
    // ════════════════════════════════════════════════════════════
    { source: "transformers",    target: "gpt4o",         label: "powers" },
    { source: "transformers",    target: "claude35",       label: "powers" },
    { source: "transformers",    target: "gemini15",       label: "powers" },
    { source: "transformers",    target: "llama3",         label: "powers" },
    { source: "transformers",    target: "deepseekv3",     label: "powers" },
    { source: "attention",       target: "transformers",   label: "foundation of" },
    { source: "moe",             target: "mixtral8x22",    label: "powers" },
    { source: "moe",             target: "deepseekv3",     label: "powers" },
    { source: "moe",             target: "deepseekr1",     label: "powers" },
    { source: "moe",             target: "jamba",          label: "powers" },
    { source: "moe",             target: "dbrx",           label: "powers" },
    { source: "moe",             target: "gpt4turbo",      label: "likely powers" },
    { source: "flashattn",       target: "transformers",   label: "optimizes" },
    { source: "flashattn",       target: "gemini15",       label: "enables" },
    { source: "flashattn",       target: "llama31",        label: "enables" },
    { source: "rope",            target: "llama3",         label: "used by" },
    { source: "rope",            target: "llama31",        label: "used by" },
    { source: "rope",            target: "mistral7b",      label: "used by" },
    { source: "rope",            target: "deepseekr1",     label: "used by" },
    { source: "gqa",             target: "llama3",         label: "used by" },
    { source: "gqa",             target: "gemini20flash",  label: "used by" },
    { source: "ssm",             target: "jamba",          label: "powers" },
    { source: "scaling",         target: "gpt5",           label: "guides" },
    { source: "scaling",         target: "emergent",       label: "predicts" },
    { source: "diffusion_models",target: "sdxl",           label: "powers" },
    { source: "diffusion_models",target: "sd3",            label: "powers" },
    { source: "diffusion_models",target: "dalle3",         label: "powers" },
    { source: "diffusion_models",target: "flux1",          label: "powers" },
    { source: "diffusion_models",target: "imagen3",        label: "powers" },
    { source: "diffusion_models",target: "sora",           label: "powers" },
    { source: "diffusion_models",target: "veo2",           label: "powers" },
    { source: "lora",            target: "finetuning",     label: "method for" },
    { source: "lora",            target: "sdxl",           label: "adapts" },
    { source: "lora",            target: "llama3",         label: "adapts" },
    { source: "quantization",    target: "phi3",           label: "enables" },
    { source: "quantization",    target: "tinyllama",      label: "enables" },
    { source: "quantization",    target: "smollm",         label: "enables" },
    { source: "quantization",    target: "minicpm",        label: "enables" },
    { source: "knowledge_dist",  label: "creates", target: "phi3" },
    { source: "knowledge_dist",  label: "creates", target: "phi2" },
    { source: "knowledge_dist",  label: "creates", target: "smollm" },
    { source: "spec_decode",     target: "vllm",           label: "used in" },
    { source: "spec_decode",     target: "kv_cache",       label: "uses" },
    { source: "kv_cache",        target: "context_window", label: "enables" },
    { source: "instruction_tuning", target: "llama3",      label: "trains" },
    { source: "instruction_tuning", target: "mistral7b",   label: "trains" },
    { source: "instruction_tuning", target: "nous_hermes", label: "trains" },
    { source: "instruction_tuning", target: "openchat",    label: "trains" },
    { source: "cot",             target: "reasoning",      label: "improves" },
    { source: "tot",             target: "reasoning",      label: "improves" },
    { source: "tot",             target: "cot",            label: "extends" },
    { source: "cot",             target: "o1",             label: "inspires" },
    { source: "cot",             target: "deepseekr1",     label: "inspires" },
    { source: "cot",             target: "math_reasoning", label: "enables" },
    { source: "reward_modeling", target: "rlhf",           label: "part of" },
    { source: "rlaif",           target: "claude35",       label: "trains" },
    { source: "rlaif",           target: "constitutional", label: "extends" },
    { source: "dpo",             target: "zephyr7b",       label: "trains" },
    { source: "dpo",             target: "rlhf",           label: "alternative to" },
    { source: "dpo",             target: "alignment",      label: "advances" },
    { source: "constitutional",  target: "alignment",      label: "advances" },
    { source: "deepspeed",       target: "pytorch",        label: "extends" },
    { source: "deepspeed",       target: "llama3",         label: "trains" },
    { source: "deepspeed",       target: "deepseekv3",     label: "trains" },
    { source: "few_shot",        target: "prompteng",      label: "technique of" },
    { source: "zero_shot",       target: "prompteng",      label: "technique of" },
    { source: "benchmark",       target: "mmlu",           label: "includes" },
    { source: "benchmark",       target: "humaneval",      label: "includes" },
    { source: "benchmark",       target: "gsm8k",          label: "includes" },
    { source: "mmlu",            target: "eval",           label: "informs" },
    { source: "humaneval",       target: "code_gen",       label: "measures" },
    { source: "gsm8k",           target: "math_reasoning", label: "measures" },
    { source: "emergent",        target: "gpt4o",          label: "observed in" },
    { source: "emergent",        target: "claude35",       label: "observed in" },
    { source: "interpretability",target: "alignment",      label: "informs" },
    { source: "red_teaming",     target: "alignment",      label: "improves" },
    { source: "red_teaming",     target: "ai_safety_concept", label: "part of" },
    { source: "watermarking",    target: "ai_ethics",      label: "supports" },

    // ════════════════════════════════════════════════════════════
    // FRAMEWORKS → MODELS / CONCEPTS
    // ════════════════════════════════════════════════════════════
    { source: "langchain",       target: "langgraph",      label: "evolved into" },
    { source: "langchain",       target: "langsmith",      label: "monitored by" },
    { source: "langchain",       target: "chroma",         label: "integrates" },
    { source: "langchain",       target: "pinecone",       label: "integrates" },
    { source: "langchain",       target: "rag",            label: "enables" },
    { source: "llamaindex",      target: "rag",            label: "enables" },
    { source: "llamaindex",      target: "vectordb",       label: "integrates" },
    { source: "llamaindex",      target: "graph_rag",      label: "enables" },
    { source: "dspy",            target: "prompteng",      label: "automates" },
    { source: "dspy",            target: "finetuning",     label: "automates" },
    { source: "haystack",        target: "rag",            label: "enables" },
    { source: "haystack",        target: "hybrid_search",  label: "enables" },
    { source: "crewai",          target: "agents",         label: "built with" },
    { source: "autogen",         target: "agents",         label: "built with" },
    { source: "langgraph",       target: "agents",         label: "built with" },
    { source: "langgraph",       target: "multiagent",     label: "enables" },
    { source: "metagpt",         target: "multiagent",     label: "uses" },
    { source: "metagpt",         target: "code_gen",       label: "specializes in" },
    { source: "autogpt",         target: "agents",         label: "built with" },
    { source: "memgpt",          target: "longtermemory",  label: "implements" },
    { source: "memgpt",          target: "agents",         label: "enhances" },
    { source: "openrouter",      target: "gpt4o",          label: "provides access" },
    { source: "openrouter",      target: "claude35",       label: "provides access" },
    { source: "openrouter",      target: "deepseekv3",     label: "provides access" },
    { source: "openrouter",      target: "deepseekr1",     label: "provides access" },
    { source: "openrouter",      target: "mixtral8x22",    label: "provides access" },
    { source: "openrouter",      target: "commandr",       label: "provides access" },
    { source: "openrouter",      target: "llama3",         label: "provides access" },
    { source: "ollama",          target: "llama3",         label: "runs" },
    { source: "ollama",          target: "mistral7b",      label: "runs" },
    { source: "ollama",          target: "deepseekv3",     label: "runs" },
    { source: "ollama",          target: "phi3",           label: "runs" },
    { source: "ollama",          target: "gemma2",         label: "runs" },
    { source: "ollama",          target: "qwen25",         label: "runs" },
    { source: "ollama",          target: "deepseekr1",     label: "runs" },
    { source: "vllm",            target: "llama3",         label: "serves" },
    { source: "vllm",            target: "mixtral8x22",    label: "serves" },
    { source: "vllm",            target: "deepseekv3",     label: "serves" },
    { source: "vllm",            target: "spec_decode",    label: "implements" },
    { source: "tgi",             target: "llama3",         label: "serves" },
    { source: "tgi",             target: "mistral7b",      label: "serves" },
    { source: "litellm",         target: "openrouter",     label: "unifies" },
    { source: "litellm",         target: "gpt4o",          label: "proxies" },
    { source: "litellm",         target: "claude35",       label: "proxies" },
    { source: "pytorch",         target: "transformers_lib",label: "foundation for" },
    { source: "pytorch",         target: "llama3",         label: "trains" },
    { source: "pytorch",         target: "deepseekv3",     label: "trains" },
    { source: "transformers_lib",target: "llama3",         label: "hosts" },
    { source: "transformers_lib",target: "gemma2",         label: "hosts" },
    { source: "transformers_lib",target: "mistral7b",      label: "hosts" },
    { source: "transformers_lib",target: "falcon40b",      label: "hosts" },
    { source: "transformers_lib",target: "zephyr7b",       label: "hosts" },
    { source: "semantic_kernel", target: "agents",         label: "builds" },
    { source: "semantic_kernel", target: "microsoft",      label: "by" },
    { source: "agentops",        target: "agents",         label: "monitors" },
    { source: "agentops",        target: "langchain",      label: "integrates" },
    { source: "agentops",        target: "crewai",         label: "integrates" },
    { source: "langflow",        target: "langchain",      label: "visualizes" },
    { source: "flowise",         target: "langchain",      label: "visualizes" },
    { source: "flowise",         target: "rag",            label: "enables" },
    { source: "instructor",      target: "structured_output", label: "implements" },
    { source: "instructor",      target: "functioncalling", label: "uses" },
    { source: "pydantic_ai",     target: "agents",         label: "builds" },
    { source: "pydantic_ai",     target: "structured_output", label: "enforces" },
    { source: "smolagents",      target: "agents",         label: "builds" },
    { source: "smolagents",      target: "code_gen",       label: "uses" },
    { source: "mlflow",          target: "wandb",          label: "competes with" },
    { source: "mlflow",          target: "finetuning",     label: "tracks" },
    { source: "ray_fw",          target: "vllm",           label: "powers" },
    { source: "streamlit",       target: "gradio",         label: "competes with" },
    { source: "gradio",          target: "huggingfacehub", label: "hosted on" },
    { source: "e2b",             target: "agents",         label: "sandboxes" },
    { source: "e2b",             target: "code_gen",       label: "executes" },

    // ════════════════════════════════════════════════════════════
    // TOOLS INTERCONNECTIONS
    // ════════════════════════════════════════════════════════════
    { source: "vectordb",        target: "pinecone",       label: "example" },
    { source: "vectordb",        target: "chroma",         label: "example" },
    { source: "vectordb",        target: "qdrant",         label: "example" },
    { source: "vectordb",        target: "milvus",         label: "example" },
    { source: "vectordb",        target: "weaviate",       label: "example" },
    { source: "vectordb",        target: "pgvector",       label: "example" },
    { source: "pinecone",        target: "embeddings",     label: "stores" },
    { source: "qdrant",          target: "embeddings",     label: "stores" },
    { source: "weaviate",        target: "hybrid_search",  label: "enables" },
    { source: "huggingfacehub",  target: "llama3",         label: "hosts" },
    { source: "huggingfacehub",  target: "mistral7b",      label: "hosts" },
    { source: "huggingfacehub",  target: "gemma2",         label: "hosts" },
    { source: "huggingfacehub",  target: "flux1",          label: "hosts" },
    { source: "huggingfacehub",  target: "zephyr7b",       label: "hosts" },
    { source: "huggingfacehub",  target: "smollm",         label: "hosts" },
    { source: "wandb",           target: "finetuning",     label: "tracks" },
    { source: "wandb",           target: "eval",           label: "tracks" },
    { source: "langsmith",       target: "agents",         label: "monitors" },
    { source: "langsmith",       target: "langchain",      label: "monitors" },
    { source: "github_copilot",  target: "code_gen",       label: "implements" },
    { source: "github_copilot",  target: "microsoft",      label: "by" },
    { source: "github_copilot",  target: "gpt4o",          label: "powered by" },
    { source: "cursor",          target: "code_gen",       label: "implements" },
    { source: "cursor",          target: "claude35",       label: "uses" },
    { source: "cursor",          target: "gpt4o",          label: "uses" },
    { source: "aider",           target: "code_gen",       label: "implements" },
    { source: "aider",           target: "claude35",       label: "uses" },
    { source: "opendevin",       target: "computer_use",   label: "implements" },
    { source: "opendevin",       target: "code_gen",       label: "specializes in" },
    { source: "bedrock",         target: "claude35",       label: "hosts" },
    { source: "bedrock",         target: "llama3",         label: "hosts" },
    { source: "bedrock",         target: "commandr",       label: "hosts" },
    { source: "vertex_ai",       target: "gemini15",       label: "hosts" },
    { source: "vertex_ai",       target: "gemma2",         label: "hosts" },
    { source: "azure_openai",    target: "gpt4o",          label: "hosts" },
    { source: "azure_openai",    target: "gpt4turbo",      label: "hosts" },
    { source: "sagemaker",       target: "llama3",         label: "trains" },
    { source: "sagemaker",       target: "finetuning",     label: "enables" },
    { source: "tensorrt",        target: "llama3",         label: "optimizes" },
    { source: "tensorrt",        target: "mixtral8x22",    label: "optimizes" },
    { source: "sentence_transformers", target: "embeddings", label: "creates" },
    { source: "sentence_transformers", target: "semantic_search", label: "enables" },
    { source: "helicone",        target: "gpt4o",          label: "observes" },
    { source: "helicone",        target: "eval",           label: "tracks" },
    { source: "promptlayer",     target: "prompteng",      label: "manages" },
    { source: "v0",              target: "code_gen",       label: "implements" },
    { source: "bolt",            target: "code_gen",       label: "implements" },
    { source: "bolt",            target: "agents",         label: "uses" },
    { source: "modal",           target: "vllm",           label: "hosts" },
    { source: "modal",           target: "pytorch",        label: "runs" },
    { source: "bentoml",         target: "llama3",         label: "serves" },
    { source: "bentoml",         target: "pytorch",        label: "wraps" },

    // ════════════════════════════════════════════════════════════
    // CONCEPT RELATIONSHIPS
    // ════════════════════════════════════════════════════════════
    { source: "agents",          target: "rag",            label: "uses" },
    { source: "agents",          target: "mcp",            label: "uses" },
    { source: "agents",          target: "tooluse",        label: "requires" },
    { source: "agents",          target: "longtermemory",  label: "benefits from" },
    { source: "agents",          target: "automation",     label: "enables" },
    { source: "agents",          target: "multiagent",     label: "composes into" },
    { source: "rag",             target: "vectordb",       label: "requires" },
    { source: "rag",             target: "embeddings",     label: "uses" },
    { source: "rag",             target: "hallucination",  label: "reduces" },
    { source: "rag",             target: "grounding",      label: "enables" },
    { source: "rag",             target: "graph_rag",      label: "extends to" },
    { source: "rag",             target: "agentic_rag",    label: "extends to" },
    { source: "rag",             target: "self_rag",       label: "extends to" },
    { source: "rlhf",            target: "alignment",      label: "enables" },
    { source: "mcp",             target: "tooluse",        label: "standardizes" },
    { source: "mcp",             target: "automation",     label: "enables" },
    { source: "tooluse",         target: "functioncalling",label: "via" },
    { source: "tooluse",         target: "computer_use",   label: "extends to" },
    { source: "prompteng",       target: "agents",         label: "optimizes" },
    { source: "prompteng",       target: "hallucination",  label: "reduces" },
    { source: "cot",             target: "prompteng",      label: "technique of" },
    { source: "synthdata",       target: "finetuning",     label: "used in" },
    { source: "hallucination",   target: "grounding",      label: "solved by" },
    { source: "hallucination",   target: "alignment",      label: "challenges" },
    { source: "hallucination",   target: "eval",           label: "measured by" },
    { source: "grounding",       target: "rag",            label: "achieved via" },
    { source: "grounding",       target: "knowledge_base", label: "uses" },
    { source: "ai_ethics",       target: "bias_fairness",  label: "includes" },
    { source: "ai_ethics",       target: "ai_safety_concept", label: "includes" },
    { source: "ai_ethics",       target: "alignment",      label: "includes" },
    { source: "ai_ethics",       target: "xai_concept",    label: "includes" },
    { source: "ai_safety_concept",target: "alignment",     label: "requires" },
    { source: "ai_safety_concept",target: "red_teaming",   label: "uses" },
    { source: "xai_concept",     target: "interpretability",label: "requires" },
    { source: "context_window",  target: "kv_cache",       label: "limited by" },
    { source: "context_window",  target: "gemini15",       label: "extreme in" },
    { source: "context_window",  target: "llama31",        label: "extended in" },
    { source: "image_gen",       target: "diffusion_models",label: "uses" },
    { source: "image_gen",       target: "dalle3",         label: "example" },
    { source: "image_gen",       target: "midjourney",     label: "example" },
    { source: "image_gen",       target: "sdxl",           label: "example" },
    { source: "image_gen",       target: "flux1",          label: "example" },
    { source: "video_gen",       target: "sora",           label: "example" },
    { source: "video_gen",       target: "veo2",           label: "example" },
    { source: "video_gen",       target: "pika_model",     label: "example" },
    { source: "music_gen",       target: "suno_model",     label: "example" },
    { source: "voice_cloning",   target: "elevenlabs",     label: "used by" },
    { source: "stt",             target: "whisper",        label: "example" },
    { source: "tts",             target: "elevenlabs",     label: "used by" },
    { source: "code_gen",        target: "codestral",      label: "example" },
    { source: "code_gen",        target: "deepseekcoder",  label: "example" },
    { source: "code_gen",        target: "codellama",      label: "example" },
    { source: "code_gen",        target: "qwen_coder",     label: "example" },
    { source: "code_gen",        target: "github_copilot", label: "implemented by" },
    { source: "computer_use",    target: "claude35",       label: "first in" },
    { source: "computer_use",    target: "agents",         label: "enables" },
    { source: "math_reasoning",  target: "o1",             label: "excels in" },
    { source: "math_reasoning",  target: "deepseekr1",     label: "excels in" },
    { source: "medical_ai",      target: "multimodal",     label: "leverages" },
    { source: "multiagent",      target: "crewai",         label: "built with" },
    { source: "multiagent",      target: "autogen",        label: "built with" },
    { source: "multiagent",      target: "metagpt",        label: "built with" },
    { source: "structured_output",target: "functioncalling",label: "implemented via" },
    { source: "semantic_search", target: "embeddings",     label: "uses" },
    { source: "semantic_search", target: "vectordb",       label: "uses" },
    { source: "hybrid_search",   target: "semantic_search",label: "combines" },
    { source: "reranking",       target: "rag",            label: "improves" },
    { source: "reranking",       target: "hybrid_search",  label: "follows" },
    { source: "graph_rag",       target: "knowledge_base", label: "uses" },
    { source: "agentic_rag",     target: "agents",         label: "uses" },
    { source: "knowledge_base",  target: "rag",            label: "powers" },
    { source: "ocr",             target: "multimodal",     label: "uses" },
    { source: "federated_learning", target: "ai_ethics",   label: "supports" },
    { source: "eval",            target: "benchmark",      label: "uses" },
    { source: "eval",            target: "alignment",      label: "measures" },
    { source: "tokenization",    target: "transformers",   label: "feeds into" },
    { source: "temperature",     target: "prompteng",      label: "parameter of" },

    // ════════════════════════════════════════════════════════════
    // MODEL CAPABILITIES
    // ════════════════════════════════════════════════════════════
    { source: "gpt4o",       target: "multimodal",    label: "is" },
    { source: "gemini15",    target: "multimodal",    label: "is" },
    { source: "gemini20flash",target: "multimodal",   label: "is" },
    { source: "llama32",     target: "multimodal",    label: "is" },
    { source: "gpt4o",       target: "reasoning",     label: "has" },
    { source: "claude35",    target: "reasoning",     label: "has" },
    { source: "claude4sonnet",target: "reasoning",    label: "has" },
    { source: "deepseekv3",  target: "reasoning",     label: "has" },
    { source: "deepseekr1",  target: "reasoning",     label: "specializes in" },
    { source: "o1",          target: "reasoning",     label: "specializes in" },
    { source: "claude35",    target: "code_gen",      label: "excels at" },
    { source: "gpt4o",       target: "code_gen",      label: "excels at" },
    { source: "claude4sonnet",target: "computer_use", label: "implements" },
    { source: "llama31",     target: "context_window",label: "extends" },
    { source: "commandr",    target: "rag",           label: "optimized for" },
    { source: "sonar",       target: "rag",           label: "uses" },
    { source: "sonar",       target: "grounding",     label: "achieves" },
    { source: "finetuning",  target: "llama3",        label: "applied to" },
    { source: "finetuning",  target: "mistral7b",     label: "applied to" },
    { source: "phi3",        target: "knowledge_dist",label: "trained with" },
    { source: "phi2",        target: "knowledge_dist",label: "trained with" },
    { source: "smollm",      target: "quantization",  label: "uses" },
    { source: "tinyllama",   target: "quantization",  label: "uses" },

    // ════════════════════════════════════════════════════════════
    // ANTHROPIC SPECIAL LINKS
    // ════════════════════════════════════════════════════════════
    { source: "anthropic",   target: "mcp",            label: "created" },
    { source: "anthropic",   target: "constitutional", label: "developed" },
    { source: "anthropic",   target: "ai_safety_concept", label: "focuses on" },

    // ════════════════════════════════════════════════════════════
    // YOUTUBE CHANNELS
    // ════════════════════════════════════════════════════════════
    { source: "yt-two-minute",  target: "transformers",    label: "explains" },
    { source: "yt-two-minute",  target: "diffusion_models",label: "explains" },
    { source: "yt-karpathy",    target: "transformers",    label: "teaches" },
    { source: "yt-karpathy",    target: "finetuning",      label: "teaches" },
    { source: "yt-karpathy",    target: "openai",          label: "worked at" },
    { source: "yt-karpathy",    target: "pytorch",         label: "teaches" },
    { source: "yt-ai-explained",target: "reasoning",       label: "covers" },
    { source: "yt-ai-explained",target: "agents",          label: "covers" },
    { source: "yt-yannic",      target: "attention",       label: "reviews" },
    { source: "yt-yannic",      target: "scaling",         label: "reviews" },
    { source: "yt-yannic",      target: "moe",             label: "reviews" },
    { source: "yt-fireship",    target: "ollama",          label: "demos" },
    { source: "yt-fireship",    target: "openrouter",      label: "demos" },
    { source: "yt-fireship",    target: "cursor",          label: "demos" },
    { source: "yt-mattwolfe",   target: "agents",          label: "covers" },
    { source: "yt-mattwolfe",   target: "automation",      label: "covers" },
    { source: "yt-mattwolfe",   target: "image_gen",       label: "covers" },

    // ════════════════════════════════════════════════════════════
    // ADDITIONAL MODEL CAPABILITIES
    // ════════════════════════════════════════════════════════════
    { source: "gpt5",           target: "reasoning",       label: "excels at" },
    { source: "gpt5",           target: "multimodal",      label: "is" },
    { source: "gpt5",           target: "code_gen",        label: "excels at" },
    { source: "claude4sonnet",  target: "multimodal",      label: "is" },
    { source: "claude4sonnet",  target: "code_gen",        label: "excels at" },
    { source: "claude4sonnet",  target: "context_window",  label: "extends" },
    { source: "gemma3",         target: "multimodal",      label: "is" },
    { source: "gemma3",         target: "context_window",  label: "extends" },
    { source: "deepseekv3",     target: "code_gen",        label: "excels at" },
    { source: "deepseekv3",     target: "math_reasoning",  label: "excels at" },
    { source: "deepseekr1",     target: "math_reasoning",  label: "specializes in" },
    { source: "deepseekr1",     target: "cot",             label: "trained with" },
    { source: "phi4",           target: "code_gen",        label: "excels at" },
    { source: "phi4",           target: "reasoning",       label: "has" },
    { source: "phi4",           target: "knowledge_dist",  label: "trained with" },
    { source: "grok2",          target: "reasoning",       label: "has" },
    { source: "grok2",          target: "code_gen",        label: "has" },
    { source: "jamba",          target: "context_window",  label: "extends" },
    { source: "jamba",          target: "ssm",             label: "uses" },
    { source: "llama32",        target: "context_window",  label: "extends" },
    { source: "llama32",        target: "stt",             label: "includes" },
    { source: "llama31",        target: "code_gen",        label: "capable of" },
    { source: "llama31",        target: "reasoning",       label: "capable of" },
    { source: "qwen25",         target: "code_gen",        label: "capable of" },
    { source: "qwen25",         target: "math_reasoning",  label: "excels at" },
    { source: "commandr",       target: "tooluse",         label: "optimized for" },
    { source: "commandr",       target: "functioncalling", label: "supports" },
    { source: "gemini15",       target: "ocr",             label: "capable of" },
    { source: "gemini20flash",  target: "code_gen",        label: "capable of" },
    { source: "gemini20flash",  target: "tooluse",         label: "supports" },
    { source: "sonar",          target: "knowledge_base",  label: "queries" },
    { source: "sonar",          target: "grounding",       label: "achieves" },
    { source: "midjourney",     target: "image_gen",       label: "implements" },
    { source: "midjourney",     target: "diffusion_models",label: "uses" },
    { source: "whisper",        target: "stt",             label: "implements" },
    { source: "sora",           target: "video_gen",       label: "implements" },
    { source: "veo2",           target: "video_gen",       label: "implements" },
    { source: "pika_model",     target: "video_gen",       label: "implements" },
    { source: "suno_model",     target: "music_gen",       label: "implements" },
    { source: "sdxl",           target: "image_gen",       label: "implements" },
    { source: "sd3",            target: "image_gen",       label: "implements" },
    { source: "flux1",          target: "image_gen",       label: "implements" },
    { source: "dalle3",         target: "image_gen",       label: "implements" },
    { source: "imagen3",        target: "image_gen",       label: "implements" },
    { source: "codestral",      target: "code_gen",        label: "specializes in" },
    { source: "deepseekcoder",  target: "code_gen",        label: "specializes in" },
    { source: "codellama",      target: "code_gen",        label: "specializes in" },
    { source: "qwen_coder",     target: "code_gen",        label: "specializes in" },

    // ════════════════════════════════════════════════════════════
    // COMPANY → RESEARCH CONTRIBUTIONS
    // ════════════════════════════════════════════════════════════
    { source: "openai",         target: "scaling",         label: "pioneered" },
    { source: "openai",         target: "rlhf",            label: "developed" },
    { source: "openai",         target: "cot",             label: "published" },
    { source: "openai",         target: "few_shot",        label: "published" },
    { source: "openai",         target: "instruction_tuning", label: "published" },
    { source: "openai",         target: "spec_decode",     label: "uses" },
    { source: "google",         target: "attention",       label: "invented" },
    { source: "google",         target: "transformers",    label: "invented" },
    { source: "google",         target: "flashattn",       label: "published" },
    { source: "google",         target: "rope",            label: "uses" },
    { source: "google",         target: "benchmark",       label: "created" },
    { source: "anthropic",      target: "rlaif",           label: "developed" },
    { source: "anthropic",      target: "reward_modeling", label: "uses" },
    { source: "anthropic",      target: "interpretability",label: "researches" },
    { source: "anthropic",      target: "red_teaming",     label: "practices" },
    { source: "meta",           target: "lora",            label: "uses" },
    { source: "meta",           target: "rope",            label: "uses in llama" },
    { source: "meta",           target: "gqa",             label: "developed" },
    { source: "meta",           target: "flashattn",       label: "uses" },
    { source: "deepseek",       target: "moe",             label: "advanced" },
    { source: "deepseek",       target: "cot",             label: "trained with" },
    { source: "deepseek",       target: "kv_cache",        label: "optimized" },
    { source: "microsoft",      target: "lora",            label: "popularized" },
    { source: "microsoft",      target: "knowledge_dist",  label: "pioneered with phi" },
    { source: "microsoft",      target: "deepspeed",       label: "created" },
    { source: "nvidia_ai",      target: "flashattn",       label: "accelerates" },
    { source: "nvidia_ai",      target: "quantization",    label: "advances" },
    { source: "nvidia_ai",      target: "spec_decode",     label: "accelerates" },
    { source: "huggingface",    target: "lora",            label: "popularized PEFT" },
    { source: "huggingface",    target: "instruction_tuning", label: "enabled" },
    { source: "huggingface",    target: "benchmark",       label: "hosts" },
    { source: "databricks",     target: "instruction_tuning", label: "contributed" },

    // ════════════════════════════════════════════════════════════
    // COMPANY PARTNERSHIPS & INVESTMENTS
    // ════════════════════════════════════════════════════════════
    { source: "microsoft",      target: "openai",          label: "partners with" },
    { source: "aws_ai",         target: "anthropic",       label: "invests in" },
    { source: "google",         target: "anthropic",       label: "invests in" },
    { source: "nvidia_ai",      target: "openai",          label: "supplies GPUs" },
    { source: "nvidia_ai",      target: "anthropic",       label: "supplies GPUs" },
    { source: "nvidia_ai",      target: "google",          label: "supplies GPUs" },
    { source: "together",       target: "openrouter",      label: "partners with" },
    { source: "replicate",      target: "huggingface",     label: "integrates" },

    // ════════════════════════════════════════════════════════════
    // FRAMEWORK → FRAMEWORK CONNECTIONS
    // ════════════════════════════════════════════════════════════
    { source: "crewai",         target: "langchain",       label: "built on" },
    { source: "crewai",         target: "multiagent",      label: "enables" },
    { source: "langgraph",      target: "crewai",          label: "alternative to" },
    { source: "autogpt",        target: "automation",      label: "pioneered" },
    { source: "autogpt",        target: "langchain",       label: "inspired" },
    { source: "instructor",     target: "pydantic_ai",     label: "related to" },
    { source: "smolagents",     target: "transformers_lib",label: "uses" },
    { source: "langflow",       target: "flowise",         label: "competes with" },
    { source: "memgpt",         target: "langchain",       label: "integrates with" },
    { source: "dspy",           target: "langchain",       label: "alternative to" },
    { source: "guidance_fw",    target: "structured_output",label: "implements" },
    { source: "semantic_kernel",target: "autogen",         label: "related to" },
    { source: "ray_fw",         target: "pytorch",         label: "distributes" },
    { source: "bentoml",        target: "vllm",            label: "integrates" },
    { source: "mlflow",         target: "pytorch",         label: "tracks" },
    { source: "agentops",       target: "openrouter",      label: "monitors" },

    // ════════════════════════════════════════════════════════════
    // TOOLS → MODELS (more hosting/powering connections)
    // ════════════════════════════════════════════════════════════
    { source: "cursor",         target: "claude4sonnet",   label: "uses" },
    { source: "cursor",         target: "deepseekv3",      label: "uses" },
    { source: "cursor",         target: "deepseekr1",      label: "uses" },
    { source: "v0",             target: "claude35",        label: "uses" },
    { source: "bolt",           target: "claude4sonnet",   label: "uses" },
    { source: "aider",          target: "deepseekv3",      label: "uses" },
    { source: "aider",          target: "gpt4o",           label: "uses" },
    { source: "github_copilot", target: "claude4sonnet",   label: "offers" },
    { source: "bedrock",        target: "claude4sonnet",   label: "hosts" },
    { source: "bedrock",        target: "titan",           label: "hosts" },
    { source: "bedrock",        target: "mistral7b",       label: "hosts" },
    { source: "vertex_ai",      target: "gemini20flash",   label: "hosts" },
    { source: "vertex_ai",      target: "gemma3",          label: "hosts" },
    { source: "vertex_ai",      target: "claude4sonnet",   label: "hosts" },
    { source: "azure_openai",   target: "gpt5",            label: "will host" },
    { source: "openrouter",     target: "llama32",         label: "provides access" },
    { source: "openrouter",     target: "gemma3",          label: "provides access" },
    { source: "openrouter",     target: "phi4",            label: "provides access" },
    { source: "openrouter",     target: "qwen25",          label: "provides access" },
    { source: "openrouter",     target: "claude4sonnet",   label: "provides access" },
    { source: "openrouter",     target: "gpt5",            label: "provides access" },
    { source: "ollama",         target: "llama32",         label: "runs" },
    { source: "ollama",         target: "codestral",       label: "runs" },
    { source: "ollama",         target: "gemma3",          label: "runs" },
    { source: "ollama",         target: "phi4",            label: "runs" },
    { source: "tensorrt",       target: "deepseekv3",      label: "optimizes" },
    { source: "tensorrt",       target: "deepseekr1",      label: "optimizes" },
    { source: "groq",           target: "deepseekr1",      label: "accelerates" },
    { source: "groq",           target: "gemma2",          label: "accelerates" },
    { source: "together",       target: "deepseekv3",      label: "hosts" },
    { source: "together",       target: "llama32",         label: "hosts" },

    // ════════════════════════════════════════════════════════════
    // NVIDIA GPU INFRASTRUCTURE
    // ════════════════════════════════════════════════════════════
    { source: "nvidia_ai",      target: "pytorch",         label: "CUDA accelerates" },
    { source: "nvidia_ai",      target: "vllm",            label: "CUDA powers" },
    { source: "nvidia_ai",      target: "transformers_lib",label: "accelerates" },
    { source: "nvidia_ai",      target: "deepspeed",       label: "accelerates" },

    // ════════════════════════════════════════════════════════════
    // RICHER CONCEPT INTERCONNECTIONS
    // ════════════════════════════════════════════════════════════
    { source: "multimodal",     target: "image_gen",       label: "enables" },
    { source: "multimodal",     target: "video_gen",       label: "enables" },
    { source: "multimodal",     target: "stt",             label: "includes" },
    { source: "multimodal",     target: "tts",             label: "includes" },
    { source: "multimodal",     target: "ocr",             label: "includes" },
    { source: "multimodal",     target: "voice_cloning",   label: "enables" },
    { source: "agents",         target: "code_gen",        label: "uses" },
    { source: "agents",         target: "eval",            label: "measured by" },
    { source: "agents",         target: "longtermemory",   label: "needs" },
    { source: "agents",         target: "structured_output",label: "relies on" },
    { source: "agents",         target: "computer_use",    label: "can do" },
    { source: "rag",            target: "reranking",       label: "improved by" },
    { source: "rag",            target: "chunking",        label: "requires" },
    { source: "alignment",      target: "constitutional",  label: "via" },
    { source: "alignment",      target: "rlhf",            label: "via" },
    { source: "alignment",      target: "rlaif",           label: "via" },
    { source: "alignment",      target: "dpo",             label: "via" },
    { source: "finetuning",     target: "lora",            label: "uses" },
    { source: "finetuning",     target: "synthdata",       label: "uses" },
    { source: "finetuning",     target: "instruction_tuning",label: "type of" },
    { source: "reasoning",      target: "cot",             label: "enabled by" },
    { source: "reasoning",      target: "tot",             label: "enabled by" },
    { source: "reasoning",      target: "o1",              label: "exemplified by" },
    { source: "reasoning",      target: "deepseekr1",      label: "exemplified by" },
    { source: "reasoning",      target: "math_reasoning",  label: "includes" },
    { source: "embeddings",     target: "sentence_transformers",label: "created by" },
    { source: "embeddings",     target: "pgvector",        label: "stored in" },
    { source: "embeddings",     target: "qdrant",          label: "stored in" },
    { source: "embeddings",     target: "milvus",          label: "stored in" },
    { source: "embeddings",     target: "weaviate",        label: "stored in" },
    { source: "context_window", target: "gemini15",        label: "extreme in" },
    { source: "context_window", target: "claude4sonnet",   label: "extended in" },
    { source: "context_window", target: "llama31",         label: "extended in" },
    { source: "prompteng",      target: "cot",             label: "includes" },
    { source: "prompteng",      target: "few_shot",        label: "includes" },
    { source: "prompteng",      target: "zero_shot",       label: "includes" },
    { source: "prompteng",      target: "temperature",     label: "controls via" },
    { source: "hallucination",  target: "red_teaming",     label: "exposed by" },
    { source: "hallucination",  target: "eval",            label: "measured by" },
    { source: "automation",     target: "mcp",             label: "enabled by" },
    { source: "automation",     target: "agents",          label: "powered by" },
    { source: "eval",           target: "wandb",           label: "tracked by" },
    { source: "eval",           target: "langsmith",       label: "tracked by" },
    { source: "knowledge_base", target: "vectordb",        label: "stored in" },
    { source: "knowledge_base", target: "rag",             label: "queried via" },
    { source: "synthdata",      target: "finetuning",      label: "enables" },
    { source: "synthdata",      target: "knowledge_dist",  label: "uses" },
    { source: "tokenization",   target: "context_window",  label: "determines" },
    { source: "functioncalling",target: "mcp",             label: "standardized by" },
    { source: "functioncalling",target: "structured_output",label: "requires" },
    { source: "computer_use",   target: "gpt4o",           label: "implemented in" },
    { source: "medical_ai",     target: "rag",             label: "uses" },
    { source: "medical_ai",     target: "alignment",       label: "requires" },
    { source: "semantic_search",target: "reranking",       label: "improved by" },
    { source: "hybrid_search",  target: "vectordb",        label: "uses" },
    { source: "graph_rag",      target: "semantic_search", label: "uses" },
    { source: "agentic_rag",    target: "tooluse",         label: "uses" },
    { source: "self_rag",       target: "eval",            label: "uses for retrieval" },
    { source: "longtermemory",  target: "embeddings",      label: "uses" },
    { source: "longtermemory",  target: "vectordb",        label: "stored in" },
    { source: "longtermemory",  target: "knowledge_base",  label: "part of" },
    { source: "voice_cloning",  target: "tts",             label: "type of" },
    { source: "stt",            target: "tts",             label: "paired with" },
    { source: "structured_output",target: "rag",           label: "improves" },
    { source: "interpretability",target: "hallucination",  label: "explains" },
    { source: "federated_learning",target: "privacy",      label: "enables" },
    { source: "bias_fairness",  target: "eval",            label: "measured by" },
  ],
};
