import { ResearchPaper } from "@/types";

export const FEATURED_PAPERS: ResearchPaper[] = [
  {
    id: "paper-001",
    title: "Attention Is All You Need",
    authors: ["Vaswani, A.", "Shazeer, N.", "Parmar, N.", "Uszkoreit, J."],
    abstract: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.",
    tldr: "Introduced the Transformer architecture, which became foundational for modern LLMs like BERT, GPT, and T5.",
    url: "https://arxiv.org/abs/1706.03762",
    arxivId: "1706.03762",
    publishedAt: "2017-06-12",
    citations: 87000,
    categories: ["transformers", "nlp", "architecture"],
  },
  {
    id: "paper-002",
    title: "Language Models are Unsupervised Multitask Learners",
    authors: ["Radford, A.", "Wu, J.", "Child, R.", "Luan, D.", "Amodei, D."],
    abstract: "Natural language processing tasks are typically approached with supervised learning on task-specific datasets. We demonstrate that language models begin to learn these tasks without any explicit supervision when trained on a new dataset of Internet text curated to be large and diverse.",
    tldr: "Introduced GPT-2, demonstrating that language models can perform diverse tasks through in-context learning without task-specific training.",
    url: "https://arxiv.org/abs/1901.02860",
    arxivId: "1901.02860",
    publishedAt: "2019-02-14",
    citations: 22000,
    categories: ["gpt", "language-models", "in-context-learning"],
  },
  {
    id: "paper-003",
    title: "Language Models are Few-Shot Learners",
    authors: ["Brown, T.", "Mann, B.", "Ryder, N.", "Subbiah, M.", "Kaplan, J."],
    abstract: "Recent work has demonstrated substantial gains on many NLP tasks and benchmarks by pre-training on a large corpus of text followed by fine-tuning on a specific task. While typically task-agnostic in architecture, this method still requires task-specific fine-tuning datasets of thousands or tens of thousands of examples.",
    tldr: "Introduced GPT-3, showing that in-context learning enables few-shot performance without fine-tuning.",
    url: "https://arxiv.org/abs/2005.14165",
    arxivId: "2005.14165",
    publishedAt: "2020-06-11",
    citations: 45000,
    categories: ["gpt", "language-models", "few-shot-learning"],
  },
  {
    id: "paper-004",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    authors: ["Devlin, J.", "Chang, M.", "Lee, K.", "Toutanova, K."],
    abstract: "We introduce BERT, a new method of pre-training language representations. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.",
    tldr: "Introduced BERT, demonstrating the power of bidirectional pre-training and transforming NLP.",
    url: "https://arxiv.org/abs/1810.04805",
    arxivId: "1810.04805",
    publishedAt: "2018-10-11",
    citations: 70000,
    categories: ["bert", "transformers", "nlp"],
  },
  {
    id: "paper-005",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    authors: ["Lewis, P.", "Perez, E.", "Piktus, A.", "Schwenk, H.", "Schwab, D."],
    abstract: "Large pre-trained language models have been shown to store factual knowledge in their parameters, yet their ability to access and precisely manipulate knowledge is still limited, and they cannot easily update their memory as new facts emerge.",
    tldr: "Introduced RAG, combining retrieval and generation for improved factual accuracy in NLP.",
    url: "https://arxiv.org/abs/2005.11401",
    arxivId: "2005.11401",
    publishedAt: "2020-05-22",
    citations: 12000,
    categories: ["rag", "retrieval", "language-models"],
  },
  {
    id: "paper-006",
    title: "Emergent Abilities of Large Language Models",
    authors: ["Wei, J.", "Tay, Y.", "Bommasani, R.", "Raffel, C.", "Zoph, B."],
    abstract: "Scaling up language models has been shown to predictably improve performance and sample efficiency on a large range of downstream tasks. This paper investigates an unpredicted phenomenon that we refer to as emergent abilities.",
    tldr: "Demonstrated that large language models exhibit emergent abilities that aren't present in smaller models.",
    url: "https://arxiv.org/abs/2206.07682",
    arxivId: "2206.07682",
    publishedAt: "2022-06-15",
    citations: 8000,
    categories: ["language-models", "scaling", "emergent-abilities"],
  },
  {
    id: "paper-007",
    title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
    authors: ["Wei, J.", "Wang, X.", "Schuurmans, D.", "Bosma, M.", "Chi, E."],
    abstract: "We explore how to best prompt language models for reasoning. Starting with the simple baseline of few-shot prompting, we investigate whether language models can perform reasoning via chain-of-thought prompting, where a model is asked to explain its reasoning as a series of intermediate steps before answering a question.",
    tldr: "Introduced chain-of-thought prompting, a technique that dramatically improves reasoning in language models.",
    url: "https://arxiv.org/abs/2201.11903",
    arxivId: "2201.11903",
    publishedAt: "2022-01-28",
    citations: 15000,
    categories: ["prompt-engineering", "reasoning", "language-models"],
  },
  {
    id: "paper-008",
    title: "Constitutional AI: Harmlessness from AI Feedback",
    authors: ["Bai, Y.", "Kadavath, S.", "Kundu, S.", "Askell, A.", "Kernion, J."],
    abstract: "A significant bottleneck in scaling language model alignment via reinforcement learning from human feedback (RLHF) is the expense of human feedback. To address this, we introduce Constitutional AI (CAI), a method for training language models to be harmless without any human feedback.",
    tldr: "Proposed Constitutional AI for training safer models using AI feedback instead of human feedback.",
    url: "https://arxiv.org/abs/2212.08073",
    arxivId: "2212.08073",
    publishedAt: "2022-12-15",
    citations: 3000,
    categories: ["alignment", "safety", "language-models"],
  },
  {
    id: "paper-009",
    title: "Scaling Vision Transformers",
    authors: ["Zhai, X.", "Kolesnikov, A.", "Houlsby, N.", "Beyer, L."],
    abstract: "This work studies the scaling properties of vision transformers. We investigate the scaling laws for vision transformers and present a simple and effective approach for scaling them to arbitrary sizes by using different architectural configurations.",
    tldr: "Studied how vision transformers scale with model size and compute.",
    url: "https://arxiv.org/abs/2106.04560",
    arxivId: "2106.04560",
    publishedAt: "2021-06-08",
    citations: 4500,
    categories: ["vision-transformers", "computer-vision", "scaling"],
  },
  {
    id: "paper-010",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    authors: ["Dosovitskiy, A.", "Beyer, L.", "Kolesnikov, A.", "Weissenborn, D.", "Houlsby, N."],
    abstract: "While the Transformer architecture has become the de-facto standard for natural language processing tasks, its applications to computer vision remain limited. In vision, attention is either applied in conjunction with convolutional networks, or used to replace certain components of convolutional networks while keeping their overall structure.",
    tldr: "Introduced Vision Transformers (ViT), showing transformers work well for image recognition.",
    url: "https://arxiv.org/abs/2010.11929",
    arxivId: "2010.11929",
    publishedAt: "2020-10-22",
    citations: 35000,
    categories: ["vision-transformers", "computer-vision", "transformers"],
  },
  {
    id: "paper-011",
    title: "Flamingo: a Visual Language Model for Few-Shot Learning",
    authors: ["Alayrac, J.", "Donahue, J.", "Luc, P.", "Miech, A.", "Barr, I."],
    abstract: "Building and releasing a multimodal model that can handle different types of inputs and outputs is challenging. We present Flamingo, a family of visual language models (VLMs) that can perceive and understand arbitrary combinations of images, text, and videos.",
    tldr: "Introduced Flamingo, a multimodal model for few-shot learning with images and text.",
    url: "https://arxiv.org/abs/2204.14198",
    arxivId: "2204.14198",
    publishedAt: "2022-04-29",
    citations: 2500,
    categories: ["multimodal", "vision-language", "few-shot-learning"],
  },
  {
    id: "paper-012",
    title: "Agents: An Open-source Framework for Autonomous Agents",
    authors: ["Wang, J.", "Zhou, H.", "Sun, Y.", "Li, L.", "Zhang, Q."],
    abstract: "This paper presents an open-source framework for building autonomous agents that can use language models as their core reasoning engine. We demonstrate how to equip language models with tools and memory for completing complex tasks.",
    tldr: "Introduced an agent framework showing how to build autonomous systems with LLMs.",
    url: "https://arxiv.org/abs/2309.16609",
    arxivId: "2309.16609",
    publishedAt: "2023-09-28",
    citations: 1200,
    categories: ["agents", "language-models", "autonomous-systems"],
  },
  {
    id: "paper-013",
    title: "Gorilla: Large Language Model Connected with Massive APIs",
    authors: ["Patil, S.", "Zhang, T.", "Wang, X.", "Gonzalez, J."],
    abstract: "Large language models (LLMs) have shown remarkable capabilities as a generalist agent. However, their ability to invoke and compose multiple APIs to solve complex real-world tasks remains limited.",
    tldr: "Introduced Gorilla, demonstrating how LLMs can effectively use multiple APIs.",
    url: "https://arxiv.org/abs/2305.15334",
    arxivId: "2305.15334",
    publishedAt: "2023-05-24",
    citations: 800,
    categories: ["agents", "api-integration", "language-models"],
  },
  {
    id: "paper-014",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    authors: ["Yao, S.", "Zhao, J.", "Yu, D.", "Du, N.", "Shafran, I."],
    abstract: "While large language models (LLMs) have demonstrated impressive capabilities across tasks in language understanding and interactive decision making, their abilities for reasoning and acting remain limited.",
    tldr: "Introduced ReAct, showing how reasoning and acting can be combined in agents.",
    url: "https://arxiv.org/abs/2210.03629",
    arxivId: "2210.03629",
    publishedAt: "2022-10-06",
    citations: 5000,
    categories: ["agents", "reasoning", "prompt-engineering"],
  },
  {
    id: "paper-015",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    authors: ["Schick, T.", "Dwivedi-Yu, J.", "Dessì, R.", "Raileanu, R.", "Lomeli, M."],
    abstract: "Language models exhibit remarkable abilities to solve new tasks from just a few examples or from natural language instructions, without any parameter updates. Motivated by observing how humans leverage external tools like search engines or calculators when faced with tasks they cannot easily solve by themselves, we teach language models to use external tools.",
    tldr: "Showed how to train LLMs to autonomously call and use external tools.",
    url: "https://arxiv.org/abs/2302.04761",
    arxivId: "2302.04761",
    publishedAt: "2023-02-09",
    citations: 3500,
    categories: ["agents", "tool-use", "language-models"],
  },
  {
    id: "paper-016",
    title: "LLaMA: Open and Efficient Foundation Language Models",
    authors: ["Touvron, H.", "Lavril, T.", "Izacard, G.", "Martinet, X.", "Lachaux, M."],
    abstract: "In this work, we develop and release Llama, a collection of foundation language models ranging from 7B to 65B parameters. We show that it is possible to significantly outperform GPT-3 (175B) while using 5-13x fewer parameters by training, for longer, on more tokens.",
    tldr: "Introduced LLaMA, showing efficient large language models can be open-sourced.",
    url: "https://arxiv.org/abs/2302.13971",
    arxivId: "2302.13971",
    publishedAt: "2023-02-27",
    citations: 8000,
    categories: ["llama", "open-source", "language-models"],
  },
  {
    id: "paper-017",
    title: "Mistral 7B",
    authors: ["Jiang, A.", "Sablayrolles, A.", "Mensch, A.", "Bamford, C.", "Chaplot, D."],
    abstract: "We introduce Mistral 7B, a 7-billion-parameter language model engineered for superior performance and efficiency. We leverage grouped-query attention to achieve efficient inference. We further show that instruction-tuning our model can lead to improved performance.",
    tldr: "Released Mistral 7B, a highly efficient 7B parameter model with strong performance.",
    url: "https://arxiv.org/abs/2310.06825",
    arxivId: "2310.06825",
    publishedAt: "2023-10-10",
    citations: 2000,
    categories: ["mistral", "open-source", "language-models"],
  },
  {
    id: "paper-018",
    title: "Direct Preference Optimization: Your Language Model is Secret Reward Model",
    authors: ["Rafailov, R.", "Sharma, A.", "Mitchell, E.", "Manning, C.", "Finn, C."],
    abstract: "While large language models (LLMs) are widely deployed, there remain many challenges in aligning these models with human preferences. Existing methods like reinforcement learning from human feedback (RLHF) are complex and often unstable in practice.",
    tldr: "Introduced DPO, a simpler alternative to RLHF for aligning language models.",
    url: "https://arxiv.org/abs/2305.18290",
    arxivId: "2305.18290",
    publishedAt: "2023-05-29",
    citations: 2000,
    categories: ["alignment", "fine-tuning", "language-models"],
  },
  {
    id: "paper-019",
    title: "Efficient Transformers: A Survey",
    authors: ["Tay, Y.", "Dehghani, M.", "Abnar, S.", "Shen, Y.", "Alfonseca, E."],
    abstract: "Transformers have become one of the most important architectures in deep learning. However, the quadratic complexity of the self-attention mechanism creates a bottleneck, especially for long sequences.",
    tldr: "Comprehensive survey of efficient transformer variants and techniques.",
    url: "https://arxiv.org/abs/2009.14794",
    arxivId: "2009.14794",
    publishedAt: "2020-09-30",
    citations: 8000,
    categories: ["transformers", "efficiency", "nlp"],
  },
  {
    id: "paper-020",
    title: "The Curious Case of Hallucinations in Neural Machine Translation",
    authors: ["Kang, D.", "Hashimoto, T.", "Li, Y.", "Yin, P.", "Bastani, O."],
    abstract: "Neural machine translation (NMT) systems based on the sequence-to-sequence paradigm have achieved impressive performance. However, there remains a critical issue: NMT systems sometimes produce completely inaccurate translations that are nonsensical or hallucinated.",
    tldr: "Analyzed hallucination phenomenon in neural machine translation systems.",
    url: "https://arxiv.org/abs/2104.05602",
    arxivId: "2104.05602",
    publishedAt: "2021-04-12",
    citations: 1500,
    categories: ["hallucinations", "language-models", "nmt"],
  },
  {
    id: "paper-021",
    title: "Prompt Injection: What's the Problem?",
    authors: ["Greshake, K.", "Shahbazi, B.", "Eucalyptus", "Tanaka, M.", "Teufel, S."],
    abstract: "With the widespread adoption of large language models (LLMs) for both user-facing applications and as a backbone for AI systems, prompt injection attacks have emerged as a significant security concern.",
    tldr: "Analyzed prompt injection attacks and their implications for LLM security.",
    url: "https://arxiv.org/abs/2310.00944",
    arxivId: "2310.00944",
    publishedAt: "2023-10-02",
    citations: 500,
    categories: ["security", "prompt-engineering", "language-models"],
  },
  {
    id: "paper-022",
    title: "Sparks of Artificial General Intelligence: Early experiments with GPT-4",
    authors: ["Bubeck, S.", "Chandrasekaran, V.", "Eldan, R.", "Grangier, D.", "Hoffman, M."],
    abstract: "Artificial general intelligence (AGI) has been the long-standing dream of AI research. In the past decade, advances in deep learning and scale have been impressive but still incremental progress.",
    tldr: "Examined early signs of AGI-like capabilities in GPT-4.",
    url: "https://arxiv.org/abs/2303.12712",
    arxivId: "2303.12712",
    publishedAt: "2023-03-27",
    citations: 6000,
    categories: ["gpt-4", "agi", "language-models"],
  },
  {
    id: "paper-023",
    title: "Context Window Extension via Scaling",
    authors: ["Li, J.", "Sun, Y.", "Du, R.", "Ren, G.", "Liang, Y."],
    abstract: "Large language models have shown impressive performance on a wide variety of tasks. However, they are typically limited to processing input sequences of fixed maximum length. We introduce a method to extend the context window of pre-trained LLMs.",
    tldr: "Presented techniques for extending the context window of language models.",
    url: "https://arxiv.org/abs/2309.04437",
    arxivId: "2309.04437",
    publishedAt: "2023-09-08",
    citations: 1200,
    categories: ["language-models", "context-window", "scaling"],
  },
  {
    id: "paper-024",
    title: "In-Context Learning and Induction Heads",
    authors: ["Todd, E.", "Voelker, M.", "Liphardt, J."],
    abstract: "In-context learning (ICL) in large language models is a phenomenon where models learn to perform new tasks from examples provided in the prompt, without any parameter updates.",
    tldr: "Explained the mechanisms behind in-context learning through induction heads.",
    url: "https://arxiv.org/abs/2202.05262",
    arxivId: "2202.05262",
    publishedAt: "2022-02-11",
    citations: 2800,
    categories: ["in-context-learning", "language-models", "interpretability"],
  },
  {
    id: "paper-025",
    title: "Unified-IO: A Unified Model for Vision, Language, and Vision-Language Tasks",
    authors: ["Lu, J.", "Clark, C.", "Zellers, R.", "Mottaghi, R.", "Kembhavi, A."],
    abstract: "Modern artificial intelligence is increasingly adopting unified models that can handle multiple modalities and tasks. In this work, we introduce Unified-IO, a unified model for vision and language understanding that can handle a diverse range of tasks with a single model.",
    tldr: "Introduced Unified-IO, a single model for both vision and language tasks.",
    url: "https://arxiv.org/abs/2206.08916",
    arxivId: "2206.08916",
    publishedAt: "2022-06-17",
    citations: 900,
    categories: ["multimodal", "vision-language", "unified-models"],
  },
  {
    id: "paper-026",
    title: "QA-LoRA: Quantization-Aware Low-Rank Adaptation of Large Language Models",
    authors: ["Ma, X.", "Fang, G.", "Wang, Z."],
    abstract: "Adapter-based approaches have shown great promise for fine-tuning and efficiently adapting large language models. However, these methods still require significant computational resources.",
    tldr: "Introduced QA-LoRA for efficient quantization-aware fine-tuning.",
    url: "https://arxiv.org/abs/2309.14717",
    arxivId: "2309.14717",
    publishedAt: "2023-09-26",
    citations: 400,
    categories: ["fine-tuning", "quantization", "lora"],
  },
  {
    id: "paper-027",
    title: "Token-level Reference-free Hallucination Detection for Free-form Text Generation",
    authors: ["Huang, L.", "Feng, W.", "Wan, L.", "Jin, H."],
    abstract: "Hallucination is a persistent problem in neural text generation. Existing hallucination detection methods typically require reference texts, which are often unavailable in practice.",
    tldr: "Proposed reference-free methods for detecting hallucinations in generated text.",
    url: "https://arxiv.org/abs/2310.12467",
    arxivId: "2310.12467",
    publishedAt: "2023-10-19",
    citations: 300,
    categories: ["hallucinations", "text-generation", "language-models"],
  },
  {
    id: "paper-028",
    title: "Scaling Instruction-Finetuned Language Models",
    authors: ["Chowdhery, A.", "Narang, S.", "Devlin, J.", "Bosma, M.", "Mishra, G."],
    abstract: "Finetuning language models on a collection of datasets phrased as instructions has been shown to improve model performance and generalization to unseen tasks. In this paper, we explore the impact of instruction finetuning on scaling laws.",
    tldr: "Showed that instruction fine-tuning scales well with model size.",
    url: "https://arxiv.org/abs/2210.11416",
    arxivId: "2210.11416",
    publishedAt: "2022-10-20",
    citations: 5500,
    categories: ["fine-tuning", "language-models", "instruction-tuning"],
  },
  {
    id: "paper-029",
    title: "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
    authors: ["Wang, X.", "Wei, J.", "Schuurmans, D.", "Le, Q.", "Chi, E."],
    abstract: "Chain of thought prompting has shown impressive results in reasoning tasks. However, the quality of generated intermediate steps significantly influences the final answer accuracy.",
    tldr: "Introduced self-consistency to improve reasoning by sampling multiple chain-of-thought paths.",
    url: "https://arxiv.org/abs/2203.11171",
    arxivId: "2203.11171",
    publishedAt: "2022-03-21",
    citations: 4200,
    categories: ["reasoning", "prompt-engineering", "language-models"],
  },
  {
    id: "paper-030",
    title: "Multi-Agent Communication meets Natural Language",
    authors: ["Pitis, S.", "Czarnecki, K.", "Jojic, N."],
    abstract: "Multi-agent reinforcement learning has shown promise for solving complex cooperative tasks. However, learning effective communication between agents remains challenging.",
    tldr: "Explored how to use natural language for multi-agent communication.",
    url: "https://arxiv.org/abs/2212.14734",
    arxivId: "2212.14734",
    publishedAt: "2022-12-28",
    citations: 600,
    categories: ["agents", "multiagent-systems", "language-models"],
  },
  {
    id: "paper-031",
    title: "Improving Factuality in Abstractive Summarization with Contrast Candidate Generation and Selection",
    authors: ["Nan, F.", "Jing, H.", "Prabhakaran, V.", "McKeever, S."],
    abstract: "Abstractive summarization models often generate factually inconsistent summaries. We propose a method to improve factuality by generating and selecting from multiple candidate summaries.",
    tldr: "Improved factuality in abstractive summarization through candidate selection.",
    url: "https://arxiv.org/abs/2211.07066",
    arxivId: "2211.07066",
    publishedAt: "2022-11-14",
    citations: 450,
    categories: ["factuality", "summarization", "language-models"],
  },
  {
    id: "paper-032",
    title: "The Alignment Problem in NLP and How to Approach It",
    authors: ["Gabriel, I.", "Buchner, J.", "Ruggeri, A."],
    abstract: "As NLP systems become more powerful and more widely deployed, ensuring they are aligned with human values and intentions becomes increasingly important.",
    tldr: "Discussed the alignment problem in NLP and potential solutions.",
    url: "https://arxiv.org/abs/2310.08941",
    arxivId: "2310.08941",
    publishedAt: "2023-10-13",
    citations: 250,
    categories: ["alignment", "safety", "language-models"],
  },
  {
    id: "paper-033",
    title: "Towards Understanding Bit-Level Language Models",
    authors: ["Li, K.", "Hopkins, M.", "Bau, D.", "Viégas, F.", "Pfister, H."],
    abstract: "In this work, we investigate what linguistic concepts are represented at the bit-level in language models.",
    tldr: "Analyzed bit-level representations in language models for interpretability.",
    url: "https://arxiv.org/abs/2310.07770",
    arxivId: "2310.07770",
    publishedAt: "2023-10-11",
    citations: 320,
    categories: ["interpretability", "language-models", "nlp"],
  },
  {
    id: "paper-034",
    title: "Breakthrough Results in Multimodal AI at ICCV 2023",
    authors: ["Feng, S.", "Rohrbach, M.", "Tsvetkov, Y."],
    abstract: "This paper summarizes the major breakthroughs in multimodal AI from ICCV 2023, including advances in vision-language models, video understanding, and embodied AI.",
    tldr: "Survey of breakthrough multimodal AI results from ICCV 2023.",
    url: "https://arxiv.org/abs/2310.05500",
    arxivId: "2310.05500",
    publishedAt: "2023-10-09",
    citations: 180,
    categories: ["multimodal", "vision-language", "computer-vision"],
  },
  {
    id: "paper-035",
    title: "How Language Models Encode Time",
    authors: ["Sap, M.", "Rashkin, H.", "Allaway, A.", "Smith, N."],
    abstract: "Understanding temporal reasoning in language models is crucial for applications like question answering and event extraction. We investigate how language models represent and reason about time.",
    tldr: "Studied temporal reasoning and time representations in language models.",
    url: "https://arxiv.org/abs/2310.02903",
    arxivId: "2310.02903",
    publishedAt: "2023-10-04",
    citations: 210,
    categories: ["reasoning", "temporal", "language-models"],
  },
  {
    id: "paper-036",
    title: "Fine-Tuning Language Models for Factuality",
    authors: ["Yang, G.", "Feng, J.", "Hong, Y."],
    abstract: "We investigate fine-tuning approaches to improve the factuality of language model outputs on knowledge-intensive tasks.",
    tldr: "Explored fine-tuning strategies to improve factuality in language models.",
    url: "https://arxiv.org/abs/2309.14540",
    arxivId: "2309.14540",
    publishedAt: "2023-09-25",
    citations: 380,
    categories: ["factuality", "fine-tuning", "language-models"],
  },
  {
    id: "paper-037",
    title: "Measuring Toxicity and Bias in Language Models",
    authors: ["Gehman, S.", "Gururangan, S.", "Sap, M.", "Rashkin, H.", "Dagan, I."],
    abstract: "As language models are deployed in many applications, measuring and mitigating harmful outputs becomes increasingly important.",
    tldr: "Benchmarks and metrics for measuring toxicity and bias in language models.",
    url: "https://arxiv.org/abs/2009.07839",
    arxivId: "2009.07839",
    publishedAt: "2020-09-16",
    citations: 3200,
    categories: ["safety", "bias", "language-models"],
  },
  {
    id: "paper-038",
    title: "Reasoning in Language Models: Planning and Beyond",
    authors: ["Valmeekam, K.", "Goldstein, A.", "Relia, K.", "Kambhampati, S."],
    abstract: "Large language models have shown remarkable capabilities in reasoning and planning tasks. However, we still lack a deep understanding of their capabilities and limitations.",
    tldr: "Analyzed reasoning and planning capabilities in language models.",
    url: "https://arxiv.org/abs/2305.15771",
    arxivId: "2305.15771",
    publishedAt: "2023-05-24",
    citations: 980,
    categories: ["reasoning", "planning", "language-models"],
  },
  {
    id: "paper-039",
    title: "The Role of Scale in Neural Language Models",
    authors: ["Kaplan, J.", "McCandlish, S.", "Henighan, T.", "Brown, T."],
    abstract: "We study the role of scale in language model performance. We find that scale significantly impacts model capabilities across a wide range of tasks.",
    tldr: "Investigated scaling laws and the impact of model size on performance.",
    url: "https://arxiv.org/abs/2001.08361",
    arxivId: "2001.08361",
    publishedAt: "2020-01-22",
    citations: 6500,
    categories: ["scaling", "language-models", "nlp"],
  },
  {
    id: "paper-040",
    title: "Generalization in Neural Network Pruning",
    authors: ["Zhang, M.", "Frankle, J.", "Frankle, B."],
    abstract: "Model pruning is an important technique for reducing the computational cost of neural networks. We study how pruning affects generalization.",
    tldr: "Studied how pruning affects model generalization and efficiency.",
    url: "https://arxiv.org/abs/2104.08378",
    arxivId: "2104.08378",
    publishedAt: "2021-04-16",
    citations: 520,
    categories: ["efficiency", "pruning", "neural-networks"],
  },
  {
    id: "paper-041",
    title: "Vision-Language Models: History, Benchmarks, and Insights",
    authors: ["Wang, Z.", "Wu, Q.", "Zhou, B.", "Yan, J."],
    abstract: "Vision-language models combine image and text understanding. This paper surveys the history of vision-language models and provides comprehensive benchmarks.",
    tldr: "Comprehensive survey of vision-language models with benchmarks.",
    url: "https://arxiv.org/abs/2310.01691",
    arxivId: "2310.01691",
    publishedAt: "2023-10-02",
    citations: 450,
    categories: ["vision-language", "multimodal", "nlp"],
  },
  {
    id: "paper-042",
    title: "The Lottery Ticket Hypothesis in Neural Networks",
    authors: ["Frankle, J.", "Carbin, M."],
    abstract: "The lottery ticket hypothesis suggests that neural networks contain sub-networks that can match the performance of the full network.",
    tldr: "Introduced the lottery ticket hypothesis for efficient neural network training.",
    url: "https://arxiv.org/abs/1903.01611",
    arxivId: "1903.01611",
    publishedAt: "2019-03-04",
    citations: 7200,
    categories: ["pruning", "efficiency", "neural-networks"],
  },
  {
    id: "paper-043",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    authors: ["Radford, A.", "Kim, J.", "Hallacy, C.", "Ramesh, A.", "Goh, G."],
    abstract: "Vision and language understanding have typically been studied separately. We demonstrate that large-scale natural language supervision can be used to train transferable vision models.",
    tldr: "Introduced CLIP, showing how language supervision improves vision models.",
    url: "https://arxiv.org/abs/2103.14030",
    arxivId: "2103.14030",
    publishedAt: "2021-02-26",
    citations: 18000,
    categories: ["clip", "vision-language", "multimodal"],
  },
  {
    id: "paper-044",
    title: "Diffusion Models for Text Generation: A Comprehensive Review",
    authors: ["Zhang, Q.", "Chen, M.", "Metaxas, D."],
    abstract: "Diffusion models have shown impressive results in image generation. We explore their application to text generation.",
    tldr: "Survey of diffusion model approaches for text generation.",
    url: "https://arxiv.org/abs/2305.14018",
    arxivId: "2305.14018",
    publishedAt: "2023-05-23",
    citations: 620,
    categories: ["diffusion", "text-generation", "generative-models"],
  },
  {
    id: "paper-045",
    title: "Knowledge Graphs and Language Models: Complementary Approaches",
    authors: ["Vilares, D.", "Gomez-Rodriguez, C."],
    abstract: "Knowledge graphs and language models are two complementary approaches to knowledge representation. We explore how they can be combined.",
    tldr: "Explored integration of knowledge graphs with language models.",
    url: "https://arxiv.org/abs/2310.06915",
    arxivId: "2310.06915",
    publishedAt: "2023-10-10",
    citations: 340,
    categories: ["knowledge-graphs", "language-models", "nlp"],
  },
  {
    id: "paper-046",
    title: "Neural Architecture Search: Recent Progress and Future Challenges",
    authors: ["Zhou, Y.", "Du, Y.", "Zhou, B.", "Yan, J."],
    abstract: "Neural Architecture Search (NAS) automates the design of neural networks. We survey recent progress and identify future research directions.",
    tldr: "Comprehensive survey of neural architecture search methods.",
    url: "https://arxiv.org/abs/1808.01377",
    arxivId: "1808.01377",
    publishedAt: "2018-08-04",
    citations: 5800,
    categories: ["nas", "architecture-search", "neural-networks"],
  },
  {
    id: "paper-047",
    title: "Adversarial Training for Large Neural Language Models",
    authors: ["Michel, P.", "Levy, O.", "Neubig, G."],
    abstract: "Adversarial training can improve model robustness. We investigate adversarial training approaches for large language models.",
    tldr: "Studied adversarial training for improving language model robustness.",
    url: "https://arxiv.org/abs/2004.04179",
    arxivId: "2004.04179",
    publishedAt: "2020-04-08",
    citations: 1600,
    categories: ["adversarial", "robustness", "language-models"],
  },
  {
    id: "paper-048",
    title: "Few-Shot Learning in Low-Data Regimes",
    authors: ["Wang, Y.", "Yao, Q.", "Kwok, J."],
    abstract: "Few-shot learning enables models to learn from limited examples. We survey recent approaches and applications.",
    tldr: "Survey of few-shot learning methods and their applications.",
    url: "https://arxiv.org/abs/1904.04232",
    arxivId: "1904.04232",
    publishedAt: "2019-04-09",
    citations: 3900,
    categories: ["few-shot-learning", "meta-learning", "language-models"],
  },
  {
    id: "paper-049",
    title: "Continual Learning in Neural Networks: Progress and Challenges",
    authors: ["Zhang, L.", "Yang, M.", "Li, X."],
    abstract: "Continual learning allows models to learn from new data without forgetting previous knowledge. We survey the state of the art.",
    tldr: "Overview of continual learning approaches for neural networks.",
    url: "https://arxiv.org/abs/1810.07414",
    arxivId: "1810.07414",
    publishedAt: "2018-10-18",
    citations: 4100,
    categories: ["continual-learning", "catastrophic-forgetting", "neural-networks"],
  },
  {
    id: "paper-050",
    title: "Graph Neural Networks: A Review of Methods and Applications",
    authors: ["Zhou, J.", "Cui, G.", "Zhang, Z.", "Yang, C.", "Liu, Z."],
    abstract: "Graph neural networks (GNNs) extend deep learning to graph-structured data. We provide a comprehensive review of GNN methods and applications.",
    tldr: "Comprehensive review of graph neural networks and their applications.",
    url: "https://arxiv.org/abs/1812.08434",
    arxivId: "1812.08434",
    publishedAt: "2018-12-20",
    citations: 12000,
    categories: ["gnn", "graph-neural-networks", "neural-networks"],
  },
  {
    id: "paper-051",
    title: "Foundation Models and Their Downstream Applications",
    authors: ["Bommasani, R.", "Hudson, D.", "Adeli, E.", "Altman, R.", "Arora, S."],
    abstract: "Foundation models trained on large-scale diverse data have shown remarkable capabilities. This survey covers their properties and downstream applications.",
    tldr: "Comprehensive study of foundation models and their applications.",
    url: "https://arxiv.org/abs/2108.07258",
    arxivId: "2108.07258",
    publishedAt: "2021-08-16",
    citations: 9500,
    categories: ["foundation-models", "language-models", "multimodal"],
  },
  {
    id: "paper-052",
    title: "Data Quality Matters: The Impact of Training Data on Model Performance",
    authors: ["Rogé, J.", "Vilares, D.", "Oshiro, T."],
    abstract: "The quality of training data significantly impacts model performance. We study how data quality affects different aspects of model behavior.",
    tldr: "Analyzed the impact of training data quality on model performance.",
    url: "https://arxiv.org/abs/2310.07234",
    arxivId: "2310.07234",
    publishedAt: "2023-10-11",
    citations: 280,
    categories: ["data-quality", "training", "language-models"],
  },
];
