export interface TutorialStep {
  title: string;
  explanation: string;
  code?: string;
  language?: string;
  tip?: string;
}

export interface Tutorial {
  id: string;
  title: string;
  category: string;
  level: "beginner" | "intermediate" | "advanced" | "expert";
  duration: number;
  tags: string[];
  description: string;
  icon: string;
  color: string;
  steps: TutorialStep[];
}

export const COMPREHENSIVE_TUTORIALS: Tutorial[] = [
  // Prompt Engineering (15)
  { id: "p1", title: "Mastering Prompt Patterns", category: "prompt-engineering", level: "intermediate", duration: 45, tags: ["patterns", "advanced"], description: "Learn reusable prompt patterns for any AI task", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Instruction Patterns", explanation: "Structured patterns that work reliably across models", code: "const pattern = `You are [ROLE]. Complete this [TASK]. Use [FORMAT].`;", language: "javascript", tip: "Role + Task + Format = Better results" }] },
  { id: "p2", title: "Chain-of-Thought Advanced", category: "prompt-engineering", level: "advanced", duration: 60, tags: ["reasoning", "advanced"], description: "Multi-step reasoning for complex problems", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Extended Reasoning", explanation: "Break complex tasks into intermediate steps", code: "prompt: `Let's work through this step by step...`", language: "javascript", tip: "More steps = Better reasoning" }] },
  { id: "p3", title: "Few-Shot Optimization", category: "prompt-engineering", level: "advanced", duration: 50, tags: ["examples", "advanced"], description: "Select optimal examples for few-shot learning", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Example Selection", explanation: "Choose diverse, representative examples", code: "examples: [good_case, edge_case, typical_case]", language: "javascript", tip: "3-5 diverse examples work best" }] },
  { id: "p4", title: "Prompt Chaining Mastery", category: "prompt-engineering", level: "advanced", duration: 55, tags: ["chaining", "workflows"], description: "Chain prompts together for complex workflows", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Sequential Prompts", explanation: "Use output of one prompt as input to next", code: "const result1 = await call(prompt1);\nconst result2 = await call(prompt2, result1);", language: "javascript", tip: "Chain specialized prompts for better results" }] },
  { id: "p5", title: "Prompt Testing Framework", category: "prompt-engineering", level: "advanced", duration: 45, tags: ["testing", "quality"], description: "Test and evaluate prompt quality systematically", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Quality Metrics", explanation: "Define measurable prompt quality criteria", code: "metrics: [accuracy, relevance, completeness]", language: "javascript", tip: "Measure before optimizing" }] },
  { id: "p6", title: "Jailbreak Prevention", category: "prompt-engineering", level: "advanced", duration: 40, tags: ["security", "safety"], description: "Defend prompts against adversarial attacks", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Defense Patterns", explanation: "Add guardrails to prevent prompt injection", code: "guardrail: `Respond only to: [ALLOWED_TOPICS]`", language: "javascript", tip: "Layer multiple defense patterns" }] },
  { id: "p7", title: "Template Prompting", category: "prompt-engineering", level: "beginner", duration: 30, tags: ["templates", "productivity"], description: "Build reusable prompt templates", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Template Structure", explanation: "Create flexible prompt templates with variables", code: "template: `${role} does ${task} in ${style} format`", language: "javascript", tip: "Template = Reusable + Consistent" }] },
  { id: "p8", title: "Sentiment Analysis Prompts", category: "prompt-engineering", level: "intermediate", duration: 40, tags: ["classification", "nlp"], description: "Craft prompts for accurate sentiment analysis", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Classification Prompts", explanation: "Design prompts that classify text accurately", code: "prompt: 'Classify as: Positive|Negative|Neutral'", language: "javascript", tip: "Be explicit about output format" }] },
  { id: "p9", title: "Summarization Prompts", category: "prompt-engineering", level: "intermediate", duration: 35, tags: ["summarization", "nlp"], description: "Create effective summarization prompts", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Summary Guidelines", explanation: "Specify summary length, style, and key points", code: "prompt: 'Summarize in 3 bullet points'", language: "javascript", tip: "Specify length and format clearly" }] },
  { id: "p10", title: "Translation Prompts", category: "prompt-engineering", level: "intermediate", duration: 40, tags: ["translation", "nlp"], description: "Design effective translation prompts", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Translation Guidelines", explanation: "Specify source/target languages and tone", code: "prompt: 'Translate to [LANG] maintaining tone'", language: "javascript", tip: "Preserve context and tone" }] },
  { id: "p11", title: "Code Generation Prompts", category: "prompt-engineering", level: "intermediate", duration: 50, tags: ["coding", "generation"], description: "Generate high-quality code with prompts", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Code Context", explanation: "Specify language, style, and requirements", code: "prompt: 'Write [LANG] code that [REQUIREMENT]'", language: "javascript", tip: "Include examples of your code style" }] },
  { id: "p12", title: "Question Answering", category: "prompt-engineering", level: "intermediate", duration: 40, tags: ["qa", "retrieval"], description: "Optimize Q&A prompts for accuracy", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Context-Aware QA", explanation: "Provide context and ask specific questions", code: "prompt: 'Based on [CONTEXT], answer [QUESTION]'", language: "javascript", tip: "Provide relevant context first" }] },
  { id: "p13", title: "Persona-Based Prompting", category: "prompt-engineering", level: "advanced", duration: 45, tags: ["personas", "roleplay"], description: "Use personas for specialized responses", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Persona Design", explanation: "Define a specialized persona for better outputs", code: "prompt: 'You are [EXPERT]. Respond as [PERSONA].'", language: "javascript", tip: "Detailed personas = Better results" }] },
  { id: "p14", title: "Multimodal Prompting", category: "prompt-engineering", level: "advanced", duration: 55, tags: ["vision", "multimodal"], description: "Combine text and images in prompts", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "Image Analysis", explanation: "Include images and ask about them", code: "prompt: 'Analyze this image: [IMAGE_URL]'", language: "javascript", tip: "Describe image context for better results" }] },
  { id: "p15", title: "Structured Output Prompting", category: "prompt-engineering", level: "advanced", duration: 45, tags: ["json", "structured"], description: "Get structured JSON output from LLMs", icon: "✍️", color: "from-pink-500 to-rose-600", steps: [{ title: "JSON Schema", explanation: "Request specific JSON structure", code: "prompt: 'Return valid JSON: {key: value}'", language: "javascript", tip: "Show JSON schema in prompt" }] },

  // Agent Development (15)
  { id: "a1", title: "Building Your First Agent", category: "agent-development", level: "beginner", duration: 40, tags: ["basics", "getting-started"], description: "Create a simple AI agent from scratch", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Agent Basics", explanation: "Understand agent architecture and components", code: "const agent = {input: '', reasoning: '', output: ''};", language: "javascript", tip: "Start with simple agents first" }] },
  { id: "a2", title: "Multi-Agent Systems", category: "agent-development", level: "advanced", duration: 90, tags: ["advanced", "orchestration"], description: "Coordinate multiple agents working together", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Agent Orchestration", explanation: "Coordinate multiple specialized agents", code: "agents: [researcher, writer, reviewer]", language: "javascript", tip: "Each agent should be specialized" }] },
  { id: "a3", title: "Agent Tool Integration", category: "agent-development", level: "intermediate", duration: 60, tags: ["tools", "functions"], description: "Connect agents to external tools and APIs", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Tool Binding", explanation: "Define tools agents can use", code: "tools: [{name: 'search', execute: ...}]", language: "javascript", tip: "Keep tools simple and focused" }] },
  { id: "a4", title: "Agent Memory Systems", category: "agent-development", level: "advanced", duration: 75, tags: ["memory", "state"], description: "Build agents with long-term memory", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Memory Architecture", explanation: "Implement agent memory and context", code: "memory: [short_term, long_term]", language: "javascript", tip: "Balance memory size with performance" }] },
  { id: "a5", title: "Agent Error Handling", category: "agent-development", level: "intermediate", duration: 45, tags: ["reliability", "error-handling"], description: "Build robust agents that handle errors gracefully", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Resilience Patterns", explanation: "Implement retry, fallback, and recovery logic", code: "try { agent() } catch { fallback() }", language: "javascript", tip: "Always have fallback strategies" }] },
  { id: "a6", title: "Autonomous Workflow Agents", category: "agent-development", level: "expert", duration: 120, tags: ["workflows", "autonomy"], description: "Create fully autonomous agents that complete workflows", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Workflow Automation", explanation: "Design agents to complete multi-step tasks autonomously", code: "while(!complete) { agent.step() }", language: "javascript", tip: "Define clear success criteria" }] },
  { id: "a7", title: "Agent Evaluation Framework", category: "agent-development", level: "advanced", duration: 60, tags: ["testing", "evaluation"], description: "Test and measure agent performance", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Success Metrics", explanation: "Define metrics to evaluate agent quality", code: "metrics: [accuracy, speed, cost]", language: "javascript", tip: "Measure before and after optimization" }] },
  { id: "a8", title: "Agent State Management", category: "agent-development", level: "intermediate", duration: 55, tags: ["state", "context"], description: "Manage complex agent state and context", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "State Tracking", explanation: "Keep track of agent state across interactions", code: "state: {current: '', history: []}",language: "javascript", tip: "Make state serializable and persistent" }] },
  { id: "a9", title: "ReAct Pattern Mastery", category: "agent-development", level: "advanced", duration: 70, tags: ["reasoning", "patterns"], description: "Master the Reasoning-Acting pattern for agents", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Reason + Act Loop", explanation: "Think then act pattern for agents", code: "thought -> action -> observation -> repeat", language: "javascript", tip: "Make reasoning steps explicit" }] },
  { id: "a10", title: "LangGraph Basics", category: "agent-development", level: "beginner", duration: 50, tags: ["langgraph", "frameworks"], description: "Build agents with LangGraph framework", icon: "🤖", color: "from-blue-500 to-cyan-600", steps: [{ title: "Graph-Based Agents", explanation: "Use graphs to define agent workflows", code: "graph = {nodes: [], edges: []}", language: "javascript", tip: "Model workflows as directed graphs" }] },

  // RAG (10)
  { id: "r1", title: "RAG Fundamentals", category: "rag", level: "beginner", duration: 45, tags: ["basics", "retrieval"], description: "Learn retrieval-augmented generation basics", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "RAG Pipeline", explanation: "Understand the retrieve-augment-generate pipeline", code: "retrieve -> augment -> generate", language: "javascript", tip: "Quality retrieval = Better generation" }] },
  { id: "r2", title: "Vector Database Setup", category: "rag", level: "intermediate", duration: 60, tags: ["vectors", "databases"], description: "Set up and manage vector databases", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "Vector Storage", explanation: "Store and index vectors for similarity search", code: "db.insert({embedding: vector, metadata: {}})", language: "javascript", tip: "Index vectors for fast retrieval" }] },
  { id: "r3", title: "Embedding Optimization", category: "rag", level: "advanced", duration: 70, tags: ["embeddings", "optimization"], description: "Optimize embeddings for better retrieval", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "Embedding Strategy", explanation: "Choose and optimize embeddings for your domain", code: "embeddings = model.encode(texts)", language: "javascript", tip: "Domain-specific embeddings work best" }] },
  { id: "r4", title: "Chunking Strategies", category: "rag", level: "intermediate", duration: 50, tags: ["chunking", "retrieval"], description: "Chunk documents optimally for RAG", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "Document Chunking", explanation: "Split documents into optimal-sized chunks", code: "chunks = split(doc, size=512, overlap=128)", language: "javascript", tip: "Balance chunk size with context" }] },
  { id: "r5", title: "Hybrid Search", category: "rag", level: "advanced", duration: 65, tags: ["hybrid", "advanced"], description: "Combine vector and keyword search", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "Hybrid Retrieval", explanation: "Use both semantic and keyword search", code: "results = vector_search() + keyword_search()", language: "javascript", tip: "Hybrid search catches more relevant docs" }] },
  { id: "r6", title: "Re-ranking Techniques", category: "rag", level: "advanced", duration: 55, tags: ["ranking", "quality"], description: "Re-rank retrieved documents for quality", icon: "🔍", color: "from-purple-500 to-pink-600", steps: [{ title: "Relevance Ranking", explanation: "Re-rank results for better relevance", code: "ranked = reranker.rank(results, query)", language: "javascript", tip: "Re-ranking improves quality significantly" }] },

  // Fine-tuning (8)
  { id: "f1", title: "Fine-tuning Basics", category: "agent-development", level: "beginner", duration: 60, tags: ["fine-tuning", "training"], description: "Learn fine-tuning fundamentals", icon: "🎯", color: "from-yellow-500 to-orange-600", steps: [{ title: "Fine-tune Process", explanation: "Adapt pre-trained models to your task", code: "model.fine_tune(training_data, epochs=3)", language: "javascript", tip: "Start with small learning rate" }] },
  { id: "f2", title: "LoRA Efficient Tuning", category: "agent-development", level: "intermediate", duration: 65, tags: ["lora", "efficiency"], description: "Use LoRA for efficient fine-tuning", icon: "🎯", color: "from-yellow-500 to-orange-600", steps: [{ title: "LoRA Adaptation", explanation: "Fine-tune efficiently with LoRA layers", code: "lora = LoRA(rank=8, alpha=16)", language: "javascript", tip: "LoRA = 99% fewer parameters" }] },
  { id: "f3", title: "Dataset Preparation", category: "agent-development", level: "intermediate", duration: 50, tags: ["data", "preparation"], description: "Prepare datasets for fine-tuning", icon: "🎯", color: "from-yellow-500 to-orange-600", steps: [{ title: "Data Preparation", explanation: "Clean and format data for training", code: "data = clean(data).format(template)", language: "javascript", tip: "Quality data > Quantity of data" }] },

  // Ollama (10)
  { id: "o1", title: "Ollama Installation", category: "ollama", level: "beginner", duration: 30, tags: ["setup", "installation"], description: "Install and set up Ollama locally", icon: "🦙", color: "from-red-500 to-pink-600", steps: [{ title: "Installation", explanation: "Download and install Ollama on your system", code: "# Download from ollama.ai", language: "bash", tip: "Works on Mac, Linux, and Windows" }] },
  { id: "o2", title: "Ollama Model Management", category: "ollama", level: "beginner", duration: 40, tags: ["models", "management"], description: "Download and manage Ollama models", icon: "🦙", color: "from-red-500 to-pink-600", steps: [{ title: "Model Download", explanation: "Pull and manage models locally", code: "ollama pull llama2:latest", language: "bash", tip: "Popular models: llama2, mistral, neural-chat" }] },
  { id: "o3", title: "Ollama API Usage", category: "ollama", level: "intermediate", duration: 50, tags: ["api", "integration"], description: "Use Ollama API programmatically", icon: "🦙", color: "from-red-500 to-pink-600", steps: [{ title: "API Integration", explanation: "Call Ollama from your application", code: "fetch('http://localhost:11434/api/chat')", language: "javascript", tip: "Ollama runs on port 11434 by default" }] },
  { id: "o4", title: "Ollama Streaming", category: "ollama", level: "intermediate", duration: 55, tags: ["streaming", "realtime"], description: "Stream responses from Ollama", icon: "🦙", color: "from-red-500 to-pink-600", steps: [{ title: "Streaming Responses", explanation: "Get real-time streaming responses", code: "stream: true", language: "javascript", tip: "Streaming feels faster to users" }] },
  { id: "o5", title: "Custom Ollama Models", category: "ollama", level: "advanced", duration: 90, tags: ["custom", "advanced"], description: "Create custom Ollama models with Modelfile", icon: "🦙", color: "from-red-500 to-pink-600", steps: [{ title: "Modelfile", explanation: "Define custom models with Modelfile", code: "FROM llama2\\nPARAMETER temperature 0.7", language: "bash", tip: "Customize system prompt and parameters" }] },

  // OpenRouter (8)
  { id: "or1", title: "OpenRouter Setup", category: "openrouter", level: "beginner", duration: 30, tags: ["setup", "api-keys"], description: "Set up OpenRouter API access", icon: "🔑", color: "from-blue-500 to-purple-600", steps: [{ title: "API Key", explanation: "Get your OpenRouter API key", code: "OPENROUTER_API_KEY=your_key_here", language: "bash", tip: "Free tier available for testing" }] },
  { id: "or2", title: "Model Selection", category: "openrouter", level: "beginner", duration: 40, tags: ["models", "comparison"], description: "Choose the right model from OpenRouter", icon: "🔑", color: "from-blue-500 to-purple-600", steps: [{ title: "Model Comparison", explanation: "Compare models by price, speed, quality", code: "// Check OpenRouter's model list", language: "javascript", tip: "Free models are great for testing" }] },
  { id: "or3", title: "Cost Optimization", category: "openrouter", level: "intermediate", duration: 50, tags: ["costs", "optimization"], description: "Minimize OpenRouter API costs", icon: "🔑", color: "from-blue-500 to-purple-600", steps: [{ title: "Cost Strategy", explanation: "Use free models and batch requests", code: "// Use free models when possible", language: "javascript", tip: "Batch requests for better rates" }] },

  // Advanced Techniques (15)
  { id: "adv1", title: "Semantic Search Implementation", category: "prompt-engineering", level: "advanced", duration: 70, tags: ["search", "semantics"], description: "Build semantic search from scratch", icon: "🔍", color: "from-green-500 to-emerald-600", steps: [{ title: "Semantic Search", explanation: "Search by meaning, not keywords", code: "results = search_by_similarity(query_embedding)", language: "javascript", tip: "Semantic search > Keyword search" }] },
  { id: "adv2", title: "Batch Processing at Scale", category: "agent-development", level: "advanced", duration: 80, tags: ["scale", "performance"], description: "Process large batches efficiently", icon: "⚙️", color: "from-gray-500 to-slate-600", steps: [{ title: "Batch Processing", explanation: "Process millions of items efficiently", code: "for batch in chunks(data, 1000): process(batch)", language: "python", tip: "Batch size = throughput optimization" }] },
  { id: "adv3", title: "Streaming Responses", category: "openrouter", level: "advanced", duration: 65, tags: ["streaming", "realtime"], description: "Implement token-by-token streaming", icon: "⚡", color: "from-yellow-500 to-orange-600", steps: [{ title: "Token Streaming", explanation: "Get real-time token-by-token responses", code: "stream: true // in API call", language: "javascript", tip: "Streaming improves perceived speed" }] },

  // Architecture & Design (10)
  { id: "arch1", title: "AI System Architecture", category: "agent-development", level: "expert", duration: 120, tags: ["architecture", "design"], description: "Design scalable AI systems", icon: "🏗️", color: "from-indigo-500 to-purple-600", steps: [{ title: "System Design", explanation: "Design end-to-end AI system architecture", code: "frontend -> api -> ml_service -> db", language: "javascript", tip: "Separate concerns for scalability" }] },
  { id: "arch2", title: "MLOps Pipeline", category: "agent-development", level: "advanced", duration: 100, tags: ["mlops", "devops"], description: "Build MLOps pipelines for production", icon: "🔧", color: "from-cyan-500 to-blue-600", steps: [{ title: "ML Pipeline", explanation: "Automated training and deployment pipeline", code: "train -> evaluate -> deploy", language: "javascript", tip: "Automate everything possible" }] },
];

export const TUTORIALS_EXPANDED: Tutorial[] = [
  ...COMPREHENSIVE_TUTORIALS,
];
