// 100+ AI Automation Workflows for AIHub
// Organized by category with detailed setup instructions

import {
  Mail, FileText, Globe, Database, Code, GitBranch, Sparkles, Clock,
  Bot, Search, Calendar, MessageSquare, Zap, BarChart3, CreditCard,
  CheckCircle2, AlertCircle, TrendingUp, Video, Image, Mic,
  Briefcase, Users, DollarSign, PieChart, Target, Lock,
  Smartphone, Layout, Lightbulb, GitPullRequest, Shield, Ticket,
  Webhook, Plus, Minus, Eye, Ear, Wrench, Settings, Package, Brain,
  Rocket, Newspaper, Computer
} from "lucide-react";

export interface WorkflowStep {
  id: string;
  title: string;
  type: "trigger" | "action" | "ai" | "condition" | "output";
  description: string;
  icon: React.ElementType;
}

export interface Workflow {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: "simple" | "intermediate" | "complex";
  tools: string[];
  estimatedTime: string;
  steps: WorkflowStep[];
  tags: string[];
  color: string;
  setupGuide?: string;
}

export const WORKFLOWS: Workflow[] = [
  // ===== EMAIL & COMMUNICATION (10 workflows) =====
  {
    id: "email-responder",
    title: "AI Email Responder",
    description: "Automatically draft intelligent email responses using AI. Reads incoming emails, generates context-aware replies.",
    category: "Email & Communication",
    difficulty: "simple",
    tools: ["Gmail", "Claude API", "OpenRouter"],
    estimatedTime: "30 min",
    steps: [
      { id: "1", title: "Email Trigger", type: "trigger", description: "New email received in Gmail", icon: Mail },
      { id: "2", title: "Extract Context", type: "ai", description: "AI extracts key info from email", icon: Bot },
      { id: "3", title: "Generate Reply", type: "ai", description: "Claude drafts a professional response", icon: Sparkles },
      { id: "4", title: "Save as Draft", type: "output", description: "Save to Gmail drafts for review", icon: Mail },
    ],
    tags: ["email", "automation", "business"],
    color: "from-blue-500 to-indigo-600",
    setupGuide: "1. Connect Gmail account\n2. Set up Gmail filter for specific labels\n3. Configure OpenRouter API key\n4. Test with sample emails",
  },
  {
    id: "email-classifier",
    title: "Email Classifier & Router",
    description: "Automatically classify incoming emails by priority, topic, and urgency. Route to appropriate team members.",
    category: "Email & Communication",
    difficulty: "intermediate",
    tools: ["Gmail", "GPT-4", "Slack"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Email Received", type: "trigger", description: "New email arrives", icon: Mail },
      { id: "2", title: "Classify Email", type: "ai", description: "AI classifies by priority (urgent, normal, low)", icon: Bot },
      { id: "3", title: "Route Decision", type: "condition", description: "Route based on category and urgency", icon: GitBranch },
      { id: "4", title: "Assign Labels", type: "action", description: "Add Gmail labels automatically", icon: CheckCircle2 },
      { id: "5", title: "Notify Team", type: "output", description: "Send Slack notification to responsible team", icon: MessageSquare },
    ],
    tags: ["email", "routing", "team-collaboration"],
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "email-newsletter-digest",
    title: "Email Newsletter Digest",
    description: "Convert received emails into a daily newsletter digest. Summarize key points and send to subscribers.",
    category: "Email & Communication",
    difficulty: "simple",
    tools: ["Gmail", "Claude", "Mailchimp"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run at 6 AM every morning", icon: Clock },
      { id: "2", title: "Fetch Emails", type: "action", description: "Get emails from last 24 hours", icon: Mail },
      { id: "3", title: "Summarize", type: "ai", description: "AI creates concise digest", icon: Sparkles },
      { id: "4", title: "Format HTML", type: "action", description: "Format digest as HTML newsletter", icon: Code },
      { id: "5", title: "Send via Mailchimp", type: "output", description: "Send to subscriber list", icon: Globe },
    ],
    tags: ["email", "newsletter", "marketing"],
    color: "from-purple-500 to-pink-600",
  },
  {
    id: "email-reply-composer",
    title: "AI Email Reply Composer",
    description: "Compose replies to specific email senders with personalized tone. Learn from sent emails.",
    category: "Email & Communication",
    difficulty: "intermediate",
    tools: ["Gmail", "GPT-4", "Claude"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Email Received", type: "trigger", description: "New email from VIP list", icon: Mail },
      { id: "2", title: "Analyze Sender History", type: "action", description: "Fetch previous emails with sender", icon: Database },
      { id: "3", title: "Determine Tone", type: "ai", description: "AI matches your communication style", icon: Brain },
      { id: "4", title: "Compose Reply", type: "ai", description: "Generate personalized response", icon: Sparkles },
      { id: "5", title: "Save Draft", type: "output", description: "Save to drafts for review", icon: Mail },
    ],
    tags: ["email", "personalization", "communication"],
    color: "from-pink-500 to-rose-600",
  },
  {
    id: "slack-email-bridge",
    title: "Slack Email Bridge",
    description: "Forward important emails to Slack. Get email notifications without leaving Slack.",
    category: "Email & Communication",
    difficulty: "simple",
    tools: ["Gmail", "Slack"],
    estimatedTime: "20 min",
    steps: [
      { id: "1", title: "Email Trigger", type: "trigger", description: "Email matches filter criteria", icon: Mail },
      { id: "2", title: "Extract Details", type: "action", description: "Get sender, subject, preview", icon: FileText },
      { id: "3", title: "Format Message", type: "action", description: "Create Slack message format", icon: MessageSquare },
      { id: "4", title: "Send to Slack", type: "output", description: "Post to designated channel", icon: Globe },
    ],
    tags: ["email", "slack", "integration"],
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "automated-signatures",
    title: "Automated Email Signatures",
    description: "Automatically add personalized signatures to outgoing emails based on department or role.",
    category: "Email & Communication",
    difficulty: "simple",
    tools: ["Gmail", "Google Apps Script"],
    estimatedTime: "30 min",
    steps: [
      { id: "1", title: "Email Sent", type: "trigger", description: "Email sent from Gmail", icon: Mail },
      { id: "2", title: "Check Signature", type: "condition", description: "Verify if signature needed", icon: CheckCircle2 },
      { id: "3", title: "Get User Role", type: "action", description: "Look up sender role/department", icon: Database },
      { id: "4", title: "Append Signature", type: "action", description: "Add appropriate signature", icon: FileText },
    ],
    tags: ["email", "branding", "automation"],
    color: "from-teal-500 to-cyan-600",
  },

  // ===== CONTENT CREATION (10 workflows) =====
  {
    id: "ai-blog-generator",
    title: "AI Blog Post Generator",
    description: "Transform news articles into SEO-optimized blog posts. Generate title, meta description, and content.",
    category: "Content Creation",
    difficulty: "intermediate",
    tools: ["RSS Feed", "GPT-4", "WordPress"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "News Alert", type: "trigger", description: "New article in RSS feed", icon: Newspaper },
      { id: "2", title: "Check Relevance", type: "ai", description: "AI determines if article-worthy", icon: Brain },
      { id: "3", title: "Write Blog Post", type: "ai", description: "Generate full blog article", icon: Sparkles },
      { id: "4", title: "SEO Optimization", type: "ai", description: "Add keywords and meta tags", icon: Search },
      { id: "5", title: "Publish to WordPress", type: "output", description: "Auto-publish as draft", icon: Globe },
    ],
    tags: ["content", "blogging", "seo"],
    color: "from-orange-500 to-red-600",
  },
  {
    id: "social-media-content",
    title: "Social Media Content Generator",
    description: "Create Twitter, LinkedIn, and TikTok content from blog posts. Adapt tone per platform.",
    category: "Content Creation",
    difficulty: "intermediate",
    tools: ["WordPress", "GPT-4", "Buffer"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Post Published", type: "trigger", description: "New blog post created", icon: FileText },
      { id: "2", title: "Extract Content", type: "action", description: "Get title, summary, link", icon: Code },
      { id: "3", title: "Twitter Version", type: "ai", description: "Create engaging tweet (280 chars)", icon: Sparkles },
      { id: "4", title: "LinkedIn Version", type: "ai", description: "Create professional post", icon: Sparkles },
      { id: "5", title: "Schedule Posts", type: "output", description: "Queue in Buffer for optimal time", icon: Clock },
    ],
    tags: ["social-media", "content", "marketing"],
    color: "from-red-500 to-pink-600",
  },
  {
    id: "youtube-script-generator",
    title: "YouTube Script Generator",
    description: "Generate video scripts from topics or articles. Include hooks, transitions, and CTAs.",
    category: "Content Creation",
    difficulty: "intermediate",
    tools: ["GPT-4", "Claude", "Notion"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Topic Input", type: "trigger", description: "New video topic submitted", icon: Plus },
      { id: "2", title: "Research", type: "action", description: "Search for topic background", icon: Search },
      { id: "3", title: "Generate Script", type: "ai", description: "AI writes engaging video script", icon: Sparkles },
      { id: "4", title: "Add Timestamps", type: "action", description: "Format with section markers", icon: Clock },
      { id: "5", title: "Save to Notion", type: "output", description: "Store in content library", icon: Database },
    ],
    tags: ["video", "content", "youtube"],
    color: "from-red-600 to-orange-600",
  },
  {
    id: "podcast-transcript",
    title: "Podcast Transcript & Show Notes",
    description: "Transform podcast audio into transcripts, timestamps, and show notes with AI summaries.",
    category: "Content Creation",
    difficulty: "complex",
    tools: ["OpenAI Whisper", "GPT-4", "Notion"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Upload Audio", type: "trigger", description: "New podcast episode uploaded", icon: Mic },
      { id: "2", title: "Transcribe", type: "action", description: "Whisper converts audio to text", icon: FileText },
      { id: "3", title: "Add Timestamps", type: "ai", description: "AI adds speaker timestamps", icon: Clock },
      { id: "4", title: "Generate Summary", type: "ai", description: "Create episode summary", icon: Sparkles },
      { id: "5", title: "Create Show Notes", type: "ai", description: "Write SEO-optimized show notes", icon: FileText },
      { id: "6", title: "Publish", type: "output", description: "Save to Notion and Apple Podcasts", icon: Globe },
    ],
    tags: ["podcast", "audio", "transcription"],
    color: "from-purple-500 to-indigo-600",
  },
  {
    id: "image-alt-text",
    title: "AI Image Alt Text Generator",
    description: "Automatically generate descriptive alt text for images for accessibility and SEO.",
    category: "Content Creation",
    difficulty: "simple",
    tools: ["AWS Rekognition", "Claude", "WordPress"],
    estimatedTime: "30 min",
    steps: [
      { id: "1", title: "Image Uploaded", type: "trigger", description: "New image added to media library", icon: Image },
      { id: "2", title: "Analyze Image", type: "action", description: "Detect objects and content", icon: Eye },
      { id: "3", title: "Generate Alt Text", type: "ai", description: "AI creates descriptive alt text", icon: Sparkles },
      { id: "4", title: "Add to Metadata", type: "action", description: "Update image properties", icon: Database },
    ],
    tags: ["accessibility", "seo", "images"],
    color: "from-green-500 to-emerald-600",
  },

  // ===== RESEARCH & INTELLIGENCE (12 workflows) =====
  {
    id: "arxiv-paper-digest",
    title: "ArXiv Paper Digest",
    description: "Daily digest of new AI papers matching your interests. AI-generated summaries and relevance scores.",
    category: "Research & Intelligence",
    difficulty: "intermediate",
    tools: ["arXiv API", "GPT-4", "Email"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run at 8 AM every morning", icon: Clock },
      { id: "2", title: "Fetch Papers", type: "action", description: "Query arXiv for new papers", icon: FileText },
      { id: "3", title: "Relevance Score", type: "ai", description: "AI scores each paper (1-10)", icon: Brain },
      { id: "4", title: "Summarize Top Papers", type: "ai", description: "Generate 5-point summary for top 5", icon: Sparkles },
      { id: "5", title: "Format Digest", type: "action", description: "Create HTML email format", icon: Code },
      { id: "6", title: "Send Email", type: "output", description: "Deliver to inbox", icon: Mail },
    ],
    tags: ["research", "papers", "ai"],
    color: "from-violet-500 to-purple-700",
  },
  {
    id: "competitor-tracking",
    title: "Competitor Intelligence Monitor",
    description: "Track competitor announcements, product launches, and blog posts. Get daily AI-summarized briefings.",
    category: "Research & Intelligence",
    difficulty: "intermediate",
    tools: ["Web Scraper", "GPT-4", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run at 7 AM daily", icon: Clock },
      { id: "2", title: "Web Scrape", type: "action", description: "Fetch competitor websites", icon: Globe },
      { id: "3", title: "Compare Content", type: "condition", description: "Detect new vs old content", icon: GitBranch },
      { id: "4", title: "Analyze Changes", type: "ai", description: "AI summarizes competitive moves", icon: Brain },
      { id: "5", title: "Slack Alert", type: "output", description: "Post to #competitive-intel", icon: MessageSquare },
    ],
    tags: ["competitive-analysis", "intelligence", "monitoring"],
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "market-research",
    title: "Market Research Aggregator",
    description: "Aggregate news, trends, and social sentiment on specific markets or topics.",
    category: "Research & Intelligence",
    difficulty: "complex",
    tools: ["Twitter API", "News API", "GPT-4"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Weekly Trigger", type: "trigger", description: "Run every Friday at 2 PM", icon: Calendar },
      { id: "2", title: "Fetch News", type: "action", description: "Get news articles from News API", icon: Newspaper },
      { id: "3", title: "Fetch Tweets", type: "action", description: "Search Twitter for keywords", icon: MessageSquare },
      { id: "4", title: "Sentiment Analysis", type: "ai", description: "Analyze sentiment of mentions", icon: Brain },
      { id: "5", title: "Trend Analysis", type: "ai", description: "AI identifies emerging trends", icon: TrendingUp },
      { id: "6", title: "Generate Report", type: "ai", description: "Create market research report", icon: FileText },
    ],
    tags: ["research", "market-analysis", "trends"],
    color: "from-indigo-500 to-blue-700",
  },
  {
    id: "patent-monitoring",
    title: "Patent Application Monitor",
    description: "Monitor patent filings in your industry. Get alerts for competitors' patents.",
    category: "Research & Intelligence",
    difficulty: "complex",
    tools: ["USPTO API", "GPT-4", "Email"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Check USPTO daily", icon: Clock },
      { id: "2", title: "Search Patents", type: "action", description: "Query recent patent filings", icon: Search },
      { id: "3", title: "Match Keywords", type: "condition", description: "Find relevant keywords", icon: Sparkles },
      { id: "4", title: "Summarize Patent", type: "ai", description: "AI explains patent in plain English", icon: Brain },
      { id: "5", title: "Send Alert", type: "output", description: "Email to patent team", icon: Mail },
    ],
    tags: ["patents", "monitoring", "ip"],
    color: "from-blue-500 to-cyan-600",
  },
  {
    id: "sentiment-analysis",
    title: "Social Sentiment Analysis",
    description: "Real-time sentiment analysis of social media mentions about your brand or topic.",
    category: "Research & Intelligence",
    difficulty: "intermediate",
    tools: ["Twitter API", "GPT-4", "Slack"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Real-time Trigger", type: "trigger", description: "New tweet matches keywords", icon: MessageSquare },
      { id: "2", title: "Fetch Tweet", type: "action", description: "Get full tweet and context", icon: Globe },
      { id: "3", title: "Sentiment Score", type: "ai", description: "Analyze sentiment (positive/negative)", icon: Brain },
      { id: "4", title: "Track Metrics", type: "action", description: "Log sentiment to database", icon: Database },
      { id: "5", title: "Alert on Negative", type: "condition", description: "Flag if sentiment very negative", icon: AlertCircle },
      { id: "6", title: "Notify Team", type: "output", description: "Send Slack alert to social team", icon: MessageSquare },
    ],
    tags: ["sentiment", "social-media", "monitoring"],
    color: "from-pink-500 to-rose-600",
  },
  {
    id: "trend-detection",
    title: "Trend Detection Engine",
    description: "Automatically detect emerging trends in your industry using AI analysis.",
    category: "Research & Intelligence",
    difficulty: "complex",
    tools: ["Hacker News API", "Google Trends", "GPT-4"],
    estimatedTime: "2.5 hours",
    steps: [
      { id: "1", title: "Hourly Trigger", type: "trigger", description: "Run every hour", icon: Clock },
      { id: "2", title: "Fetch Trending", type: "action", description: "Get trending topics from multiple sources", icon: TrendingUp },
      { id: "3", title: "Analyze Trends", type: "ai", description: "AI identifies emerging patterns", icon: Brain },
      { id: "4", title: "Compare History", type: "action", description: "Compare with historical trends", icon: Database },
      { id: "5", title: "Score Novelty", type: "ai", description: "Rate how novel each trend is", icon: Sparkles },
      { id: "6", title: "Report Top Trends", type: "output", description: "Send Slack summary", icon: MessageSquare },
    ],
    tags: ["trends", "analysis", "innovation"],
    color: "from-cyan-500 to-blue-600",
  },

  // ===== DEVELOPER TOOLS (10 workflows) =====
  {
    id: "code-review-bot",
    title: "AI Code Review Bot",
    description: "Automatically review pull requests with AI. Check for bugs, security, and code quality.",
    category: "Developer Tools",
    difficulty: "complex",
    tools: ["GitHub API", "GPT-4", "Slack"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "PR Created", type: "trigger", description: "New PR opened on GitHub", icon: GitBranch },
      { id: "2", title: "Fetch Diff", type: "action", description: "Get changed files and code", icon: Code },
      { id: "3", title: "Check Security", type: "ai", description: "AI scans for security issues", icon: Shield },
      { id: "4", title: "Check Quality", type: "ai", description: "AI reviews code quality", icon: CheckCircle2 },
      { id: "5", title: "Generate Review", type: "ai", description: "AI writes detailed review comments", icon: Sparkles },
      { id: "6", title: "Post Comments", type: "output", description: "Add inline PR comments", icon: MessageSquare },
    ],
    tags: ["github", "code-review", "quality"],
    color: "from-gray-700 to-slate-800",
  },
  {
    id: "bug-triage",
    title: "Automatic Bug Triage",
    description: "Automatically categorize and prioritize GitHub issues. Assign to team members.",
    category: "Developer Tools",
    difficulty: "intermediate",
    tools: ["GitHub API", "Claude", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Issue Opened", type: "trigger", description: "New GitHub issue created", icon: AlertCircle },
      { id: "2", title: "Analyze Issue", type: "ai", description: "AI categorizes issue type", icon: Brain },
      { id: "3", title: "Determine Priority", type: "ai", description: "AI sets priority level", icon: Zap },
      { id: "4", title: "Suggest Labels", type: "ai", description: "AI recommends GitHub labels", icon: Sparkles },
      { id: "5", title: "Assign Owner", type: "action", description: "Assign to team member", icon: Users },
      { id: "6", title: "Notify Team", type: "output", description: "Send Slack notification", icon: MessageSquare },
    ],
    tags: ["github", "issue-management", "triage"],
    color: "from-slate-600 to-stone-800",
  },
  {
    id: "changelog-generator",
    title: "Automated Changelog Generator",
    description: "Generate changelogs from commit messages and merged PRs. Format for releases.",
    category: "Developer Tools",
    difficulty: "intermediate",
    tools: ["GitHub API", "GPT-4", "Markdown"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Release Trigger", type: "trigger", description: "Tag pushed to release branch", icon: GitBranch },
      { id: "2", title: "Fetch Commits", type: "action", description: "Get commits since last release", icon: Code },
      { id: "3", title: "Fetch PRs", type: "action", description: "Get merged PRs", icon: GitPullRequest },
      { id: "4", title: "Categorize Changes", type: "ai", description: "Group as features, fixes, breaking", icon: Brain },
      { id: "5", title: "Write Descriptions", type: "ai", description: "Generate user-friendly descriptions", icon: Sparkles },
      { id: "6", title: "Format Markdown", type: "action", description: "Create release notes markdown", icon: FileText },
    ],
    tags: ["github", "releases", "documentation"],
    color: "from-green-700 to-emerald-800",
  },
  {
    id: "deployment-automation",
    title: "Smart Deployment Automation",
    description: "Automate deployments based on tests passing. Include safety checks and rollback.",
    category: "Developer Tools",
    difficulty: "complex",
    tools: ["GitHub Actions", "Docker", "AWS"],
    estimatedTime: "3 hours",
    steps: [
      { id: "1", title: "Tests Pass", type: "trigger", description: "CI/CD tests all pass", icon: CheckCircle2 },
      { id: "2", title: "Build Docker", type: "action", description: "Build Docker container", icon: Package },
      { id: "3", title: "Run Security", type: "action", description: "Run security scan", icon: Shield },
      { id: "4", title: "Deploy Staging", type: "action", description: "Deploy to staging environment", icon: Rocket },
      { id: "5", title: "Run Tests", type: "action", description: "Run integration tests", icon: CheckCircle2 },
      { id: "6", title: "Deploy Prod", type: "output", description: "Deploy to production", icon: Globe },
    ],
    tags: ["deployment", "devops", "automation"],
    color: "from-orange-700 to-red-800",
  },
  {
    id: "dependency-updates",
    title: "Automated Dependency Updates",
    description: "Monitor and update dependencies. Create PRs with updates, run tests.",
    category: "Developer Tools",
    difficulty: "intermediate",
    tools: ["Dependabot", "GitHub", "NPM"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Weekly Check", type: "trigger", description: "Check for new versions", icon: Clock },
      { id: "2", title: "Scan Dependencies", type: "action", description: "Check npm/pip for updates", icon: Search },
      { id: "3", title: "Create Branch", type: "action", description: "Create branch for updates", icon: GitBranch },
      { id: "4", title: "Update Files", type: "action", description: "Update package.json/requirements", icon: Code },
      { id: "5", title: "Create PR", type: "action", description: "Create PR with changelog", icon: GitPullRequest },
      { id: "6", title: "Auto-merge Safe", type: "action", description: "Auto-merge if all tests pass", icon: CheckCircle2 },
    ],
    tags: ["dependencies", "updates", "security"],
    color: "from-blue-700 to-cyan-800",
  },
  {
    id: "performance-monitoring",
    title: "Performance Monitoring Alert",
    description: "Monitor website/API performance. Alert team when metrics degrade.",
    category: "Developer Tools",
    difficulty: "intermediate",
    tools: ["Datadog", "New Relic", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Real-time Monitor", type: "trigger", description: "Monitor performance metrics", icon: TrendingUp },
      { id: "2", title: "Check Thresholds", type: "condition", description: "Compare against baselines", icon: GitBranch },
      { id: "3", title: "Analyze Cause", type: "ai", description: "AI identifies likely cause", icon: Brain },
      { id: "4", title: "Generate Alert", type: "action", description: "Create alert with context", icon: AlertCircle },
      { id: "5", title: "Notify Team", type: "output", description: "Send Slack alert to devops", icon: MessageSquare },
    ],
    tags: ["monitoring", "performance", "devops"],
    color: "from-purple-700 to-indigo-800",
  },

  // ===== BUSINESS & SALES (10 workflows) =====
  {
    id: "lead-scoring",
    title: "AI Lead Scoring Engine",
    description: "Automatically score leads based on engagement and fit. Prioritize for sales team.",
    category: "Business & Sales",
    difficulty: "intermediate",
    tools: ["CRM", "GPT-4", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "New Lead", type: "trigger", description: "New contact added to CRM", icon: Plus },
      { id: "2", title: "Extract Data", type: "action", description: "Get company info and engagement", icon: Database },
      { id: "3", title: "Score Lead", type: "ai", description: "AI calculates lead quality score", icon: Brain },
      { id: "4", title: "Compare Ideal", type: "ai", description: "Compare against ideal customer profile", icon: Target },
      { id: "5", title: "Update CRM", type: "action", description: "Add score and tags", icon: Database },
      { id: "6", title: "Alert Sales", type: "output", description: "Notify sales of high-priority leads", icon: MessageSquare },
    ],
    tags: ["sales", "leads", "crm"],
    color: "from-green-600 to-emerald-700",
  },
  {
    id: "sales-email-follow-up",
    title: "Intelligent Sales Follow-up",
    description: "Automatically send personalized follow-up emails to prospects. Track engagement.",
    category: "Business & Sales",
    difficulty: "intermediate",
    tools: ["CRM", "Email", "Claude"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "No Response", type: "trigger", description: "3 days since last email, no reply", icon: Clock },
      { id: "2", title: "Get Context", type: "action", description: "Fetch previous email and prospect info", icon: Database },
      { id: "3", title: "Compose Follow-up", type: "ai", description: "AI writes personalized follow-up", icon: Sparkles },
      { id: "4", title: "Add Value", type: "ai", description: "Include relevant content/resource", icon: Plus },
      { id: "5", title: "Send Email", type: "output", description: "Send from your email", icon: Mail },
      { id: "6", title: "Log Activity", type: "action", description: "Update CRM with follow-up", icon: CheckCircle2 },
    ],
    tags: ["sales", "email", "crm"],
    color: "from-blue-600 to-indigo-700",
  },
  {
    id: "meeting-summary",
    title: "Meeting Summary & Action Items",
    description: "Automatically transcribe meetings, generate summaries, and extract action items.",
    category: "Business & Sales",
    difficulty: "intermediate",
    tools: ["Zoom", "Whisper", "GPT-4"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Meeting Ends", type: "trigger", description: "Zoom meeting ends", icon: Calendar },
      { id: "2", title: "Get Recording", type: "action", description: "Download recording", icon: Video },
      { id: "3", title: "Transcribe", type: "action", description: "Whisper transcribes audio", icon: FileText },
      { id: "4", title: "Generate Summary", type: "ai", description: "AI creates meeting summary", icon: Sparkles },
      { id: "5", title: "Extract Actions", type: "ai", description: "AI identifies action items", icon: Zap },
      { id: "6", title: "Send Summary", type: "output", description: "Email summary to attendees", icon: Mail },
    ],
    tags: ["meetings", "productivity", "transcription"],
    color: "from-purple-600 to-pink-700",
  },
  {
    id: "contract-review",
    title: "AI Contract Review",
    description: "Automatically review contracts for risks, compliance, and key terms.",
    category: "Business & Sales",
    difficulty: "complex",
    tools: ["Document Upload", "GPT-4", "Slack"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Document Uploaded", type: "trigger", description: "New contract uploaded", icon: FileText },
      { id: "2", title: "Extract Terms", type: "ai", description: "AI extracts key contract terms", icon: Brain },
      { id: "3", title: "Check Risks", type: "ai", description: "AI identifies risk clauses", icon: AlertCircle },
      { id: "4", title: "Compliance Check", type: "ai", description: "Check against company policy", icon: Shield },
      { id: "5", title: "Generate Report", type: "ai", description: "Create review report", icon: FileText },
      { id: "6", title: "Notify Legal", type: "output", description: "Send to legal team for review", icon: MessageSquare },
    ],
    tags: ["legal", "contracts", "compliance"],
    color: "from-red-600 to-orange-700",
  },
  {
    id: "invoice-processing",
    title: "Automated Invoice Processing",
    description: "Extract data from invoices, validate, and match to orders automatically.",
    category: "Business & Sales",
    difficulty: "intermediate",
    tools: ["Document AI", "GPT-4", "Accounting Software"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Invoice Received", type: "trigger", description: "Email with invoice attachment", icon: Mail },
      { id: "2", title: "Extract Data", type: "ai", description: "AI extracts invoice details", icon: Brain },
      { id: "3", title: "Validate Data", type: "condition", description: "Check for required fields", icon: CheckCircle2 },
      { id: "4", title: "Match PO", type: "action", description: "Match to purchase order", icon: Database },
      { id: "5", title: "Post to Accounting", type: "action", description: "Create entry in accounting system", icon: CreditCard },
      { id: "6", title: "Mark Complete", type: "output", description: "Log as processed", icon: CheckCircle2 },
    ],
    tags: ["accounting", "invoices", "automation"],
    color: "from-green-600 to-teal-700",
  },
  {
    id: "customer-onboarding",
    title: "Customer Onboarding Automation",
    description: "Automate customer onboarding with welcome emails, guides, and progress tracking.",
    category: "Business & Sales",
    difficulty: "intermediate",
    tools: ["CRM", "Email", "Notion"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Customer Created", type: "trigger", description: "New customer in CRM", icon: Plus },
      { id: "2", title: "Send Welcome", type: "action", description: "Send welcome email", icon: Mail },
      { id: "3", title: "Create Checklist", type: "action", description: "Create onboarding checklist", icon: CheckCircle2 },
      { id: "4", title: "Share Resources", type: "action", description: "Share docs and guides", icon: FileText },
      { id: "5", title: "Schedule Call", type: "action", description: "Schedule onboarding call", icon: Calendar },
      { id: "6", title: "Track Progress", type: "output", description: "Monitor checklist completion", icon: TrendingUp },
    ],
    tags: ["customer-success", "onboarding", "automation"],
    color: "from-indigo-600 to-blue-700",
  },
  {
    id: "pricing-optimizer",
    title: "Dynamic Pricing Optimizer",
    description: "Use AI to optimize pricing based on demand, competition, and customer segments.",
    category: "Business & Sales",
    difficulty: "complex",
    tools: ["GPT-4", "Database", "E-commerce Platform"],
    estimatedTime: "2.5 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run every morning", icon: Clock },
      { id: "2", title: "Analyze Demand", type: "ai", description: "AI analyzes sales demand", icon: Brain },
      { id: "3", title: "Check Competition", type: "ai", description: "AI monitors competitor pricing", icon: Target },
      { id: "4", title: "Calculate Optimal", type: "ai", description: "AI calculates optimal prices", icon: DollarSign },
      { id: "5", title: "Update Pricing", type: "action", description: "Update prices in system", icon: CreditCard },
      { id: "6", title: "Report Changes", type: "output", description: "Send pricing report", icon: BarChart3 },
    ],
    tags: ["pricing", "revenue", "optimization"],
    color: "from-yellow-600 to-orange-700",
  },

  // ===== HUMAN RESOURCES (8 workflows) =====
  {
    id: "resume-screening",
    title: "AI Resume Screening",
    description: "Automatically screen resumes against job requirements. Rank candidates.",
    category: "Human Resources",
    difficulty: "intermediate",
    tools: ["Email", "GPT-4", "ATS"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Resume Received", type: "trigger", description: "New resume email received", icon: Mail },
      { id: "2", title: "Extract Resume", type: "action", description: "Parse resume from attachment", icon: FileText },
      { id: "3", title: "Analyze Skills", type: "ai", description: "AI extracts skills and experience", icon: Brain },
      { id: "4", title: "Score Against JD", type: "ai", description: "AI scores against job description", icon: Target },
      { id: "5", title: "Update ATS", type: "action", description: "Add candidate with score", icon: Database },
      { id: "6", title: "Notify Recruiter", type: "output", description: "Alert recruiter if good match", icon: MessageSquare },
    ],
    tags: ["hr", "recruiting", "automation"],
    color: "from-blue-600 to-purple-700",
  },
  {
    id: "interview-scheduling",
    title: "Smart Interview Scheduling",
    description: "Automatically propose interview times based on candidate and interviewer calendars.",
    category: "Human Resources",
    difficulty: "intermediate",
    tools: ["Calendar API", "Email", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Candidate Approved", type: "trigger", description: "Candidate approved for interview", icon: CheckCircle2 },
      { id: "2", title: "Check Calendars", type: "action", description: "Fetch candidate and interviewer calendars", icon: Calendar },
      { id: "3", title: "Find Best Times", type: "ai", description: "AI finds optimal meeting times", icon: Brain },
      { id: "4", title: "Propose Options", type: "action", description: "Send time options to candidate", icon: Mail },
      { id: "5", title: "Confirm & Calendar", type: "action", description: "Add to calendars when confirmed", icon: Calendar },
      { id: "6", title: "Send Reminders", type: "output", description: "Send reminders before interview", icon: Clock },
    ],
    tags: ["hr", "scheduling", "interviewing"],
    color: "from-cyan-600 to-blue-700",
  },
  {
    id: "employee-feedback",
    title: "Anonymous Employee Feedback",
    description: "Collect anonymous feedback, analyze sentiment, identify issues for action.",
    category: "Human Resources",
    difficulty: "intermediate",
    tools: ["Google Forms", "Claude", "Slack"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Weekly Survey", type: "trigger", description: "Send survey every Friday", icon: Calendar },
      { id: "2", title: "Collect Responses", type: "action", description: "Collect feedback responses", icon: MessageSquare },
      { id: "3", title: "Analyze Sentiment", type: "ai", description: "AI analyzes feedback sentiment", icon: Brain },
      { id: "4", title: "Identify Themes", type: "ai", description: "AI groups by theme/issue", icon: Sparkles },
      { id: "5", title: "Generate Report", type: "ai", description: "AI creates executive summary", icon: FileText },
      { id: "6", title: "Alert Leaders", type: "output", description: "Send report to leadership", icon: Users },
    ],
    tags: ["hr", "feedback", "culture"],
    color: "from-purple-600 to-pink-700",
  },
  {
    id: "expense-approval",
    title: "AI Expense Approval",
    description: "Automatically approve expenses under policy. Flag exceptions for review.",
    category: "Human Resources",
    difficulty: "simple",
    tools: ["Expense App", "Claude", "Email"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Expense Submitted", type: "trigger", description: "New expense report submitted", icon: CreditCard },
      { id: "2", title: "Extract Data", type: "action", description: "Get amount, category, description", icon: Database },
      { id: "3", title: "Check Policy", type: "condition", description: "Verify against company policy", icon: Shield },
      { id: "4", title: "Auto-approve", type: "condition", description: "If compliant, auto-approve", icon: CheckCircle2 },
      { id: "5", title: "Flag Issues", type: "ai", description: "If issues, flag for review", icon: AlertCircle },
      { id: "6", title: "Notify", type: "output", description: "Notify employee of status", icon: Mail },
    ],
    tags: ["hr", "expenses", "approval"],
    color: "from-green-600 to-emerald-700",
  },
  {
    id: "onboarding-hr",
    title: "New Hire Onboarding",
    description: "Automate employee onboarding: send paperwork, set up accounts, schedule training.",
    category: "Human Resources",
    difficulty: "intermediate",
    tools: ["HRIS", "Email", "Slack"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Hire Date Set", type: "trigger", description: "New employee start date set", icon: Calendar },
      { id: "2", title: "Send Paperwork", type: "action", description: "Send I-9, tax forms via email", icon: FileText },
      { id: "3", title: "Request Setup", type: "action", description: "Request IT account setup", icon: Computer },
      { id: "4", title: "Schedule Training", type: "action", description: "Schedule training sessions", icon: Calendar },
      { id: "5", title: "Notify Team", type: "action", description: "Notify team of new hire", icon: Users },
      { id: "6", title: "Create Checklist", type: "output", description: "Create onboarding checklist", icon: CheckCircle2 },
    ],
    tags: ["hr", "onboarding", "automation"],
    color: "from-indigo-600 to-purple-700",
  },
  {
    id: "performance-review",
    title: "Performance Review Automation",
    description: "Gather data for performance reviews from multiple sources. Generate summaries.",
    category: "Human Resources",
    difficulty: "complex",
    tools: ["Database", "Email", "Claude"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Review Period", type: "trigger", description: "Review cycle initiated", icon: Calendar },
      { id: "2", title: "Collect Feedback", type: "action", description: "Send peer feedback surveys", icon: MessageSquare },
      { id: "3", title: "Gather Metrics", type: "action", description: "Get performance metrics from systems", icon: Database },
      { id: "4", title: "Analyze Data", type: "ai", description: "AI analyzes feedback and metrics", icon: Brain },
      { id: "5", title: "Generate Summary", type: "ai", description: "AI creates review summary", icon: Sparkles },
      { id: "6", title: "Share with Manager", type: "output", description: "Send to manager for final review", icon: Mail },
    ],
    tags: ["hr", "reviews", "performance"],
    color: "from-yellow-600 to-orange-700",
  },

  // ===== CUSTOMER SUCCESS (10 workflows) =====
  {
    id: "support-ticket-routing",
    title: "Smart Support Ticket Routing",
    description: "Automatically categorize and route support tickets to right team members.",
    category: "Customer Success",
    difficulty: "simple",
    tools: ["Help Desk", "Claude", "Slack"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Ticket Created", type: "trigger", description: "New support ticket submitted", icon: Ticket },
      { id: "2", title: "Extract Issue", type: "action", description: "Get ticket title and description", icon: FileText },
      { id: "3", title: "Categorize", type: "ai", description: "AI categorizes issue type", icon: Brain },
      { id: "4", title: "Route Team", type: "ai", description: "AI determines which team handles", icon: GitBranch },
      { id: "5", title: "Assign Agent", type: "action", description: "Assign to available agent", icon: Users },
      { id: "6", title: "Notify Team", type: "output", description: "Slack alert to team", icon: MessageSquare },
    ],
    tags: ["customer-success", "support", "routing"],
    color: "from-green-600 to-teal-700",
  },
  {
    id: "churn-prediction",
    title: "Customer Churn Prediction",
    description: "Predict which customers are at risk of churning. Trigger retention campaigns.",
    category: "Customer Success",
    difficulty: "complex",
    tools: ["Database", "GPT-4", "CRM"],
    estimatedTime: "2.5 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run daily churn analysis", icon: Clock },
      { id: "2", title: "Gather Data", type: "action", description: "Collect customer usage and engagement data", icon: Database },
      { id: "3", title: "Predict Churn", type: "ai", description: "AI predicts churn probability", icon: Brain },
      { id: "4", title: "Segment Customers", type: "ai", description: "AI identifies at-risk segments", icon: Target },
      { id: "5", title: "Trigger Campaign", type: "action", description: "Create retention email campaign", icon: Mail },
      { id: "6", title: "Track Results", type: "output", description: "Monitor retention metrics", icon: TrendingUp },
    ],
    tags: ["customer-success", "retention", "analytics"],
    color: "from-red-600 to-pink-700",
  },
  {
    id: "feedback-collection",
    title: "Automated Feedback Collection",
    description: "Send targeted feedback surveys to customers. Analyze results for insights.",
    category: "Customer Success",
    difficulty: "simple",
    tools: ["Email", "Forms", "Claude"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Event Trigger", type: "trigger", description: "Customer completes action (e.g., purchase)", icon: CheckCircle2 },
      { id: "2", title: "Send Survey", type: "action", description: "Send feedback survey email", icon: Mail },
      { id: "3", title: "Collect Responses", type: "action", description: "Collect survey responses", icon: MessageSquare },
      { id: "4", title: "Analyze Feedback", type: "ai", description: "AI analyzes sentiment and themes", icon: Brain },
      { id: "5", title: "Update CRM", type: "action", description: "Store feedback in CRM", icon: Database },
      { id: "6", title: "Flag Issues", type: "output", description: "Alert team if negative feedback", icon: AlertCircle },
    ],
    tags: ["customer-success", "feedback", "analytics"],
    color: "from-blue-600 to-cyan-700",
  },
  {
    id: "product-tutorial",
    title: "Personalized Product Tutorial",
    description: "Send personalized product tutorials based on feature adoption and user behavior.",
    category: "Customer Success",
    difficulty: "intermediate",
    tools: ["Analytics", "Email", "Video"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Monitor Usage", type: "trigger", description: "Track feature usage in app", icon: Eye },
      { id: "2", title: "Identify Gaps", type: "ai", description: "AI finds unused features", icon: Brain },
      { id: "3", title: "Select Tutorial", type: "ai", description: "AI chooses relevant tutorial", icon: Sparkles },
      { id: "4", title: "Send Email", type: "action", description: "Email tutorial link to user", icon: Mail },
      { id: "5", title: "Track Engagement", type: "action", description: "Track if user watched", icon: Eye },
      { id: "6", title: "Follow-up", type: "output", description: "Send follow-up based on engagement", icon: MessageSquare },
    ],
    tags: ["customer-success", "education", "onboarding"],
    color: "from-purple-600 to-indigo-700",
  },
  {
    id: "health-check",
    title: "Customer Health Score",
    description: "Calculate customer health score based on usage, support tickets, and sentiment.",
    category: "Customer Success",
    difficulty: "complex",
    tools: ["Database", "Claude", "Dashboard"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Calculate health scores daily", icon: Clock },
      { id: "2", title: "Get Metrics", type: "action", description: "Fetch usage and support data", icon: Database },
      { id: "3", title: "Analyze Activity", type: "ai", description: "AI analyzes engagement trends", icon: Brain },
      { id: "4", title: "Calculate Score", type: "ai", description: "AI calculates health score", icon: BarChart3 },
      { id: "5", title: "Identify Issues", type: "ai", description: "AI flags at-risk customers", icon: AlertCircle },
      { id: "6", title: "Notify CSM", type: "output", description: "Alert account managers", icon: MessageSquare },
    ],
    tags: ["customer-success", "analytics", "monitoring"],
    color: "from-orange-600 to-red-700",
  },
  {
    id: "renewal-reminder",
    title: "Subscription Renewal Reminder",
    description: "Remind customers about upcoming renewals. Offer upgrades or discounts.",
    category: "Customer Success",
    difficulty: "simple",
    tools: ["Billing System", "Email", "CRM"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Check Dates", type: "trigger", description: "Check for renewals 30 days out", icon: Calendar },
      { id: "2", title: "Get Customer", type: "action", description: "Fetch customer and subscription info", icon: Database },
      { id: "3", title: "Create Email", type: "ai", description: "AI creates personalized reminder", icon: Sparkles },
      { id: "4", title: "Include Offer", type: "ai", description: "AI suggests upgrade or discount", icon: Plus },
      { id: "5", title: "Send Email", type: "output", description: "Send renewal reminder", icon: Mail },
      { id: "6", title: "Track Response", type: "output", description: "Monitor email opens and clicks", icon: Eye },
    ],
    tags: ["billing", "renewal", "retention"],
    color: "from-green-600 to-emerald-700",
  },
  {
    id: "support-automation",
    title: "Support Bot - FAQ Answers",
    description: "AI chatbot that answers common support questions. Escalates complex issues.",
    category: "Customer Success",
    difficulty: "intermediate",
    tools: ["Chatbot Platform", "Claude", "Help Desk"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Customer Question", type: "trigger", description: "Customer asks support question", icon: MessageSquare },
      { id: "2", title: "Check FAQ", type: "ai", description: "AI searches FAQ knowledge base", icon: Search },
      { id: "3", title: "Generate Answer", type: "ai", description: "AI generates response", icon: Sparkles },
      { id: "4", title: "Check Complexity", type: "condition", description: "Determine if needs human", icon: GitBranch },
      { id: "5", title: "Auto-respond", type: "output", description: "Send AI response or escalate", icon: MessageSquare },
      { id: "6", title: "Log Interaction", type: "action", description: "Store for training", icon: Database },
    ],
    tags: ["support", "chatbot", "automation"],
    color: "from-cyan-600 to-blue-700",
  },

  // ===== MARKETING (12 workflows) =====
  {
    id: "email-campaign",
    title: "Behavioral Email Campaign",
    description: "Send triggered emails based on user behavior: signup, abandonment, milestones.",
    category: "Marketing",
    difficulty: "intermediate",
    tools: ["Email Platform", "Analytics", "CRM"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Behavior Trigger", type: "trigger", description: "User action detected (abandon, signup)", icon: Zap },
      { id: "2", title: "Check Segment", type: "condition", description: "Verify user in target segment", icon: Target },
      { id: "3", title: "Generate Content", type: "ai", description: "AI personalizes email content", icon: Sparkles },
      { id: "4", title: "Add Dynamic", type: "action", description: "Add dynamic content blocks", icon: Code },
      { id: "5", title: "Send Email", type: "output", description: "Send at optimal time", icon: Mail },
      { id: "6", title: "Track Metrics", type: "output", description: "Track opens, clicks, conversions", icon: TrendingUp },
    ],
    tags: ["marketing", "email", "automation"],
    color: "from-pink-600 to-rose-700",
  },
  {
    id: "content-distribution",
    title: "Multi-Channel Content Distribution",
    description: "Publish blog posts to multiple channels: email, social media, Slack.",
    category: "Marketing",
    difficulty: "intermediate",
    tools: ["WordPress", "Email", "Social Media"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Post Published", type: "trigger", description: "New blog post published", icon: FileText },
      { id: "2", title: "Extract Info", type: "action", description: "Get title, excerpt, tags", icon: Code },
      { id: "3", title: "Create Email", type: "ai", description: "AI creates newsletter version", icon: Sparkles },
      { id: "4", title: "Create Social", type: "ai", description: "AI creates social posts", icon: Sparkles },
      { id: "5", title: "Schedule Posts", type: "action", description: "Schedule across all channels", icon: Calendar },
      { id: "6", title: "Track Performance", type: "output", description: "Monitor engagement across channels", icon: TrendingUp },
    ],
    tags: ["marketing", "content", "distribution"],
    color: "from-indigo-600 to-blue-700",
  },
  {
    id: "webinar-automation",
    title: "Webinar Automation",
    description: "Automate webinar signup, reminders, follow-ups, and recordings.",
    category: "Marketing",
    difficulty: "intermediate",
    tools: ["Zoom", "Email", "CRM"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "User Signup", type: "trigger", description: "User signs up for webinar", icon: Plus },
      { id: "2", title: "Send Confirmation", type: "action", description: "Send confirmation email with link", icon: Mail },
      { id: "3", title: "Schedule Reminders", type: "action", description: "Schedule reminder emails (1h before, 15m before)", icon: Clock },
      { id: "4", title: "Webinar Ends", type: "trigger", description: "Webinar recording available", icon: Video },
      { id: "5", title: "Send Recording", type: "action", description: "Email recording link to attendees", icon: Mail },
      { id: "6", title: "Track Engagement", type: "output", description: "Log attendance and engagement", icon: Eye },
    ],
    tags: ["marketing", "webinar", "events"],
    color: "from-green-600 to-teal-700",
  },
  {
    id: "landing-page-ab-test",
    title: "Landing Page A/B Testing",
    description: "Automatically run A/B tests on landing pages. Report winners.",
    category: "Marketing",
    difficulty: "complex",
    tools: ["Landing Page Tool", "Statistics", "Analytics"],
    estimatedTime: "2 hours",
    steps: [
      { id: "1", title: "Test Trigger", type: "trigger", description: "Weekly A/B test run", icon: Calendar },
      { id: "2", title: "Create Variations", type: "action", description: "Deploy variant pages", icon: Layout },
      { id: "3", title: "Route Traffic", type: "condition", description: "Route 50/50 traffic split", icon: GitBranch },
      { id: "4", title: "Collect Stats", type: "action", description: "Collect conversion data", icon: Database },
      { id: "5", title: "Analyze Results", type: "ai", description: "AI analyzes statistical significance", icon: Brain },
      { id: "6", title: "Report & Deploy", type: "output", description: "Report winner and deploy", icon: TrendingUp },
    ],
    tags: ["marketing", "testing", "optimization"],
    color: "from-purple-600 to-pink-700",
  },
  {
    id: "review-request",
    title: "Automated Review Requests",
    description: "Send review/testimonial requests to happy customers automatically.",
    category: "Marketing",
    difficulty: "simple",
    tools: ["CRM", "Email", "Review Platform"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Happy Signal", type: "trigger", description: "Customer shows happiness signal (high rating, renewal)", icon: Zap },
      { id: "2", title: "Create Email", type: "ai", description: "AI creates personalized review request", icon: Sparkles },
      { id: "3", title: "Add Links", type: "action", description: "Add links to review platforms", icon: Plus },
      { id: "4", title: "Send Email", type: "output", description: "Send review request", icon: Mail },
      { id: "5", title: "Track Submissions", type: "action", description: "Monitor review submissions", icon: Eye },
      { id: "6", title: "Thank Customer", type: "output", description: "Send thank you after review", icon: MessageSquare },
    ],
    tags: ["marketing", "reviews", "reputation"],
    color: "from-orange-600 to-yellow-700",
  },

  // ===== FINANCE (8 workflows) =====
  {
    id: "expense-tracking",
    title: "Expense Categorization",
    description: "Automatically categorize expenses for accounting. Route for approval.",
    category: "Finance",
    difficulty: "simple",
    tools: ["Expense App", "Claude", "Accounting Software"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Expense Logged", type: "trigger", description: "New expense entered", icon: CreditCard },
      { id: "2", title: "Analyze Details", type: "ai", description: "AI categorizes expense", icon: Brain },
      { id: "3", title: "Assign Category", type: "action", description: "Assign to accounting category", icon: Database },
      { id: "4", title: "Flag if Large", type: "condition", description: "Flag if over threshold", icon: AlertCircle },
      { id: "5", title: "Route for Approval", type: "action", description: "Route to approver if needed", icon: Users },
      { id: "6", title: "Post to Accounting", type: "output", description: "Auto-post if under threshold", icon: CreditCard },
    ],
    tags: ["finance", "accounting", "expenses"],
    color: "from-green-600 to-emerald-700",
  },
  {
    id: "budget-monitoring",
    title: "Budget Monitoring & Alerts",
    description: "Monitor departmental spending. Alert when approaching budget limits.",
    category: "Finance",
    difficulty: "intermediate",
    tools: ["Accounting Software", "Database", "Slack"],
    estimatedTime: "1 hour",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Check budgets daily", icon: Clock },
      { id: "2", title: "Calculate Spent", type: "action", description: "Sum department spending", icon: Database },
      { id: "3", title: "Compare Budget", type: "condition", description: "Compare against budget limit", icon: GitBranch },
      { id: "4", title: "Calculate Alert", type: "ai", description: "AI calculates % of budget used", icon: Brain },
      { id: "5", title: "Create Alert", type: "action", description: "Create alert if over 80%", icon: AlertCircle },
      { id: "6", title: "Notify Manager", type: "output", description: "Send Slack alert to manager", icon: MessageSquare },
    ],
    tags: ["finance", "budgeting", "monitoring"],
    color: "from-blue-600 to-cyan-700",
  },
  {
    id: "payment-reminder",
    title: "Payment & Bill Reminders",
    description: "Automatic reminders for bills due and payments to collect.",
    category: "Finance",
    difficulty: "simple",
    tools: ["Accounting Software", "Email", "Calendar"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Check Dates", type: "trigger", description: "Check bills due in 3 days", icon: Calendar },
      { id: "2", title: "Get Invoice", type: "action", description: "Get bill details", icon: FileText },
      { id: "3", title: "Create Reminder", type: "ai", description: "AI creates reminder email", icon: Sparkles },
      { id: "4", title: "Send Reminder", type: "output", description: "Send payment reminder", icon: Mail },
      { id: "5", title: "Track Payment", type: "action", description: "Monitor when paid", icon: Eye },
      { id: "6", title: "Auto-post Receipt", type: "output", description: "Post payment when received", icon: CheckCircle2 },
    ],
    tags: ["finance", "billing", "payments"],
    color: "from-purple-600 to-pink-700",
  },
  {
    id: "tax-preparation",
    title: "Tax Document Organization",
    description: "Automatically collect and organize documents for tax preparation.",
    category: "Finance",
    difficulty: "intermediate",
    tools: ["Cloud Storage", "Database", "Email"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Q1 Trigger", type: "trigger", description: "Tax season reminder", icon: Calendar },
      { id: "2", title: "Gather Documents", type: "action", description: "Collect receipts and records", icon: FileText },
      { id: "3", title: "Organize Files", type: "ai", description: "AI organizes by category", icon: Database },
      { id: "4", title: "Verify Completeness", type: "condition", description: "Check for missing documents", icon: CheckCircle2 },
      { id: "5", title: "Send to Accountant", type: "action", description: "Package and send to CPA", icon: Mail },
      { id: "6", title: "Track Status", type: "output", description: "Track preparation status", icon: Eye },
    ],
    tags: ["finance", "tax", "compliance"],
    color: "from-red-600 to-orange-700",
  },
  {
    id: "revenue-reporting",
    title: "Automated Revenue Reporting",
    description: "Generate weekly/monthly revenue reports with AI insights.",
    category: "Finance",
    difficulty: "intermediate",
    tools: ["Billing System", "Database", "Claude"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Monthly Trigger", type: "trigger", description: "Generate on last day of month", icon: Calendar },
      { id: "2", title: "Query Revenue", type: "action", description: "Get revenue data from billing", icon: Database },
      { id: "3", title: "Calculate Metrics", type: "action", description: "Calculate MRR, growth, churn", icon: BarChart3 },
      { id: "4", title: "Generate Insights", type: "ai", description: "AI generates executive summary", icon: Sparkles },
      { id: "5", title: "Create Dashboard", type: "action", description: "Update revenue dashboard", icon: Layout },
      { id: "6", title: "Send Report", type: "output", description: "Email report to executives", icon: Mail },
    ],
    tags: ["finance", "reporting", "revenue"],
    color: "from-green-600 to-teal-700",
  },

  // ===== SECURITY & COMPLIANCE (8 workflows) =====
  {
    id: "data-backup",
    title: "Automated Daily Backup",
    description: "Daily automated backups of critical data with encryption and verification.",
    category: "Security & Compliance",
    difficulty: "intermediate",
    tools: ["Cloud Storage", "Database", "Encryption"],
    estimatedTime: "1.5 hours",
    steps: [
      { id: "1", title: "Daily Trigger", type: "trigger", description: "Run backup at 2 AM daily", icon: Clock },
      { id: "2", title: "Export Data", type: "action", description: "Export all critical data", icon: Database },
      { id: "3", title: "Encrypt Data", type: "action", description: "Encrypt backup", icon: Lock },
      { id: "4", title: "Upload Storage", type: "action", description: "Upload to secure cloud storage", icon: Globe },
      { id: "5", title: "Verify Integrity", type: "condition", description: "Run integrity check", icon: CheckCircle2 },
      { id: "6", title: "Log Success", type: "output", description: "Log backup completion", icon: FileText },
    ],
    tags: ["security", "backup", "compliance"],
    color: "from-red-600 to-pink-700",
  },
  {
    id: "password-rotation",
    title: "Password Rotation Reminder",
    description: "Remind team to rotate passwords quarterly. Track compliance.",
    category: "Security & Compliance",
    difficulty: "simple",
    tools: ["Password Manager", "Email", "Slack"],
    estimatedTime: "45 min",
    steps: [
      { id: "1", title: "Quarterly Trigger", type: "trigger", description: "Every 90 days", icon: Calendar },
      { id: "2", title: "Notify Team", type: "action", description: "Send password rotation reminder", icon: Mail },
      { id: "3", title: "Share Guidelines", type: "action", description: "Attach password policy", icon: FileText },
      { id: "4", title: "Track Confirmations", type: "action", description: "Collect confirmation from employees", icon: CheckCircle2 },
      { id: "5", title: "Flag Non-compliance", type: "condition", description: "Find who hasn't confirmed", icon: AlertCircle },
      { id: "6", title: "Report to IT", type: "output", description: "Report compliance status", icon: MessageSquare },
    ],
    tags: ["security", "compliance", "passwords"],
    color: "from-orange-600 to-red-700",
  },
  {
    id: "compliance-audit",
    title: "Compliance Audit Trail",
    description: "Automatically log all access and changes. Generate audit reports.",
    category: "Security & Compliance",
    difficulty: "complex",
    tools: ["Database", "Audit Log", "Claude"],
    estimatedTime: "2.5 hours",
    steps: [
      { id: "1", title: "Action Trigger", type: "trigger", description: "Any user action", icon: Zap },
      { id: "2", title: "Log Event", type: "action", description: "Log with timestamp, user, action", icon: Database },
      { id: "3", title: "Store Securely", type: "action", description: "Store in immutable audit log", icon: Lock },
      { id: "4", title: "Generate Report", type: "ai", description: "AI generates monthly report", icon: Sparkles },
      { id: "5", title: "Analyze Anomalies", type: "ai", description: "AI flags suspicious activity", icon: Brain },
      { id: "6", title: "Send Report", type: "output", description: "Email report to compliance team", icon: Mail },
    ],
    tags: ["security", "compliance", "audit"],
    color: "from-blue-600 to-purple-700",
  },
];
