export type Difficulty = "Easy" | "Medium" | "Hard";

export interface Idea {
  id: string;
  title: string;
  category: string;
  emoji: string;
  tagline: string;
  problem: string;
  solution: string;
  revenueModel: string;
  revenuePotential: string;
  difficulty: Difficulty;
  timeToMVP: string;
  techStack: string[];
  features: string[];
  whyNow: string;
  isHot?: boolean;
  isFeatured?: boolean;
  color: string;
  gradient: string;
}

export const CATEGORY_META: Record<string, { color: string; gradient: string; emoji: string }> = {
  Healthcare:      { color: "#ef4444", gradient: "from-red-500/20 to-rose-900/10",    emoji: "🏥" },
  Legal:           { color: "#6366f1", gradient: "from-indigo-500/20 to-blue-900/10", emoji: "⚖️" },
  Education:       { color: "#10b981", gradient: "from-emerald-500/20 to-green-900/10", emoji: "🎓" },
  Finance:         { color: "#f59e0b", gradient: "from-amber-500/20 to-yellow-900/10", emoji: "💰" },
  "Home Services": { color: "#f97316", gradient: "from-orange-500/20 to-amber-900/10", emoji: "🔧" },
  Construction:    { color: "#78716c", gradient: "from-stone-400/20 to-stone-900/10",  emoji: "🏗️" },
  Food:            { color: "#eab308", gradient: "from-yellow-500/20 to-amber-900/10", emoji: "🍽️" },
  Agriculture:     { color: "#84cc16", gradient: "from-lime-500/20 to-green-900/10",  emoji: "🌾" },
  HR:              { color: "#8b5cf6", gradient: "from-violet-500/20 to-purple-900/10", emoji: "👥" },
  "Mental Health": { color: "#ec4899", gradient: "from-pink-500/20 to-rose-900/10",   emoji: "🧠" },
  "Real Estate":   { color: "#14b8a6", gradient: "from-teal-500/20 to-cyan-900/10",   emoji: "🏡" },
  Retail:          { color: "#0ea5e9", gradient: "from-sky-500/20 to-blue-900/10",    emoji: "🛒" },
  "Web Design":    { color: "#a855f7", gradient: "from-purple-500/20 to-violet-900/10", emoji: "🌐" },
  Government:      { color: "#64748b", gradient: "from-slate-500/20 to-slate-900/10", emoji: "🏛️" },
  Logistics:       { color: "#06b6d4", gradient: "from-cyan-500/20 to-sky-900/10",    emoji: "🚚" },
};

export const IDEAS: Idea[] = [
  // ─── HEALTHCARE ───────────────────────────────────────────────
  {
    id: "medical-intake-ai",
    title: "AI Medical Intake Optimizer",
    category: "Healthcare",
    emoji: "🏥",
    tagline: "End the clipboard era. Patients speak, forms fill themselves.",
    problem: "Patients spend 20–40 min filling paper forms. Staff re-enter data manually, causing costly errors. 35% of medical mistakes trace back to intake failures.",
    solution: "Voice-powered intake that listens to the patient, auto-fills EMR forms in real time, detects urgency from tone and symptoms, and routes directly to the right specialist — before the doctor walks in.",
    revenueModel: "SaaS: $299–$2,999/month per clinic. White-label for hospital chains: $50K–$200K/yr.",
    revenuePotential: "$2M–$20M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "OpenAI Whisper", "GPT-4o", "Supabase", "Twilio", "FHIR API"],
    features: [
      "Real-time voice-to-form transcription",
      "Urgency scoring (0–10 scale) from symptom semantics",
      "Automatic specialist routing",
      "Insurance pre-authorization prefill",
      "Patient history cross-reference",
      "HIPAA-compliant encrypted storage",
    ],
    whyNow: "LLMs now understand medical terminology. Voice-first UX removes age/tech barriers. Healthcare is desperate for admin reduction post-COVID staffing crisis.",
    isHot: true,
    isFeatured: true,
    color: "#ef4444",
    gradient: "from-red-500/20 to-rose-900/10",
  },
  {
    id: "hospital-bed-ai",
    title: "Hospital Bed Intelligence System",
    category: "Healthcare",
    emoji: "🛏️",
    tagline: "Predict discharges. Fill beds faster. Save lives in waiting rooms.",
    problem: "Hospitals lose $150B/yr to inefficient bed utilization. Patients wait hours in ERs for beds that are technically available but administratively blocked.",
    solution: "ML model trained on patient vitals, diagnosis codes, and historical discharge patterns to predict each patient's discharge time ±2 hours, enabling real-time bed allocation and transfer coordination.",
    revenueModel: "SaaS per bed: $15–$50/bed/month. A 200-bed hospital = $36K–$120K/yr.",
    revenuePotential: "$5M–$40M ARR",
    difficulty: "Hard",
    timeToMVP: "10–14 weeks",
    techStack: ["Python", "FastAPI", "Next.js", "PostgreSQL", "TensorFlow", "HL7 FHIR"],
    features: [
      "Discharge time prediction (±2 hours accuracy)",
      "Real-time bed allocation map",
      "Transfer coordination alerts",
      "Staff capacity matching",
      "OR scheduling optimization",
      "Dashboard for bed managers",
    ],
    whyNow: "Hospital margins are razor-thin post-pandemic. A 10% improvement in bed utilization pays for the software 10x over.",
    color: "#ef4444",
    gradient: "from-red-500/20 to-rose-900/10",
  },

  // ─── LEGAL ────────────────────────────────────────────────────
  {
    id: "contract-landmine",
    title: "Contract Landmine Detector",
    category: "Legal",
    emoji: "⚖️",
    tagline: "Every clause that can hurt you — highlighted before you sign.",
    problem: "Non-lawyers sign contracts that cost them fortunes. Auto-renewals, indemnification clauses, IP assignment clauses — buried in 40 pages of legalese. One bad clause can cost $100K+.",
    solution: "Paste or upload any contract. AI reads every clause, highlights anything that could cost money, restrict your freedom, or expose you to liability — in plain English with a risk score per section.",
    revenueModel: "Freemium: 3 contracts/month free. Pro: $29/month. Business: $199/month unlimited.",
    revenuePotential: "$1M–$10M ARR",
    difficulty: "Easy",
    timeToMVP: "3–4 weeks",
    techStack: ["Next.js", "GPT-4o", "PDF.js", "Supabase", "Stripe", "Tailwind"],
    features: [
      "Clause-by-clause risk scoring",
      "Plain-English translation of every section",
      "Red-flag auto-highlighting",
      "Comparison against industry standards",
      "Amendment suggestion generator",
      "Negotiation talking points export",
    ],
    whyNow: "GPT-4 can read and reason about legal text at near-lawyer level. Everyone needs this but 90% of people can't afford a lawyer for every contract.",
    isHot: true,
    isFeatured: true,
    color: "#6366f1",
    gradient: "from-indigo-500/20 to-blue-900/10",
  },
  {
    id: "small-claims-copilot",
    title: "Small Claims Court Copilot",
    category: "Legal",
    emoji: "🔨",
    tagline: "You don't need a $400/hr lawyer. You need this.",
    problem: "73% of small claims cases are brought by people without legal representation. Most lose because they don't know procedural rules, how to write arguments, or what evidence matters.",
    solution: "Step-by-step guide that walks non-lawyers through every stage: filing, evidence gathering, argument structure, mock hearings with AI playing judge, and a final document kit — tailored to the user's state.",
    revenueModel: "Per-case: $49–$99 flat fee. Monthly subscription: $19/month for unlimited cases.",
    revenuePotential: "$500K–$5M ARR",
    difficulty: "Medium",
    timeToMVP: "5–6 weeks",
    techStack: ["Next.js", "GPT-4o", "LangChain", "Supabase", "Stripe"],
    features: [
      "State-specific procedural guidance",
      "Evidence checklist generator",
      "Demand letter auto-writer",
      "AI mock-judge practice hearings",
      "Court document kit (print-ready)",
      "Day-of hearing preparation checklist",
    ],
    whyNow: "Access to justice crisis is real. 40M Americans have a legal problem they can't afford to address. LLMs finally make this feasible to build without lawyers on staff.",
    color: "#6366f1",
    gradient: "from-indigo-500/20 to-blue-900/10",
  },

  // ─── EDUCATION ────────────────────────────────────────────────
  {
    id: "student-dna-engine",
    title: "Student Learning DNA Engine",
    category: "Education",
    emoji: "🎓",
    tagline: "Every student gets their own curriculum. Finally.",
    problem: "One teacher, 30 students, 30 different learning speeds and styles. Teachers teach to the average and 50% of students fall behind or get bored. Both groups underperform.",
    solution: "AI that builds a unique learning path for each student based on daily micro-assessments — adjusting difficulty, pacing, format (video/text/quiz/project) every 24 hours. Teachers see a class-wide gap heatmap.",
    revenueModel: "Per-student: $5–$15/month. District licensing: $50K–$500K/yr.",
    revenuePotential: "$3M–$30M ARR",
    difficulty: "Hard",
    timeToMVP: "10–12 weeks",
    techStack: ["Next.js", "Python", "GPT-4o", "PostgreSQL", "Redis", "D3.js"],
    features: [
      "Daily adaptive learning path generation",
      "Multi-format content delivery (video/text/quiz)",
      "Class-wide gap analysis heatmap for teachers",
      "Parent weekly digest (auto-generated)",
      "State curriculum standard alignment",
      "Engagement prediction and intervention alerts",
    ],
    whyNow: "Post-COVID learning loss is a $1T problem. Districts are actively buying EdTech that shows measurable outcomes. AI now makes true personalization affordable.",
    isFeatured: true,
    color: "#10b981",
    gradient: "from-emerald-500/20 to-green-900/10",
  },
  {
    id: "dropout-predictor",
    title: "AI Dropout Early Warning System",
    category: "Education",
    emoji: "🚨",
    tagline: "Save the student 6 months before they disappear.",
    problem: "16% of students drop out of high school. The warning signs — attendance patterns, grade velocity, discipline incidents — are all in school systems but nobody is connecting the dots in time.",
    solution: "ML model ingesting attendance, grades, discipline, lunch status, and family situation changes — predicts dropout risk 90–180 days ahead with specific intervention recommendations per student.",
    revenueModel: "Per-school SaaS: $8K–$25K/year. District-wide: $50K–$300K/year.",
    revenuePotential: "$2M–$15M ARR",
    difficulty: "Hard",
    timeToMVP: "12–16 weeks",
    techStack: ["Python", "FastAPI", "scikit-learn", "Next.js", "PostgreSQL", "Resend"],
    features: [
      "180-day dropout risk score per student",
      "Root cause classification (academic/social/economic)",
      "Automated counselor alert routing",
      "Intervention effectiveness tracking",
      "District-level risk dashboards",
      "FERPA-compliant data handling",
    ],
    whyNow: "School districts pay $10K+ per dropped student in lost funding. Prevention is 10x cheaper than recovery programs. ESSER funds are available for exactly this.",
    color: "#10b981",
    gradient: "from-emerald-500/20 to-green-900/10",
  },

  // ─── FINANCE ──────────────────────────────────────────────────
  {
    id: "tax-receipt-autopilot",
    title: "Tax Receipt Autopilot",
    category: "Finance",
    emoji: "🧾",
    tagline: "Photo it. Forget it. Get the biggest refund of your life.",
    problem: "Self-employed people leave $15B in unclaimed deductions annually because tracking receipts is tedious. Average freelancer misses $6,200/year in deductions.",
    solution: "Point phone at any receipt — AI categorizes, extracts amount, links to IRS deduction category, and stores. At year-end, generates a complete Schedule C with every deduction pre-populated. Sync with any accounting tool.",
    revenueModel: "Annual subscription: $99/year consumer, $299/year business. CPA white-label: $500/month.",
    revenuePotential: "$1M–$8M ARR",
    difficulty: "Easy",
    timeToMVP: "4–5 weeks",
    techStack: ["React Native", "GPT-4o Vision", "Supabase", "Stripe", "Plaid API", "PDF generation"],
    features: [
      "1-second receipt scanning (photo → data)",
      "IRS deduction category mapping",
      "Bank feed import for missed expenses",
      "Annual tax report generation (Schedule C)",
      "Mileage tracking (GPS auto-log)",
      "CPA sharing portal",
    ],
    whyNow: "GPT-4 Vision makes OCR+categorization near-perfect. 73M freelancers in the US alone, all paying more taxes than they should.",
    isHot: true,
    color: "#f59e0b",
    gradient: "from-amber-500/20 to-yellow-900/10",
  },
  {
    id: "cashflow-oracle",
    title: "Small Business Cash Flow Oracle",
    category: "Finance",
    emoji: "🔮",
    tagline: "Know you're running out of money 90 days before it happens.",
    problem: "82% of small businesses fail due to cash flow problems. Most owners don't see it coming until they're already in crisis. By then, it's too late to pivot.",
    solution: "Connect your business bank account. AI learns your revenue cycles, recurring costs, and customer payment patterns — then generates a 90-day rolling cash flow forecast with specific actions: 'Invoice client X now. Delay vendor Y payment by 14 days.'",
    revenueModel: "Monthly SaaS: $49–$199/month. Bookkeeper reseller program.",
    revenuePotential: "$2M–$12M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "Plaid API", "GPT-4o", "Python", "PostgreSQL", "Recharts"],
    features: [
      "Real-time bank feed analysis",
      "90-day rolling forecast",
      "Actionable daily recommendations",
      "Invoice timing optimizer",
      "Expense timing suggestions",
      "Scenario modeling ('what if I hire X')",
    ],
    whyNow: "Open banking (Plaid) makes bank data accessible. LLMs make narrative cash flow insights possible. Every SMB owner desperately wants this.",
    isFeatured: true,
    color: "#f59e0b",
    gradient: "from-amber-500/20 to-yellow-900/10",
  },

  // ─── HOME SERVICES ────────────────────────────────────────────
  {
    id: "pipe-whisperer",
    title: "The Pipe Whisperer",
    category: "Home Services",
    emoji: "🔧",
    tagline: "Describe your leak. Get the fix. Or we send the right plumber.",
    problem: "Homeowners call plumbers for problems they could fix in 10 minutes. Plumbers waste 40% of call time on misdiagnosed jobs. Both sides lose.",
    solution: "Homeowner describes problem or takes a photo. AI diagnoses with 90%+ accuracy using symptom decision trees. Provides step-by-step fix video for DIY. If pro needed, auto-generates a service ticket pre-filled with likely issue, parts needed, and time estimate.",
    revenueModel: "B2B2C: License to plumbing companies ($199/month). Lead generation: $15–$40 per qualified job referral.",
    revenuePotential: "$1M–$6M ARR",
    difficulty: "Easy",
    timeToMVP: "3–5 weeks",
    techStack: ["Next.js", "GPT-4o Vision", "Supabase", "Twilio", "Stripe"],
    features: [
      "Photo + text diagnosis engine",
      "90%+ accuracy symptom classifier",
      "YouTube/video fix library integration",
      "Parts list auto-generator",
      "Service ticket prefiller",
      "Plumber network dispatch",
    ],
    whyNow: "Every homeowner has a smartphone. GPT-4 Vision now understands plumbing imagery. Home services market is $600B with massive inefficiency.",
    color: "#f97316",
    gradient: "from-orange-500/20 to-amber-900/10",
  },
  {
    id: "hvac-predictor",
    title: "HVAC Failure Predictor",
    category: "Home Services",
    emoji: "❄️",
    tagline: "Fix it before it breaks. Never sweat through an August emergency.",
    problem: "HVAC emergency calls cost 3x more than scheduled maintenance. The average emergency replacement costs $5,000–$12,000. 80% of failures are preceded by detectable patterns.",
    solution: "Cheap IoT sensors on HVAC units (temperature, vibration, power draw, runtime cycles) feed an ML model that predicts failure 21–45 days out. Homeowner gets alert with repair vs. replace recommendation and pre-scheduled service slot.",
    revenueModel: "Hardware: $149 sensor kit. SaaS: $19/month monitoring. HVAC partner referral: $75–$200/job.",
    revenuePotential: "$3M–$25M ARR",
    difficulty: "Hard",
    timeToMVP: "12–16 weeks",
    techStack: ["Raspberry Pi / ESP32", "Python", "MQTT", "Next.js", "PostgreSQL", "TensorFlow Lite"],
    features: [
      "Real-time HVAC health scoring",
      "21-45 day failure prediction",
      "Repair vs replace recommendation",
      "Automated HVAC company scheduling",
      "Energy efficiency optimization",
      "Mobile app with alerts",
    ],
    whyNow: "IoT hardware costs have dropped 80% in 5 years. Predictive maintenance is the #1 requested home tech feature. HVAC companies will pay for pre-qualified leads.",
    color: "#f97316",
    gradient: "from-orange-500/20 to-amber-900/10",
  },

  // ─── CONSTRUCTION ─────────────────────────────────────────────
  {
    id: "building-code-watchdog",
    title: "Building Code AI Watchdog",
    category: "Construction",
    emoji: "🏗️",
    tagline: "Catch every violation before concrete is poured.",
    problem: "Contractors fail permit inspections 38% of the time on first submission. Each rejection costs $2,000–$15,000 in delays. Most violations are detectable from the plans before any physical work.",
    solution: "Upload CAD/PDF construction plans. AI cross-references against the relevant local building code, IBC, ADA requirements, and fire codes — outputs a ranked list of violations with exact page references and correction instructions.",
    revenueModel: "Per-plan review: $49–$299. Monthly subscription for contractors: $299–$999/month.",
    revenuePotential: "$2M–$15M ARR",
    difficulty: "Hard",
    timeToMVP: "10–14 weeks",
    techStack: ["Next.js", "Python", "GPT-4o Vision", "PDF processing", "PostgreSQL", "Supabase"],
    features: [
      "Multi-jurisdiction code database",
      "CAD and PDF plan reading",
      "Violation ranking by severity",
      "Correction instruction generator",
      "ADA compliance checker",
      "Permit approval probability score",
    ],
    whyNow: "Construction is a $2T industry running on paper. AI can now read architectural drawings. First-inspection failure rates cost the industry $10B/year.",
    isFeatured: true,
    color: "#78716c",
    gradient: "from-stone-400/20 to-stone-900/10",
  },
  {
    id: "permit-fasttrack",
    title: "Permit Approval Fast-Track AI",
    category: "Construction",
    emoji: "📋",
    tagline: "Guarantee first-time permit approval. Every time.",
    problem: "Permit applications are rejected for minor, fixable reasons that add weeks of delay. Small contractors lose $500–$5,000 per rejection cycle in labor costs.",
    solution: "AI pre-checks the permit application against the specific municipality's requirements, common rejection reasons in that jurisdiction, and previous approval patterns — before the contractor submits. Outputs a confidence score and a fix checklist.",
    revenueModel: "Pay-per-application: $29–$99. Contractor monthly plan: $149/month.",
    revenuePotential: "$500K–$4M ARR",
    difficulty: "Medium",
    timeToMVP: "5–7 weeks",
    techStack: ["Next.js", "GPT-4o", "LangChain", "Supabase", "Document parsing"],
    features: [
      "Municipality-specific requirement checks",
      "Historical rejection pattern analysis",
      "Approval probability score",
      "Pre-submission fix checklist",
      "Document completeness verification",
      "Submission timeline estimator",
    ],
    whyNow: "Local governments are digitalizing permit records. LLMs can parse regulatory text. The ROI for contractors is 10:1 on day one.",
    color: "#78716c",
    gradient: "from-stone-400/20 to-stone-900/10",
  },

  // ─── FOOD / RESTAURANT ────────────────────────────────────────
  {
    id: "restaurant-profit-surgeon",
    title: "Restaurant Profit Surgeon",
    category: "Food",
    emoji: "🍽️",
    tagline: "Find every dollar your menu is secretly losing.",
    problem: "Restaurants operate on 3–9% margins. Most have no idea which menu items lose money after food cost, labor cost, and portion waste are factored in. Menus are built on intuition, not math.",
    solution: "Connect POS system. AI calculates true per-item profitability (food cost × waste × prep time × table turn rate). Generates a menu surgery report: items to kill, reprice, portion-adjust, or spotlight — with projected profit impact per change.",
    revenueModel: "Monthly SaaS: $99–$499/month. Commission on verified profit gains (1–2% of new profit).",
    revenuePotential: "$1M–$8M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "Python", "GPT-4o", "Toast/Square API", "PostgreSQL", "Recharts"],
    features: [
      "POS system integration (Toast, Square, Clover)",
      "True per-item profitability calculator",
      "Menu engineering quadrant analysis",
      "Price elasticity recommendations",
      "Portion size optimizer",
      "Weekly profit trend alerts",
    ],
    whyNow: "Every restaurant has POS data sitting unused. Post-COVID, owners are desperate to optimize. POS APIs are now open and accessible.",
    color: "#eab308",
    gradient: "from-yellow-500/20 to-amber-900/10",
  },
  {
    id: "kitchen-waste-reducer",
    title: "Kitchen Waste AI",
    category: "Food",
    emoji: "♻️",
    tagline: "Stop throwing $2,000/month in the trash.",
    problem: "Restaurants waste 4–10% of food purchased. At $30K/month food cost, that's $1,200–$3,000/month in the garbage. The culprit is almost always inaccurate prep prediction.",
    solution: "Ingests historical sales, weather, local events, day-of-week patterns, and reservation data to predict exact prep quantities for each item — down to the portion. Reduces food waste by 40–70% without stockouts.",
    revenueModel: "Monthly SaaS: $79–$349/month. ROI guarantee model (pay 20% of verified savings).",
    revenuePotential: "$1M–$6M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Python", "FastAPI", "Next.js", "POS API", "Weather API", "PostgreSQL"],
    features: [
      "Daily prep quantity recommendations",
      "Weather and event impact modeling",
      "Waste tracking dashboard",
      "Supplier order automation",
      "Leftover ingredient recipe suggestions",
      "Waste cost calculator",
    ],
    whyNow: "Food sustainability is a mainstream business priority. POS + weather data makes prediction models remarkably accurate. 40% waste reduction = $24K/year saved.",
    color: "#eab308",
    gradient: "from-yellow-500/20 to-amber-900/10",
  },

  // ─── AGRICULTURE ──────────────────────────────────────────────
  {
    id: "crop-disease-radar",
    title: "Crop Disease Early Warning Radar",
    category: "Agriculture",
    emoji: "🌾",
    tagline: "See the disease your eyes can't — 14 days before it's visible.",
    problem: "Crop diseases wipe out 20–40% of global harvests annually. Farmers detect disease only when symptoms are already visible — by then, 30–60% of the crop is lost. Early detection is the difference between a treated patch and a total loss.",
    solution: "Weekly drone or satellite imagery + soil sensor data feeds a CNN model that detects disease signatures (spectral, thermal, moisture anomalies) 14 days before visible symptoms. Sends GPS-pinpointed alert with treatment protocol.",
    revenueModel: "Per-acre subscription: $3–$8/acre/season. Agrochemical company partnerships.",
    revenuePotential: "$3M–$50M ARR",
    difficulty: "Hard",
    timeToMVP: "14–20 weeks",
    techStack: ["Python", "TensorFlow", "FastAPI", "Next.js", "Sentinel-2 API", "PostgreSQL"],
    features: [
      "Satellite and drone imagery analysis",
      "14-day pre-symptom disease detection",
      "GPS field mapping of infected zones",
      "Treatment protocol recommendations",
      "Yield loss estimation",
      "Historical disease trend reports",
    ],
    whyNow: "Sentinel-2 satellite imagery is now free and 10-day revisit. Compute costs have dropped 10x. Climate change is increasing disease frequency, making this urgent.",
    color: "#84cc16",
    gradient: "from-lime-500/20 to-green-900/10",
  },

  // ─── HR / BUSINESS ────────────────────────────────────────────
  {
    id: "employee-churn-predictor",
    title: "Employee Churn Predictor",
    category: "HR",
    emoji: "👥",
    tagline: "Know who's quitting 90 days before they hand in their notice.",
    problem: "Replacing an employee costs 50–200% of their annual salary. HR teams find out someone is leaving when they get the resignation letter — too late to do anything meaningful.",
    solution: "Analyzes engagement scores, time-on-tasks, Slack/email sentiment (opt-in), performance trends, internal mobility patterns, and market salary data to generate a per-employee 90-day churn probability with specific retention intervention suggestions.",
    revenueModel: "Per-employee SaaS: $5–$15/employee/month. 500 employees = $30K–$90K/year.",
    revenuePotential: "$3M–$20M ARR",
    difficulty: "Hard",
    timeToMVP: "10–14 weeks",
    techStack: ["Python", "FastAPI", "Next.js", "HRIS API", "Slack API (opt-in)", "NLP", "PostgreSQL"],
    features: [
      "Individual 90-day churn probability",
      "Root cause classification",
      "Salary market gap analysis",
      "Personalized retention playbook",
      "Manager action alert system",
      "Team stability risk dashboard",
    ],
    whyNow: "The Great Resignation proved retention is a $1T problem. HRIS systems now have APIs. Sentiment analysis is mature. The ROI justification writes itself.",
    isFeatured: true,
    color: "#8b5cf6",
    gradient: "from-violet-500/20 to-purple-900/10",
  },
  {
    id: "interview-emotion-coach",
    title: "AI Interview Emotion Coach",
    category: "HR",
    emoji: "🎤",
    tagline: "Practice until you can't get it wrong.",
    problem: "76% of job seekers fail interviews not because they lack skills, but because of nerves, poor framing, and weak answers to behavioral questions. Interview coaching costs $200–$500/session.",
    solution: "AI interviewer tailored to specific job/company runs live mock interviews. Provides real-time emotional tone feedback (too nervous, too flat), answer quality scores, and specific phrase improvements — recording reviewed after session.",
    revenueModel: "Consumer: $19/month unlimited practice. B2B for bootcamps: $99/student seat.",
    revenuePotential: "$500K–$5M ARR",
    difficulty: "Medium",
    timeToMVP: "5–7 weeks",
    techStack: ["Next.js", "OpenAI Whisper", "GPT-4o", "WebRTC", "Hume AI (emotion API)", "Supabase"],
    features: [
      "Real-time emotion tone analysis",
      "Company-specific question banks",
      "STAR answer framework guidance",
      "Filler word detection",
      "Post-session performance report",
      "Progress tracking over sessions",
    ],
    whyNow: "Hume AI and emotion analysis APIs are now production-ready. Job market competition is high. Bootcamps and universities are actively seeking interview prep tools.",
    color: "#8b5cf6",
    gradient: "from-violet-500/20 to-purple-900/10",
  },

  // ─── MENTAL HEALTH ────────────────────────────────────────────
  {
    id: "school-mental-health",
    title: "School Mental Health AI Check-In",
    category: "Mental Health",
    emoji: "🧠",
    tagline: "30 seconds a day. Spot the student who's silently falling apart.",
    problem: "1 in 5 students has a mental health condition. 80% never receive help. School counselors are overwhelmed — 1 per 450 students. The warning signs are there, but invisible until crisis.",
    solution: "Daily 30-second anonymous mood/energy check-in via phone or tablet. AI detects risk patterns over time (not individual responses) and routes flagged students to counselors with a narrative summary of why. No diagnosis, just early escalation.",
    revenueModel: "Per-school: $3,000–$15,000/year. District license: $20K–$100K/year.",
    revenuePotential: "$2M–$12M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "GPT-4o", "Supabase", "React Native", "Resend", "PostgreSQL"],
    features: [
      "Anonymous daily mood check-in (30 sec)",
      "Risk pattern detection over time",
      "Counselor alert routing with context",
      "Class-level mood trend dashboard",
      "FERPA / COPPA compliance",
      "Parent opt-in reporting",
    ],
    whyNow: "Youth mental health is a national emergency. Every school board is actively looking for solutions. ESSER and mental health funding grants are available.",
    isHot: true,
    color: "#ec4899",
    gradient: "from-pink-500/20 to-rose-900/10",
  },
  {
    id: "grief-companion",
    title: "Legacy Memory Keeper",
    category: "Mental Health",
    emoji: "🕯️",
    tagline: "Preserve a voice. Let the next generation know them.",
    problem: "Families lose the knowledge, wisdom, stories, and personality of loved ones forever. Current memorial solutions are static photo albums. Future generations never get to 'know' their ancestors.",
    solution: "Record conversations, upload videos/voice notes of a person over time. AI learns their speech patterns, values, and stories to create a conversational memory that family members can talk to — especially meaningful for dementia patients before memories fade.",
    revenueModel: "Annual family subscription: $99/year. Estate planning white-label: $500+/package.",
    revenuePotential: "$1M–$8M ARR",
    difficulty: "Hard",
    timeToMVP: "10–14 weeks",
    techStack: ["Next.js", "ElevenLabs", "GPT-4o", "Supabase", "FFmpeg", "React"],
    features: [
      "Personality model built from recordings",
      "Conversational memory interface",
      "Voice cloning from existing audio",
      "Photo/video timeline integration",
      "Multi-generational family sharing",
      "Privacy-first local storage option",
    ],
    whyNow: "Voice cloning (ElevenLabs) is now production-ready. Death and grief are universal. This is a genuinely underserved market with deep emotional value.",
    color: "#ec4899",
    gradient: "from-pink-500/20 to-rose-900/10",
  },

  // ─── REAL ESTATE ──────────────────────────────────────────────
  {
    id: "rental-cashflow-predictor",
    title: "Real Rental Cash Flow Predictor",
    category: "Real Estate",
    emoji: "🏡",
    tagline: "The number every investor wants. Before they buy.",
    problem: "Real estate listings show gross rent, never actual take-home. Investors overpay by 15–30% because they don't account for property tax, insurance, vacancy, management fees, maintenance, HOA, and capital expenditure reserves.",
    solution: "Enter any property address. AI pulls public records, rental comps, local tax data, insurance estimates, and maintenance history — outputs the real monthly cash flow, cap rate, and 5-year return projection with every expense itemized.",
    revenueModel: "Freemium: 3 analyses/month. Pro: $49/month unlimited. Realtor white-label: $199/month.",
    revenuePotential: "$1M–$7M ARR",
    difficulty: "Medium",
    timeToMVP: "5–7 weeks",
    techStack: ["Next.js", "Python", "Zillow/Attom API", "GPT-4o", "PostgreSQL", "Stripe"],
    features: [
      "Full expense model (all 12 cost categories)",
      "Local rental comp analysis",
      "Vacancy rate by ZIP code",
      "5-year cash flow projection",
      "Sensitivity analysis sliders",
      "Side-by-side property comparison",
    ],
    whyNow: "Property data APIs are now affordable. Millions of Americans are looking to invest in real estate with no good tools for pre-purchase analysis. This is a 10-minute demo that converts instantly.",
    color: "#14b8a6",
    gradient: "from-teal-500/20 to-cyan-900/10",
  },

  // ─── RETAIL ───────────────────────────────────────────────────
  {
    id: "retail-shrinkage-ai",
    title: "Retail Shrinkage Intelligence",
    category: "Retail",
    emoji: "🛒",
    tagline: "Find the theft your cameras miss. Stop losing $50K/year.",
    problem: "Retail shrinkage (theft + error) costs US retailers $94B/year. Most of it is organized retail crime with patterns — same days, same methods, same item categories — that are invisible in siloed point-of-sale and inventory systems.",
    solution: "Connects POS, inventory, and security system data to detect shrinkage patterns: items that sell without scanning, inventory gaps by shift, high-loss SKU/time/staff correlations. Generates weekly loss intelligence reports and real-time alerts.",
    revenueModel: "Monthly SaaS per store: $199–$799. Chain pricing: per location with volume discount.",
    revenuePotential: "$2M–$15M ARR",
    difficulty: "Medium",
    timeToMVP: "7–9 weeks",
    techStack: ["Python", "FastAPI", "Next.js", "POS API", "PostgreSQL", "anomaly detection"],
    features: [
      "Cross-system data correlation (POS + inventory)",
      "Shift-level loss attribution",
      "High-risk SKU and time window detection",
      "Employee pattern analysis (fair + anonymous)",
      "Weekly loss intelligence reports",
      "ROI tracker vs software cost",
    ],
    whyNow: "Organized retail crime is at a 20-year high. Insurance companies are demanding better monitoring. POS APIs make data correlation feasible for the first time.",
    color: "#0ea5e9",
    gradient: "from-sky-500/20 to-blue-900/10",
  },

  // ─── LOGISTICS ────────────────────────────────────────────────
  {
    id: "last-mile-optimizer",
    title: "Last-Mile Delivery Optimizer",
    category: "Logistics",
    emoji: "🚚",
    tagline: "20% fewer miles. Same deliveries. Real savings, every day.",
    problem: "Last-mile delivery is 53% of total shipping costs. Route planners still use basic GPS turn-by-turn. They ignore time windows, traffic patterns, package weight distribution, and driver skill levels.",
    solution: "AI route optimizer that incorporates live traffic, customer time windows, driver performance history, package load distribution, and fuel costs to generate routes that are 15–25% shorter by distance and 20–30% more on-time.",
    revenueModel: "Per-driver/month: $25–$75. Fleet management platform: $1,000–$10,000/month.",
    revenuePotential: "$3M–$20M ARR",
    difficulty: "Hard",
    timeToMVP: "10–14 weeks",
    techStack: ["Python", "OR-Tools", "FastAPI", "Next.js", "Google Maps API", "PostgreSQL"],
    features: [
      "Multi-constraint route optimization",
      "Live traffic integration",
      "Customer time window management",
      "Driver performance analytics",
      "Fuel cost calculator",
      "Delivery confirmation + photo",
    ],
    whyNow: "E-commerce growth has made delivery efficiency a survival issue. OR-Tools and modern APIs make complex routing optimization achievable without a PhD team.",
    color: "#06b6d4",
    gradient: "from-cyan-500/20 to-sky-900/10",
  },

  // ─── GOVERNMENT ───────────────────────────────────────────────
  {
    id: "benefits-navigator",
    title: "Government Benefits Navigator AI",
    category: "Government",
    emoji: "🏛️",
    tagline: "Find every benefit you're entitled to in 5 minutes.",
    problem: "$80B in government benefits go unclaimed every year because eligible people don't know they qualify, or the application processes are incomprehensible. Benefits offices are overwhelmed; citizens give up.",
    solution: "User answers a 5-minute conversational questionnaire (income, family size, employment status, health conditions, zip code). AI cross-references against all federal, state, and local benefit programs and generates a personalized benefits plan with application links and step-by-step instructions.",
    revenueModel: "Government contract: $50K–$500K per agency. Nonprofit white-label: subsidized pricing.",
    revenuePotential: "$2M–$15M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "GPT-4o", "LangChain", "Supabase", "benefits.gov scraping"],
    features: [
      "Conversational eligibility questionnaire",
      "All-program federal/state/local cross-reference",
      "Personalized benefits plan",
      "Application step-by-step guides",
      "Deadline reminder system",
      "Multi-language support (12 languages)",
    ],
    whyNow: "Biden-era executive orders pushed agencies to modernize access. LLMs can finally parse the complex regulatory language. Social impact plus clear government contract revenue.",
    color: "#64748b",
    gradient: "from-slate-500/20 to-slate-900/10",
  },

  // ─── WEB DESIGN ───────────────────────────────────────────────
  {
    id: "trade-website-builder",
    title: "Trade Business Website Builder",
    category: "Web Design",
    emoji: "🌐",
    tagline: "Answer 5 questions. Get a website that books jobs while you sleep.",
    problem: "63% of trade businesses (plumbers, electricians, HVAC, roofers) have no website or a site that looks like it was built in 2009. They lose $30K–$100K/year in jobs to competitors who show up on Google.",
    solution: "5-question setup: business name, services, service area, photos, contact. AI generates a complete, mobile-first trade business website with: online booking, review aggregation, service area map, emergency call button, and SEO-optimized content — deployed to custom domain in under 2 minutes.",
    revenueModel: "Monthly subscription: $49–$99/month. Setup fee: $199. Domain + hosting included.",
    revenuePotential: "$1M–$10M ARR",
    difficulty: "Medium",
    timeToMVP: "6–8 weeks",
    techStack: ["Next.js", "GPT-4o", "Vercel", "Stripe", "Twilio", "Google Maps API", "Calendly API"],
    features: [
      "2-minute site generation",
      "Online booking integration",
      "Service area map",
      "Review aggregation (Google/Yelp)",
      "Emergency call-now button",
      "SEO content auto-generation",
      "Custom domain and hosting",
    ],
    whyNow: "Wix/Squarespace are too complex for tradespeople. They need something that works out of the box. AI content generation makes auto-SEO feasible. $50B serviceable market.",
    isHot: true,
    isFeatured: true,
    color: "#a855f7",
    gradient: "from-purple-500/20 to-violet-900/10",
  },
  {
    id: "medical-practice-site",
    title: "Medical Practice Web Platform",
    category: "Web Design",
    emoji: "💊",
    tagline: "A full patient acquisition system. Not just a website.",
    problem: "Independent doctors lose 40% of potential patients to hospital systems, not because they're worse — but because they have no digital presence or booking system. A good medical website costs $3,000–$15,000 to build.",
    solution: "AI generates a complete, HIPAA-aware medical practice website: online appointment booking, insurance verification widget, doctor bio generation from CV, patient FAQ chatbot, virtual waiting room, and after-hours follow-up automation.",
    revenueModel: "Monthly SaaS: $149–$399/month. Integration add-ons (EHR sync): $99/month.",
    revenuePotential: "$2M–$12M ARR",
    difficulty: "Medium",
    timeToMVP: "7–9 weeks",
    techStack: ["Next.js", "GPT-4o", "Calendly API", "Stripe", "Twilio", "HIPAA-compliant hosting"],
    features: [
      "AI-generated doctor bios from CV upload",
      "Online appointment booking",
      "Insurance verification form",
      "Patient FAQ chatbot",
      "After-hours inquiry automation",
      "Review management integration",
    ],
    whyNow: "Telehealth normalization means patients expect seamless digital experiences. Independent practices are underserved by big EMR vendors who charge $500+/month.",
    color: "#a855f7",
    gradient: "from-purple-500/20 to-violet-900/10",
  },
  {
    id: "law-firm-site-ai",
    title: "Law Firm Client Acquisition System",
    category: "Web Design",
    emoji: "⚖️",
    tagline: "Turn website visitors into signed retainers. Automatically.",
    problem: "Solo and small law firms spend $2,000–$8,000/month on Google Ads that go to generic websites with no conversion optimization. Average law firm converts <2% of web visitors to consultations.",
    solution: "AI-built law firm site with a practice-area-specific intake bot that qualifies leads, schedules consultations, and generates a case summary before the lawyer's first call. Includes trust badges, case result showcases, and video testimonials.",
    revenueModel: "Monthly SaaS: $199–$599/month. Performance tier: $0 + 3% of new retainer value.",
    revenuePotential: "$1M–$8M ARR",
    difficulty: "Medium",
    timeToMVP: "5–7 weeks",
    techStack: ["Next.js", "GPT-4o", "Calendly", "Supabase", "Stripe", "Twilio"],
    features: [
      "Practice-area intake qualification bot",
      "Automated consultation scheduling",
      "Pre-call case summary generation",
      "Case result showcase builder",
      "Video testimonial integration",
      "Lead source attribution analytics",
    ],
    whyNow: "Legal marketing is wildly inefficient. LLMs now enable intelligent intake automation. Solo/small firms are actively switching from static websites to conversion-optimized platforms.",
    color: "#a855f7",
    gradient: "from-purple-500/20 to-violet-900/10",
  },
];

export const CATEGORIES = ["All", ...Object.keys(CATEGORY_META)];
