import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import type { Idea } from "@/app/(app)/million-ideas/ideas-data";

// ─── Utility ──────────────────────────────────────────────────────────────────

function skillName(idea: Idea): string {
  return idea.title
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

// ─── CLAUDE.md ────────────────────────────────────────────────────────────────

function claudeMd(idea: Idea): string {
  return `# ${idea.title} — CLAUDE.md

## Project Overview
**${idea.title}** is an AI-powered ${idea.category} tool.

> ${idea.tagline}

**Problem:** ${idea.problem}

**Solution:** ${idea.solution}

---

## Tech Stack
${idea.techStack.map((t) => `- ${t}`).join("\n")}

## Core Features
${idea.features.map((f) => `- ✅ ${f}`).join("\n")}

---

## Project Structure

\`\`\`
src/
  app/
    page.tsx              # Main UI — hero, input, result display
    layout.tsx            # Root layout with metadata
    globals.css           # Tailwind + CSS variables
    api/
      process/route.ts    # POST /api/process — AI processing endpoint
  lib/
    supabase.ts           # Supabase client
    utils.ts              # cn() utility
supabase/
  schema.sql              # Database schema — run in Supabase SQL editor
.claude/
  SKILLS/${skillName(idea)}Skill/
    skill.md              # Claude skill definition for this tool
agent.md                  # AI agent configuration
CLAUDE.md                 # This file
\`\`\`

---

## Development Commands

\`\`\`bash
npm install        # Install dependencies
npm run dev        # Start dev server at localhost:3000
npm run build      # Production build
npm run start      # Start production server
\`\`\`

---

## Environment Variables

Copy \`.env.example\` to \`.env.local\` and fill in your keys:

\`\`\`bash
cp .env.example .env.local
\`\`\`

Required:
- \`OPENAI_API_KEY\` — from platform.openai.com
- \`NEXT_PUBLIC_SUPABASE_URL\` — from supabase.com
- \`NEXT_PUBLIC_SUPABASE_ANON_KEY\` — from supabase.com
- \`SUPABASE_SERVICE_ROLE_KEY\` — from supabase.com

---

## Database Setup

1. Create a project at [supabase.com](https://supabase.com)
2. Open the SQL Editor
3. Run the contents of \`supabase/schema.sql\`
4. Copy your project URL and keys into \`.env.local\`

---

## AI Integration

The core AI logic lives in \`src/app/api/process/route.ts\`.

- Model: \`gpt-4o\`
- System prompt: tuned for ${idea.category} expertise
- Max tokens: 1024
- The system prompt focuses on: ${idea.solution}

To change the AI behaviour, edit the \`SYSTEM_PROMPT\` constant in the API route.

---

## Deployment (Vercel)

\`\`\`bash
npm i -g vercel
vercel --prod
\`\`\`

Add all environment variables in the Vercel dashboard under **Settings → Environment Variables**.

---

## Revenue Model

${idea.revenueModel}

**Revenue Potential:** ${idea.revenuePotential}

**Time to MVP:** ${idea.timeToMVP} · **Difficulty:** ${idea.difficulty}

---

## Why Now

${idea.whyNow}

---

*Generated by [AIHub 1M Ideas](https://aihub-eight-xi.vercel.app/million-ideas)*
`;
}

// ─── agent.md ─────────────────────────────────────────────────────────────────

function agentMd(idea: Idea): string {
  return `# ${idea.title} — Agent Configuration

## Agent Identity

**Name:** ${idea.title} AI Assistant
**Role:** Expert AI agent specialised in ${idea.category}
**Version:** 1.0.0

---

## Agent Purpose

> ${idea.tagline}

This agent helps users with ${idea.category.toLowerCase()} tasks by leveraging AI to:
${idea.features.map((f) => `- ${f}`).join("\n")}

---

## System Prompt

\`\`\`
You are an expert AI assistant for ${idea.title}, specialised in ${idea.category}.

${idea.solution}

Your responsibilities:
${idea.features.map((f, i) => `${i + 1}. ${f}`).join("\n")}

Guidelines:
- Be specific, actionable, and professional
- Always provide concrete recommendations with clear next steps
- Ask clarifying questions when the user's situation is unclear
- Cite relevant industry standards, regulations, or best practices when applicable
- Format responses with clear structure: headers, bullet points, and numbered steps
- Keep responses focused and avoid unnecessary padding
\`\`\`

---

## Capabilities

| Capability | Description |
|---|---|
${idea.features.map((f) => `| ${f.split(" ").slice(0, 3).join(" ")} | ${f} |`).join("\n")}

---

## API Endpoint

\`\`\`
POST /api/process
Content-Type: application/json

Body: { "input": "Describe your situation..." }
Response: { "result": "AI-generated response..." }
\`\`\`

---

## Model Configuration

\`\`\`json
{
  "model": "gpt-4o",
  "max_tokens": 1024,
  "temperature": 0.7,
  "provider": "OpenAI"
}
\`\`\`

---

## Usage Examples

**Example input:**
> "I need help with ${idea.category.toLowerCase()} — specifically around ${idea.features[0]?.toLowerCase() ?? "my main challenge"}"

**Example output:**
> The agent analyses the situation, identifies the key pain point, and provides step-by-step actionable recommendations tailored to ${idea.category}.

---

## Revenue Model

${idea.revenueModel}

---

## Integration Notes

- Connect this agent to your Supabase database to log all interactions
- Enable Supabase RLS policies to keep user data private
- Use the sessions table to track conversation history
- Set up rate limiting at the API route level for production

---

*${idea.title} · Built with AIHub 1M Ideas*
`;
}

// ─── .claude/SKILLS/[Name]Skill/skill.md ─────────────────────────────────────

function skillMd(idea: Idea): string {
  const name = skillName(idea);
  return `---
name: ${name}Skill
description: AI skill for ${idea.title} — ${idea.tagline}
version: 1.0.0
category: ${idea.category}
difficulty: ${idea.difficulty}
---

# ${name} Skill

## What This Skill Does

${idea.solution}

This skill enables Claude to act as a specialised ${idea.category} expert, providing users with:
${idea.features.map((f) => `- ${f}`).join("\n")}

---

## When to Use This Skill

Activate this skill when the user needs help with:
- Any ${idea.category.toLowerCase()} related task or question
- Analysis and recommendations for: ${idea.features.slice(0, 3).join(", ")}
- Building or improving AI-powered ${idea.category.toLowerCase()} tools
- Understanding the ${idea.category.toLowerCase()} market and revenue opportunities

---

## Skill Behaviour

When this skill is active, Claude should:

1. **Adopt the persona** of a world-class ${idea.category} expert with deep AI knowledge
2. **Focus exclusively** on ${idea.category.toLowerCase()} use cases and challenges
3. **Provide structured responses** with clear sections, bullet points, and actionable steps
4. **Reference specific tools** from the tech stack: ${idea.techStack.join(", ")}
5. **Quantify recommendations** with dollar amounts, time estimates, and ROI projections

---

## System Prompt Integration

\`\`\`
You are an expert ${idea.category} AI assistant powered by ${idea.title}.

Problem you solve: ${idea.problem}

Your solution approach: ${idea.solution}

Always:
- Be specific and data-driven
- Reference real ${idea.category.toLowerCase()} workflows and pain points
- Suggest concrete implementation steps using: ${idea.techStack.slice(0, 3).join(", ")}
- Quantify the value you provide (time saved, cost reduced, revenue generated)

Revenue model context: ${idea.revenueModel}
\`\`\`

---

## Example Interactions

### Example 1 — Analysis Request
**User:** "Help me analyse my ${idea.category.toLowerCase()} situation"
**Skill response:** Provides structured analysis with key findings, risk factors, and recommended next steps

### Example 2 — Implementation Help
**User:** "How do I implement ${idea.features[0]?.toLowerCase() ?? "this feature"}?"
**Skill response:** Step-by-step technical guide with code examples, timeline, and resource requirements

### Example 3 — Revenue Strategy
**User:** "How should I price this tool?"
**Skill response:** Pricing strategy aligned with: ${idea.revenueModel}

---

## Tech Stack Reference

${idea.techStack.map((t) => `- **${t}** — core technology for this skill`).join("\n")}

---

## Output Format Guidelines

Always structure responses as:

\`\`\`markdown
## Summary
[1-2 sentence overview]

## Key Findings / Recommendations
- Point 1
- Point 2
- Point 3

## Action Steps
1. Step one (timeline: X days)
2. Step two (timeline: X days)

## Resources
- [Relevant link or tool]
\`\`\`

---

## Skill Metadata

| Field | Value |
|---|---|
| Revenue Potential | ${idea.revenuePotential} |
| Time to MVP | ${idea.timeToMVP} |
| Build Difficulty | ${idea.difficulty} |
| Why Now | ${idea.whyNow} |

---

*Skill generated by [AIHub 1M Ideas](https://aihub-eight-xi.vercel.app/million-ideas)*
`;
}

// ─── Existing file generators (unchanged) ─────────────────────────────────────

function packageJson(idea: Idea): string {
  return JSON.stringify(
    {
      name: idea.id,
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "15.1.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        typescript: "^5",
        tailwindcss: "^4",
        "lucide-react": "^0.468.0",
        openai: "^4.77.0",
        "@supabase/supabase-js": "^2.47.0",
        "framer-motion": "^11.15.0",
        ...(idea.techStack.some((t) => t.toLowerCase().includes("stripe"))
          ? { stripe: "^17.5.0", "@stripe/stripe-js": "^5.5.0" } : {}),
        ...(idea.techStack.some((t) => t.toLowerCase().includes("recharts"))
          ? { recharts: "^2.13.0" } : {}),
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
      },
    },
    null,
    2,
  );
}

function envExample(idea: Idea): string {
  const lines = [
    "# ─── App ────────────────────────────────────",
    "NEXT_PUBLIC_APP_URL=http://localhost:3000",
    "",
    "# ─── OpenAI ─────────────────────────────────",
    "OPENAI_API_KEY=sk-...",
    "",
    "# ─── Supabase ───────────────────────────────",
    "NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key",
    "SUPABASE_SERVICE_ROLE_KEY=your-service-key",
  ];
  if (idea.techStack.some((t) => t.toLowerCase().includes("stripe"))) {
    lines.push("", "# ─── Stripe ─────────────────────────────────");
    lines.push("STRIPE_SECRET_KEY=sk_test_...");
    lines.push("NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...");
    lines.push("STRIPE_WEBHOOK_SECRET=whsec_...");
  }
  if (idea.techStack.some((t) => t.toLowerCase().includes("twilio"))) {
    lines.push("", "# ─── Twilio ─────────────────────────────────");
    lines.push("TWILIO_ACCOUNT_SID=AC...");
    lines.push("TWILIO_AUTH_TOKEN=...");
    lines.push("TWILIO_PHONE_NUMBER=+1...");
  }
  return lines.join("\n");
}

function rootLayout(idea: Idea): string {
  return `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "${idea.title}",
  description: "${idea.tagline}",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`;
}

function globalsCss(): string {
  return `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #0a0a0a;
  --primary: #6366f1;
  --muted: #f4f4f5;
  --border: #e4e4e7;
  --radius: 0.625rem;
}

* { box-sizing: border-box; }
body {
  background: var(--background);
  color: var(--foreground);
  font-family: var(--font-sans), system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
}
`;
}

function mainPage(idea: Idea): string {
  return `"use client";

import { useState } from "react";
import { Sparkles, ArrowRight, CheckCircle2 } from "lucide-react";

const FEATURES = ${JSON.stringify(idea.features, null, 2)};

export default function HomePage() {
  const [input, setInput] = useState("");
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!input.trim()) return;
    setLoading(true);
    try {
      const res = await fetch("/api/process", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input }),
      });
      const data = await res.json();
      setResult(data.result);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-950 text-white">
      <section className="max-w-4xl mx-auto px-6 pt-24 pb-16 text-center">
        <div className="inline-flex items-center gap-2 bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm px-4 py-2 rounded-full mb-8">
          <Sparkles className="w-4 h-4" />
          ${idea.category} · AI-Powered
        </div>
        <h1 className="text-5xl md:text-6xl font-black leading-tight mb-6">${idea.title}</h1>
        <p className="text-xl text-slate-400 max-w-2xl mx-auto mb-12 leading-relaxed">${idea.tagline}</p>

        <form onSubmit={handleSubmit} className="max-w-2xl mx-auto">
          <div className="flex gap-3">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Describe your situation or question..."
              className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
            />
            <button
              type="submit"
              disabled={loading}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white px-6 py-3 rounded-xl font-semibold transition-colors"
            >
              {loading ? "Analyzing..." : "Analyze"}
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </form>

        {result && (
          <div className="mt-8 max-w-2xl mx-auto bg-white/5 border border-white/10 rounded-2xl p-6 text-left">
            <p className="text-slate-300 leading-relaxed whitespace-pre-wrap">{result}</p>
          </div>
        )}
      </section>

      <section className="max-w-4xl mx-auto px-6 pb-24">
        <h2 className="text-2xl font-bold text-center mb-12 text-slate-200">What It Does</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {FEATURES.map((feature, i) => (
            <div key={i} className="flex items-start gap-3 bg-white/3 border border-white/5 rounded-xl p-4">
              <CheckCircle2 className="w-5 h-5 text-indigo-400 flex-shrink-0 mt-0.5" />
              <span className="text-slate-300 text-sm">{feature}</span>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
`;
}

function apiRoute(idea: Idea): string {
  return `import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const SYSTEM_PROMPT = \`You are an AI assistant for ${idea.title}, specialised in ${idea.category}.

${idea.solution}

Analyse the user's input and provide a clear, actionable, specific response.
Be direct, precise, and professional. Use bullet points and structure for clarity.\`;

export async function POST(req: NextRequest) {
  try {
    const { input } = await req.json();
    if (!input?.trim()) return NextResponse.json({ error: "Input required" }, { status: 400 });

    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: input },
      ],
      max_tokens: 1024,
    });

    return NextResponse.json({ result: completion.choices[0]?.message?.content ?? "" });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: "Processing failed" }, { status: 500 });
  }
}
`;
}

function supabaseClient(): string {
  return `import { createClient } from "@supabase/supabase-js";

const supabaseUrl  = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey  = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseKey);
`;
}

function readme(idea: Idea): string {
  return `# ${idea.title}

> ${idea.tagline}

## Overview

**Problem:** ${idea.problem}

**Solution:** ${idea.solution}

## Revenue Model

${idea.revenueModel} — **Potential:** ${idea.revenuePotential}

## Quick Start

\`\`\`bash
npm install
cp .env.example .env.local   # fill in your keys
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000)

## Tech Stack

${idea.techStack.map((t) => `- ${t}`).join("\n")}

## Features

${idea.features.map((f) => `- ✅ ${f}`).join("\n")}

## Build Info

**Difficulty:** ${idea.difficulty} · **Time to MVP:** ${idea.timeToMVP}

## Why Now

${idea.whyNow}

## Deploy

\`\`\`bash
npx vercel --prod
\`\`\`

See \`CLAUDE.md\` for full development guide and \`.claude/SKILLS/\` for AI skill configuration.

---
*Generated by [AIHub 1M Ideas](https://aihub-eight-xi.vercel.app/million-ideas)*
`;
}

function supabaseSchema(idea: Idea): string {
  return `-- ${idea.title} — Supabase Schema
create extension if not exists "uuid-ossp";

create table if not exists sessions (
  id         uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  user_email text,
  metadata   jsonb default '{}'
);

create table if not exists requests (
  id             uuid primary key default uuid_generate_v4(),
  session_id     uuid references sessions(id),
  created_at     timestamptz default now(),
  input          text not null,
  output         text,
  processing_ms  integer,
  model          text default 'gpt-4o'
);

alter table sessions enable row level security;
alter table requests enable row level security;

create policy "Public sessions" on sessions for all using (true);
create policy "Public requests" on requests for all using (true);

create index if not exists idx_requests_session on requests(session_id);
create index if not exists idx_requests_created on requests(created_at desc);
`;
}

// ─── Main ZIP builder ─────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const { idea } = (await req.json()) as { idea: Idea };
    if (!idea?.id || !idea?.title) {
      return NextResponse.json({ error: "Missing idea data" }, { status: 400 });
    }

    const zip  = new JSZip();
    const root = zip.folder(idea.id)!;
    const name = skillName(idea);

    // ── Root files ──────────────────────────────────────────
    root.file("CLAUDE.md",      claudeMd(idea));
    root.file("agent.md",       agentMd(idea));
    root.file("README.md",      readme(idea));
    root.file("package.json",   packageJson(idea));
    root.file(".env.example",   envExample(idea));
    root.file("next.config.ts", `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`);
    root.file("tsconfig.json",  JSON.stringify({
      compilerOptions: {
        target: "ES2017", lib: ["dom","dom.iterable","esnext"], allowJs: true,
        skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true,
        module: "esnext", moduleResolution: "bundler", resolveJsonModule: true,
        isolatedModules: true, jsx: "preserve", incremental: true,
        plugins: [{ name: "next" }], paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts","**/*.ts","**/*.tsx",".next/types/**/*.ts"],
      exclude: ["node_modules"],
    }, null, 2));

    // ── .claude/SKILLS/[Name]Skill/ ─────────────────────────
    const claudeDir = root.folder(".claude")!;
    const skillsDir = claudeDir.folder("SKILLS")!;
    const skillDir  = skillsDir.folder(`${name}Skill`)!;
    skillDir.file("skill.md", skillMd(idea));

    // ── src/ ────────────────────────────────────────────────
    const src = root.folder("src")!;
    const app = src.folder("app")!;
    app.file("layout.tsx",    rootLayout(idea));
    app.file("globals.css",   globalsCss());
    app.file("page.tsx",      mainPage(idea));

    const processRoute = app.folder("api")!.folder("process")!;
    processRoute.file("route.ts", apiRoute(idea));

    const lib = src.folder("lib")!;
    lib.file("supabase.ts", supabaseClient());
    lib.file("utils.ts", `import { clsx, type ClassValue } from "clsx";\nimport { twMerge } from "tailwind-merge";\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}\n`);

    // ── supabase/ ───────────────────────────────────────────
    root.folder("supabase")!.file("schema.sql", supabaseSchema(idea));

    const buffer   = await zip.generateAsync({ type: "arraybuffer" });
    const filename = `${idea.id}-starter-kit.zip`;

    return new NextResponse(buffer, {
      headers: {
        "Content-Type":        "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length":      buffer.byteLength.toString(),
      },
    });
  } catch (err) {
    console.error("[download-idea]", err);
    return NextResponse.json({ error: "Download failed: " + String(err) }, { status: 500 });
  }
}
